/*
 * locale.c — kernel32's locales: names and LCIDs, GetLocaleInfo,
 * enumeration.
 *
 * Every locale Windows knows is in locale_data.h (generated by
 * tools/gen_locales.py from .NET's own copy of the Windows table): its
 * name, LCID, code pages, GEOID, list separator and fallbacks.  English
 * (en-US, en) and the invariant locale answer from the tables below, as
 * they always have; for every other locale the rest of GetLocaleInfo
 * (names in the locale's own language, number symbols and patterns, day
 * and month names, date and time formats, first day of the week...) comes
 * from ICU (icu.dll, loaded the first time such a locale is asked about),
 * the way .NET derives the same values on Linux.  A field ICU cannot
 * answer falls back to the en-US value.
 *
 * The user's locale is HKCU\Control Panel\International's LocaleName
 * (written by intl.exe and the Settings app's "Time & language" page), read
 * once per process; the system locale stays en-US.
 */
#define NOVA_BUILD_KERNEL32
#include <winternl.h>
#include <winreg.h>
#include "k32.h"
#include "locale_data.h"

void *memcpy(void *d, const void *s, size_t n);
void *memset(void *d, int c, size_t n);
size_t strlen(const char *s);

#define K32 __declspec(dllexport)
#ifndef LOAD_LIBRARY_SEARCH_SYSTEM32
#define LOAD_LIBRARY_SEARCH_SYSTEM32 0x00000800
#endif

#define LOCALE_NOUSEROVERRIDE_       0x80000000u
#define LOCALE_USE_CP_ACP_           0x40000000u
#define LOCALE_RETURN_NUMBER_        0x20000000u
#define LOCALE_RETURN_GENITIVE_NAMES_ 0x10000000u
#define LOCALE_ALLOW_NEUTRAL_NAMES_  0x08000000u
#define LOCALE_CUSTOM_UNSPECIFIED_   0x1000u
#ifndef LOCALE_NAME_MAX_LENGTH
#define LOCALE_NAME_MAX_LENGTH 85
#endif
#ifndef LOCALE_INVARIANT
#define LOCALE_INVARIANT 0x007F
#endif
typedef DWORD LCTYPE_;

/* special "indexes" besides the table's */
#define LOC_INVARIANT (-2)
#define LOC_NONE      (-1)

static int wlen(const WCHAR *s) { int n = 0; if (s) while (s[n]) n++; return n; }
static char lower(char c) { return c >= 'A' && c <= 'Z' ? (char)(c + 32) : c; }

/* -----------------------------------------------------------------------
 * Names and LCIDs
 * ----------------------------------------------------------------------- */
static int cmp_lower(const char *a, const char *b)
{
    for (;; a++, b++) {
        char x = lower(*a), y = lower(*b);
        if (x != y) return (unsigned char)x - (unsigned char)y;
        if (!x) return 0;
    }
}

static int find_ascii(const char *name)
{
    int lo = 0, hi = NOVA_LOCALE_COUNT - 1;
    while (lo <= hi) {
        int mid = (lo + hi) / 2, c = cmp_lower(g_locales[mid].name, name);
        if (!c) return mid;
        if (c < 0) lo = mid + 1; else hi = mid - 1;
    }
    return LOC_NONE;
}

static int en_us(void) { static int i = -3; if (i == -3) i = find_ascii("en-US"); return i; }

/* The user's locale: LocaleName under HKCU\Control Panel\International
 * (or, without it, the LCID in "Locale"), read the first time it is needed;
 * en-US when neither names a locale.  A specific locale only: a neutral
 * name ("de") becomes its default ("de-DE"). */
static int lcid_index(LCID lcid);
static int locale_index(LPCWSTR w);
static volatile LONG g_user = -3;

static int user_locale(void)
{
    int i = g_user;
    if (i != -3) return i;
    i = LOC_NONE;
    HKEY k;
    if (!RegOpenKeyExW(HKEY_CURRENT_USER, L"Control Panel\\International", 0, KEY_READ, &k)) {
        WCHAR v[LOCALE_NAME_MAX_LENGTH + 1];
        DWORD type, n = sizeof(v) - sizeof(WCHAR);
        if (!RegQueryValueExW(k, L"LocaleName", NULL, &type, (BYTE *)v, &n) && type == REG_SZ && n >= 4) {
            v[n / 2] = 0;
            i = locale_index(v);
        }
        n = sizeof(v) - sizeof(WCHAR);
        if (i < 0 && !RegQueryValueExW(k, L"Locale", NULL, &type, (BYTE *)v, &n) && type == REG_SZ) {
            v[n / 2] = 0;
            LCID l = 0;
            for (const WCHAR *c = v; *c; c++) {
                int d = *c >= '0' && *c <= '9' ? *c - '0' : (*c | 0x20) >= 'a' && (*c | 0x20) <= 'f' ? (*c | 0x20) - 'a' + 10 : -1;
                if (d < 0) { l = 0; break; }
                l = l * 16 + (LCID)d;
            }
            if (l) i = lcid_index(l);
        }
        RegCloseKey(k);
    }
    if (i >= 0 && g_locales[i].specific >= 0) i = g_locales[i].specific;
    if (i < 0 || g_locales[i].lcid == LOCALE_CUSTOM_UNSPECIFIED_) i = en_us();
    InterlockedExchange(&g_user, i);
    return i;
}

/* a locale name (NULL: the user's; "": invariant) -> a table index */
static int locale_index(LPCWSTR w)
{
    static const char sysdef[] = "!x-sys-default-locale";
    char a[LOCALE_NAME_MAX_LENGTH + 1];
    if (!w) return user_locale();                            /* LOCALE_NAME_USER_DEFAULT */
    if (!w[0]) return LOC_INVARIANT;
    int n = wlen(w);
    if (n > LOCALE_NAME_MAX_LENGTH) return LOC_NONE;
    for (int i = 0; i <= n; i++) {
        if (w[i] > 0x7F) return LOC_NONE;
        a[i] = (char)w[i];
    }
    if (!cmp_lower(a, sysdef)) return en_us();
    int i = find_ascii(a);
    if (i >= 0) return i;
    /* ICU-style "de_DE": '_' for '-' (the last '_' may be a sort: "de-DE_phoneb") */
    for (char *p = a; *p; p++) if (*p == '_') *p = '-';
    if ((i = find_ascii(a)) >= 0) return i;
    char *last = 0;
    for (char *p = a; *p; p++) if (*p == '-') last = p;
    if (last) { *last = '_'; i = find_ascii(a); }
    return i;
}

static int lcid_index(LCID lcid)
{
    if (lcid == LOCALE_INVARIANT) return LOC_INVARIANT;
    if (lcid == 0 || lcid == LOCALE_USER_DEFAULT || lcid == 0x0C00 /* LOCALE_CUSTOM_DEFAULT */)
        return user_locale();
    if (lcid == LOCALE_SYSTEM_DEFAULT || lcid == 0x1400 /* LOCALE_CUSTOM_UI_DEFAULT */)
        return en_us();
    if (lcid == LOCALE_CUSTOM_UNSPECIFIED_) return LOC_NONE;
    int legacy = LOC_NONE;
    for (int i = 0; i < NOVA_LOCALE_COUNT; i++) {
        if (g_locales[i].lcid != lcid) continue;
        if (!cmp_lower(g_locales[i].name, "zh-CHS") || !cmp_lower(g_locales[i].name, "zh-CHT")) {
            legacy = i;                                      /* 0x4/0x7C4: zh-Hans/zh-Hant first */
            continue;
        }
        return i;
    }
    return legacy;
}

static BOOL is_neutral(int i) { return i >= 0 && g_locales[i].specific != i; }
static BOOL is_sort(int i)    { for (const char *p = g_locales[i].name; *p; p++) if (*p == '_') return TRUE; return FALSE; }

static int put_name(const char *s, LPWSTR out, int cap)
{
    int n = (int)strlen(s);
    if (!cap) return n + 1;
    if (!out || cap <= n) { SetLastError(ERROR_INSUFFICIENT_BUFFER); return 0; }
    for (int i = 0; i <= n; i++) out[i] = (WCHAR)(unsigned char)s[i];
    return n + 1;
}

/* the parent: "de-DE" -> "de", "zh-CN" -> "zh-Hans", "de" -> "" */
static const char *parent_of(int i, char *buf)
{
    const char *n = g_locales[i].name;
    if (!cmp_lower(n, "zh-CN") || !cmp_lower(n, "zh-SG")) return "zh-Hans";
    if (!cmp_lower(n, "zh-TW") || !cmp_lower(n, "zh-HK") || !cmp_lower(n, "zh-MO")) return "zh-Hant";
    int len = 0, cut = -1;
    for (; n[len] && n[len] != '_'; len++) if (n[len] == '-') cut = len;
    if (cut < 0) return "";
    memcpy(buf, n, (SIZE_T)cut);
    buf[cut] = 0;
    int p = find_ascii(buf);
    return p >= 0 ? g_locales[p].name : "";
}

K32 BOOL  WINAPI IsValidLocaleName(LPCWSTR n) { return n && locale_index(n) != LOC_NONE; }
K32 BOOL  WINAPI IsValidLocale(LCID lcid, DWORD f) { (void)f; return lcid_index(lcid) != LOC_NONE; }

K32 LCID WINAPI LocaleNameToLCID(LPCWSTR n, DWORD f)
{
    int i = locale_index(n);
    if (i == LOC_INVARIANT) return LOCALE_INVARIANT;
    (void)f;                                                 /* (neutral names have LCIDs too) */
    if (i < 0) { SetLastError(ERROR_INVALID_PARAMETER); return 0; }
    return g_locales[i].lcid;
}

K32 int WINAPI LCIDToLocaleName(LCID lcid, LPWSTR n, int cap, DWORD f)
{
    int i = lcid_index(lcid);
    if (i == LOC_INVARIANT) { if (cap && n) n[0] = 0; return 1; }
    if (i < 0) { SetLastError(ERROR_INVALID_PARAMETER); return 0; }
    if (is_neutral(i) && !(f & LOCALE_ALLOW_NEUTRAL_NAMES_) && g_locales[i].specific >= 0)
        i = g_locales[i].specific;
    return put_name(g_locales[i].name, n, cap);
}

K32 int WINAPI ResolveLocaleName(LPCWSTR name, LPWSTR out, int cap)
{
    int i = locale_index(name);
    if (i == LOC_INVARIANT) { if (out && cap) out[0] = 0; return 1; }
    if (i < 0) { SetLastError(ERROR_INVALID_PARAMETER); return 0; }
    if (g_locales[i].specific >= 0) i = g_locales[i].specific;
    return put_name(g_locales[i].name, out, cap);
}

/* (the user interface itself is English: the UI languages stay en-US) */
K32 LCID WINAPI GetUserDefaultLCID(void)       { return g_locales[user_locale()].lcid; }
K32 LCID WINAPI GetSystemDefaultLCID(void)     { return 0x409; }
K32 LCID WINAPI GetThreadLocale(void)          { return GetUserDefaultLCID(); }
K32 BOOL WINAPI SetThreadLocale(LCID lcid)     { return IsValidLocale(lcid, 0); }
K32 WORD WINAPI GetUserDefaultLangID(void)     { return (WORD)GetUserDefaultLCID(); }
K32 WORD WINAPI GetSystemDefaultLangID(void)   { return 0x409; }
K32 WORD WINAPI GetUserDefaultUILanguage(void) { return 0x409; }
K32 WORD WINAPI GetSystemDefaultUILanguage(void) { return 0x409; }
K32 int  WINAPI GetUserDefaultLocaleName(LPWSTR n, int cap)
{
    return put_name(g_locales[user_locale()].name, n, cap ? cap : 1);
}
K32 int  WINAPI GetSystemDefaultLocaleName(LPWSTR n, int cap) { return put_name("en-US", n, cap ? cap : 1); }

/* LOCALE_WINDOWS 1, LOCALE_SUPPLEMENTAL 2, LOCALE_ALTERNATE_SORTS 4,
 * LOCALE_NEUTRALDATA 0x10, LOCALE_SPECIFICDATA 0x20 */
K32 BOOL WINAPI EnumSystemLocalesEx(BOOL (WINAPI *fn)(LPWSTR, DWORD, LPARAM), DWORD f, LPARAM p, LPVOID r)
{
    (void)r;
    if (!fn) { SetLastError(ERROR_INVALID_PARAMETER); return FALSE; }
    for (int i = 0; i < NOVA_LOCALE_COUNT; i++) {
        BOOL sort = is_sort(i), neutral = is_neutral(i);
        if (sort ? !(f & 4) : (f & 4) && !(f & ~4u)) continue;     /* alternate sorts only when asked */
        if ((f & 0x10) && !(f & 0x20) && !neutral) continue;
        if ((f & 0x20) && !(f & 0x10) && neutral) continue;
        WCHAR w[LOCALE_NAME_MAX_LENGTH + 1];
        put_name(g_locales[i].name, w, LOCALE_NAME_MAX_LENGTH + 1);
        if (!fn(w, 1 | (sort ? 4 : 0) | (neutral ? 0x10 : 0x20), p)) break;
    }
    return TRUE;
}

/* LCIDs as 8 hex digits; LCID_INSTALLED/LCID_SUPPORTED alike */
static void lcid_hex(LCID l, char *s)
{
    for (int k = 7; k >= 0; k--, l >>= 4) s[k] = "0123456789ABCDEF"[l & 15];
    s[8] = 0;
}
K32 BOOL WINAPI EnumSystemLocalesW(BOOL (WINAPI *fn)(LPWSTR), DWORD f)
{
    (void)f;
    for (int i = 0; i < NOVA_LOCALE_COUNT; i++) {
        if (g_locales[i].lcid == LOCALE_CUSTOM_UNSPECIFIED_ || is_neutral(i)) continue;
        char s[9];
        WCHAR w[9];
        lcid_hex(g_locales[i].lcid, s);
        for (int k = 0; k < 9; k++) w[k] = (WCHAR)s[k];
        if (!fn(w)) break;
    }
    return TRUE;
}
K32 BOOL WINAPI EnumSystemLocalesA(BOOL (WINAPI *fn)(LPSTR), DWORD f)
{
    (void)f;
    for (int i = 0; i < NOVA_LOCALE_COUNT; i++) {
        if (g_locales[i].lcid == LOCALE_CUSTOM_UNSPECIFIED_ || is_neutral(i)) continue;
        char s[9];
        lcid_hex(g_locales[i].lcid, s);
        if (!fn(s)) break;
    }
    return TRUE;
}

/* -----------------------------------------------------------------------
 * English and the invariant locale: fixed tables
 * ----------------------------------------------------------------------- */
enum { LOC_EN_US, LOC_EN, LOC_INV };

static const char *english_value(int loc, DWORD t)
{
    BOOL inv = loc == LOC_INV, neutral = loc == LOC_EN;
    switch (t) {                                                 /* what differs by locale */
    case 0x01: return inv ? "007F" : neutral ? "0009" : "0409";  /* LOCALE_ILANGUAGE */
    case 0x02: case 0x72: return inv ? "Invariant Language (Invariant Country)" : neutral ? "English" : "English (United States)";
    case 0x73: return inv ? "Invariant Language (Invariant Country)" : neutral ? "English" : "English (United States)";
    case 0x5C: return inv ? "" : neutral ? "en" : "en-US";       /* LOCALE_SNAME */
    case 0x6D: return neutral || inv ? "" : "en";                /* LOCALE_SPARENT */
    case 0x71: return neutral ? "1" : "0";                       /* LOCALE_INEUTRAL */
    case 0x5A: return inv ? "IV" : neutral ? "" : "US";          /* LOCALE_SISO3166CTRYNAME */
    case 0x68: return inv ? "IVC" : neutral ? "" : "USA";        /* LOCALE_SISO3166CTRYNAME2 */
    case 0x59: return inv ? "iv" : "en";                         /* LOCALE_SISO639LANGNAME */
    case 0x67: return inv ? "ivl" : "eng";                       /* LOCALE_SISO639LANGNAME2 */
    case 0x06: case 0x08: case 0x1002: return inv ? "Invariant Country" : neutral ? "" : "United States";
    case 0x5B: return inv ? "39070" : "244";                     /* LOCALE_IGEOID */
    case 0x14: return inv ? "\xC2\xA4" : "$";                    /* LOCALE_SCURRENCY */
    case 0x15: return inv ? "XDR" : "USD";                       /* LOCALE_SINTLSYMBOL */
    case 0x1007: return inv ? "International Monetary Fund" : "US Dollar";   /* LOCALE_SENGCURRNAME */
    case 0x1008: return inv ? "International Monetary Fund" : "US Dollar";   /* LOCALE_SNATIVECURRNAME */
    case 0x1F: return inv ? "MM/dd/yyyy" : "M/d/yyyy";           /* LOCALE_SSHORTDATE */
    case 0x20: return inv ? "dddd, dd MMMM yyyy" : "dddd, MMMM d, yyyy";      /* LOCALE_SLONGDATE */
    case 0x1003: return inv ? "HH:mm:ss" : "h:mm:ss tt";         /* LOCALE_STIMEFORMAT */
    case 0x79: return inv ? "HH:mm" : "h:mm tt";                 /* LOCALE_SSHORTTIME */
    case 0x23: return inv ? "1" : "0";                           /* LOCALE_ITIME (24-hour) */
    case 0x100C: return inv ? "0" : "6";                         /* LOCALE_IFIRSTDAYOFWEEK: Monday 0 ... Sunday 6 */
    case 0x0D: return inv ? "0" : "1";                           /* LOCALE_IMEASURE: metric 0, US 1 */
    case 0x100A: return inv ? "9" : "1";                         /* LOCALE_IPAPERSIZE: A4 9, letter 1 */
    }
    switch (t) {                                                 /* the same for all three */
    case 0x03: return "ENU";                                     /* LOCALE_SABBREVLANGNAME */
    case 0x04: case 0x1001: case 0x6F: return "English";         /* native / English / localized language name */
    case 0x05: return "1";                                       /* LOCALE_ICOUNTRY */
    case 0x07: return "USA";                                     /* LOCALE_SABBREVCTRYNAME */
    case 0x0B: return "437";                                     /* LOCALE_IDEFAULTCODEPAGE (OEM) */
    case 0x1004: return "1252";                                  /* LOCALE_IDEFAULTANSICODEPAGE */
    case 0x1011: return "10000";                                 /* LOCALE_IDEFAULTMACCODEPAGE */
    case 0x1012: return "037";                                   /* LOCALE_IDEFAULTEBCDICCODEPAGE */
    case 0x0C: return ",";                                       /* LOCALE_SLIST */
    case 0x0E: return ".";                                       /* LOCALE_SDECIMAL */
    case 0x0F: return ",";                                       /* LOCALE_STHOUSAND */
    case 0x10: return "3;0";                                     /* LOCALE_SGROUPING */
    case 0x11: return "2";                                       /* LOCALE_IDIGITS */
    case 0x12: return "1";                                       /* LOCALE_ILZERO */
    case 0x13: return "0123456789";                              /* LOCALE_SNATIVEDIGITS */
    case 0x16: return ".";                                       /* LOCALE_SMONDECIMALSEP */
    case 0x17: return ",";                                       /* LOCALE_SMONTHOUSANDSEP */
    case 0x18: return "3;0";                                     /* LOCALE_SMONGROUPING */
    case 0x19: return "2";                                       /* LOCALE_ICURRDIGITS */
    case 0x1A: return "2";                                       /* LOCALE_IINTLCURRDIGITS */
    case 0x1B: return "0";                                       /* LOCALE_ICURRENCY: $1.1 */
    case 0x1C: return "1";                                       /* LOCALE_INEGCURR: -$1.1 */
    case 0x1D: return "/";                                       /* LOCALE_SDATE */
    case 0x1E: return ":";                                       /* LOCALE_STIME */
    case 0x21: return "0";                                       /* LOCALE_IDATE: M-D-Y */
    case 0x22: return "0";                                       /* LOCALE_ILDATE */
    case 0x24: return "1";                                       /* LOCALE_ICENTURY */
    case 0x25: return "0";                                       /* LOCALE_ITLZERO */
    case 0x26: return "0";                                       /* LOCALE_IDAYLZERO */
    case 0x27: return "0";                                       /* LOCALE_IMONLZERO */
    case 0x28: return "AM";                                      /* LOCALE_S1159 */
    case 0x29: return "PM";                                      /* LOCALE_S2359 */
    case 0x50: return "";                                        /* LOCALE_SPOSITIVESIGN */
    case 0x51: return "-";                                       /* LOCALE_SNEGATIVESIGN */
    case 0x52: return "3";                                       /* LOCALE_IPOSSIGNPOSN */
    case 0x53: return "0";                                       /* LOCALE_INEGSIGNPOSN */
    case 0x5D: return "h:mm:ss";                                 /* LOCALE_SDURATION */
    case 0x69: return "NaN";                                     /* LOCALE_SNAN */
    case 0x6A: return "Infinity";                                /* LOCALE_SPOSINFINITY */
    case 0x6B: return "-Infinity";                               /* LOCALE_SNEGINFINITY */
    case 0x6C: return "Latn;";                                   /* LOCALE_SSCRIPTS */
    case 0x6E: return "en-US";                                   /* LOCALE_SCONSOLEFALLBACKNAME */
    case 0x70: return "0";                                       /* LOCALE_IREADINGLAYOUT: left to right */
    case 0x74: return "1";                                       /* LOCALE_INEGATIVEPERCENT: -n % */
    case 0x75: return "1";                                       /* LOCALE_IPOSITIVEPERCENT: n % */
    case 0x76: return "%";                                       /* LOCALE_SPERCENT */
    case 0x77: return "\xE2\x80\xB0";                            /* LOCALE_SPERMILLE */
    case 0x78: return "MMMM d";                                  /* LOCALE_SMONTHDAY */
    case 0x7A: return "ENU";                                     /* LOCALE_SOPENTYPELANGUAGETAG */
    case 0x7B: return "";                                        /* LOCALE_SSORTLOCALE */
    case 0x1006: return "MMMM yyyy";                             /* LOCALE_SYEARMONTH */
    case 0x1009: return "1";                                     /* LOCALE_ICALENDARTYPE: Gregorian */
    case 0x100B: return "0";                                     /* LOCALE_IOPTIONALCALENDAR */
    case 0x100D: return "0";                                     /* LOCALE_IFIRSTWEEKOFYEAR */
    case 0x100E: case 0x100F: return "";                         /* LOCALE_SMONTHNAME13, ABBREV13 */
    case 0x1010: return "1";                                     /* LOCALE_INEGNUMBER: -1.1 */
    case 0x1014: return "1";                                     /* LOCALE_IDIGITSUBSTITUTION: none */
    case 0x1016: return "en-US";                                 /* LOCALE_SNATIVELANGUAGE... (unused) */
    }
    if (t >= 0x2A && t <= 0x30) {                                /* LOCALE_SDAYNAME1..7 (Monday first) */
        static const char *d[] = { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" };
        return d[t - 0x2A];
    }
    if (t >= 0x31 && t <= 0x37) {
        static const char *d[] = { "Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun" };
        return d[t - 0x31];
    }
    if (t >= 0x60 && t <= 0x66) {                                /* LOCALE_SSHORTESTDAYNAME1..7 */
        static const char *d[] = { "Mo", "Tu", "We", "Th", "Fr", "Sa", "Su" };
        return d[t - 0x60];
    }
    if (t >= 0x38 && t <= 0x43) {
        static const char *m[] = { "January", "February", "March", "April", "May", "June", "July", "August",
                                   "September", "October", "November", "December" };
        return m[t - 0x38];
    }
    if (t >= 0x44 && t <= 0x4F) {
        static const char *m[] = { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" };
        return m[t - 0x44];
    }
    return 0;
}

/* -----------------------------------------------------------------------
 * ICU (C:\Windows\System32\icu.dll), for every other locale
 * ----------------------------------------------------------------------- */
typedef int UErrorCode;
#define U_FAILURE(e) ((e) > 0)
enum { UNUM_DECIMAL = 1, UNUM_CURRENCY = 2, UNUM_PERCENT = 3 };
enum { UDAT_FULL = 0, UDAT_LONG = 1, UDAT_MEDIUM = 2, UDAT_SHORT = 3, UDAT_NONE = -1 };
#define UDAT_DEFAULT_STYLE_ UDAT_MEDIUM
enum { UDAT_MONTHS = 1, UDAT_SHORT_MONTHS = 2, UDAT_WEEKDAYS = 3, UDAT_SHORT_WEEKDAYS = 4, UDAT_AM_PMS = 5,
       UDAT_STANDALONE_MONTHS = 10, UDAT_STANDALONE_SHORT_MONTHS = 11, UDAT_SHORTER_WEEKDAYS = 20 };
enum { UNUM_MAX_FRACTION_DIGITS = 6, UNUM_GROUPING_SIZE = 10, UNUM_SECONDARY_GROUPING_SIZE = 15 };

#define ICU_FUNCS(X) \
    X(int, uloc_getDisplayName, (const char *, const char *, WCHAR *, int, UErrorCode *)) \
    X(int, uloc_getDisplayLanguage, (const char *, const char *, WCHAR *, int, UErrorCode *)) \
    X(int, uloc_getDisplayCountry, (const char *, const char *, WCHAR *, int, UErrorCode *)) \
    X(int, uloc_getLanguage, (const char *, char *, int, UErrorCode *)) \
    X(int, uloc_getCountry, (const char *, char *, int, UErrorCode *)) \
    X(const char *, uloc_getISO3Language, (const char *)) \
    X(const char *, uloc_getISO3Country, (const char *)) \
    X(int, uloc_addLikelySubtags, (const char *, char *, int, UErrorCode *)) \
    X(int, uloc_getScript, (const char *, char *, int, UErrorCode *)) \
    X(int, uloc_getCharacterOrientation, (const char *, UErrorCode *)) \
    X(void *, unum_open, (int, const WCHAR *, int, const char *, void *, UErrorCode *)) \
    X(void, unum_close, (void *)) \
    X(int, unum_getSymbol, (const void *, int, WCHAR *, int, UErrorCode *)) \
    X(int, unum_getAttribute, (const void *, int)) \
    X(int, unum_toPattern, (const void *, signed char, WCHAR *, int, UErrorCode *)) \
    X(void *, udat_open, (int, int, const char *, const WCHAR *, int, const WCHAR *, int, UErrorCode *)) \
    X(void, udat_close, (void *)) \
    X(int, udat_toPattern, (const void *, signed char, WCHAR *, int, UErrorCode *)) \
    X(int, udat_getSymbols, (const void *, int, int, WCHAR *, int, UErrorCode *)) \
    X(void *, udatpg_open, (const char *, UErrorCode *)) \
    X(void, udatpg_close, (void *)) \
    X(int, udatpg_getBestPattern, (void *, const WCHAR *, int, WCHAR *, int, UErrorCode *)) \
    X(void *, ucal_open, (const WCHAR *, int, const char *, int, UErrorCode *)) \
    X(void, ucal_close, (void *)) \
    X(int, ucal_getAttribute, (const void *, int)) \
    X(int, ulocdata_getMeasurementSystem, (const char *, UErrorCode *)) \
    X(void, ulocdata_getPaperSize, (const char *, int *, int *, UErrorCode *)) \
    X(int, ucurr_forLocale, (const char *, WCHAR *, int, UErrorCode *)) \
    X(const WCHAR *, ucurr_getName, (const WCHAR *, const char *, int, signed char *, int *, UErrorCode *))

static struct {
#define ICU_PTR(ret, name, args) ret (*name) args;
    ICU_FUNCS(ICU_PTR)
} icu;
static volatile LONG g_icu_state;                    /* 0 not tried, 1 loaded, 2 unavailable */

static BOOL icu_load(void)
{
    if (g_icu_state) return g_icu_state == 1;
    HMODULE h = LoadLibraryExW(L"icu.dll", NULL, LOAD_LIBRARY_SEARCH_SYSTEM32);
    BOOL ok = h != NULL;
#define ICU_GET(ret, name, args) \
    if (ok && !(icu.name = (ret (*) args)GetProcAddress(h, #name))) ok = FALSE;
    ICU_FUNCS(ICU_GET)
    InterlockedExchange(&g_icu_state, ok ? 1 : 2);
    return ok;
}

/* the table's name as an ICU locale id: de-DE -> de_DE (a sort suffix dropped) */
static void icu_id(int i, char *out)
{
    const char *n = g_locales[i].name;
    int k = 0;
    for (; n[k] && n[k] != '_' && k < 31; k++) out[k] = n[k] == '-' ? '_' : n[k];
    out[k] = 0;
}

static int ascii_out(const char *s, WCHAR *out, int cap)
{
    int n = 0;
    for (; s[n] && n < cap - 1; n++) out[n] = (WCHAR)(unsigned char)s[n];
    out[n] = 0;
    return n;
}

static int dec_out(int v, WCHAR *out, int cap)
{
    char s[16];
    int n = 0;
    unsigned u = v < 0 ? (unsigned)-v : (unsigned)v;
    do s[n++] = (char)('0' + u % 10); while ((u /= 10) && n < 15);
    if (v < 0) s[n++] = '-';
    int k = 0;
    while (n && k < cap - 1) out[k++] = (WCHAR)s[--n];
    out[k] = 0;
    return k;
}

static int symbol(const char *loc, int style, int sym, WCHAR *out, int cap)
{
    UErrorCode e = 0;
    void *f = icu.unum_open(style, NULL, 0, loc, NULL, &e);
    int n = U_FAILURE(e) ? -1 : icu.unum_getSymbol(f, sym, out, cap, &e);
    if (f) icu.unum_close(f);
    return U_FAILURE(e) ? -1 : n;
}

static int num_attr(const char *loc, int style, int attr)
{
    UErrorCode e = 0;
    void *f = icu.unum_open(style, NULL, 0, loc, NULL, &e);
    int v = U_FAILURE(e) ? -1 : icu.unum_getAttribute(f, attr);
    if (f) icu.unum_close(f);
    return v;
}

/* Number pattern indexes (LOCALE_ICURRENCY, INEGCURR, INEGNUMBER,
 * INEGATIVEPERCENT, IPOSITIVEPERCENT): the ICU pattern reduced to its
 * shape ("-n %", "(C n)") and looked up in Windows' list, as .NET's
 * pal_localeNumberData.c (MIT) does */
static int number_pattern(const char *loc, int style, int negative, const char *const *list, int count, int dflt)
{
    UErrorCode e = 0;
    WCHAR p[128];
    void *f = icu.unum_open(style, NULL, 0, loc, NULL, &e);
    if (U_FAILURE(e)) { if (f) icu.unum_close(f); return dflt; }
    int len = icu.unum_toPattern(f, 0, p, 128, &e);
    icu.unum_close(f);
    if (U_FAILURE(e) || len <= 0 || len >= 128) return dflt;
    int start = 0, end = len - 1, semi = -1;
    for (int i = 0; i < len; i++) if (p[i] == ';') semi = i;
    if (semi >= 0) { if (negative) start = semi + 1; else end = semi - 1; }
    BOOL minus = FALSE, digit = FALSE, cur = FALSE, space = FALSE;
    for (int i = start; i <= end; i++) if (p[i] == '-' || p[i] == '(' || p[i] == ')') minus = TRUE;
    char shape[16];
    int k = 0;
    if (negative && !minus) shape[k++] = '-';
    for (int i = start; i <= end && k < 14; i++) {
        WCHAR c = p[i];
        if (c == '#' || c == '0') { if (!digit) { digit = TRUE; shape[k++] = 'n'; } }
        else if (c == 0xA4) { if (!cur) { cur = TRUE; shape[k++] = 'C'; } }
        else if (c == ' ' || c == 0xA0) { if (!space) { space = TRUE; shape[k++] = ' '; } }
        else if (c == '-' || c == '(' || c == ')') shape[k++] = (char)c;
        else if (c == '%') shape[k++] = '%';
    }
    shape[k] = 0;
    for (int i = 0; i < count; i++) {
        const char *a = list[i], *b = shape;
        while (*a && *a == *b) a++, b++;
        if (!*a && !*b) return i;
    }
    return dflt;
}

/* An ICU date pattern in Windows' notation (.NET's CalendarData
 * NormalizeDatePattern and ConvertIcuTimeFormatString, MIT): EEEE ->
 * dddd, a -> tt, y -> yyyy, G -> g, LLLL -> MMMM */
static int date_pattern(const WCHAR *in, int n, WCHAR *out, int cap, BOOL time)
{
    int k = 0, i = 0;
    BOOL ampm = FALSE;
#define PUT(c) do { if (k < cap - 1) out[k++] = (c); } while (0)
    while (i < n) {
        WCHAR c = in[i];
        int run = 1;
        while (i + run < n && in[i + run] == c) run++;
        if (c == '\'') {                                     /* quoted text verbatim */
            PUT(in[i++]);
            while (i < n) { WCHAR q = in[i++]; PUT(q); if (q == '\'') break; }
            continue;
        }
        i += run;
        switch (c) {
        case 'E': case 'e': case 'c':
            run = run < 3 ? 3 : run > 4 ? 3 : run;
            while (run--) PUT('d');
            break;
        case 'L': case 'M':
            if (run > 4) run = 3;
            while (run--) PUT('M');
            break;
        case 'G': PUT('g'); break;
        case 'y':
            if (run == 1) run = 4;
            while (run--) PUT('y');
            break;
        case 'a': case 'b': case 'B':
            if (!ampm) { ampm = TRUE; PUT('t'); PUT('t'); }
            break;
        default:
            if (time && ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z')) &&
                c != 'H' && c != 'h' && c != 'm' && c != 's')
                break;                                       /* zones and the like: none in Windows formats */
            while (run--) PUT(c);
        }
    }
    /* a space left at either end by a dropped field */
    while (k && out[k - 1] == ' ') k--;
    int lead = 0;
    while (lead < k && out[lead] == ' ') lead++;
    if (lead) { for (int j = lead; j < k; j++) out[j - lead] = out[j]; k -= lead; }
    out[k] = 0;
    return k;
#undef PUT
}

/* @date/@time: the UDAT_* style (UDAT_NONE: not this half) */
static int icu_pattern(const char *loc, int date, int time, WCHAR *out, int cap)
{
    UErrorCode e = 0;
    WCHAR p[128];
    void *f = icu.udat_open(time, date, loc, NULL, 0, NULL, 0, &e);
    int n = U_FAILURE(e) ? -1 : icu.udat_toPattern(f, 0, p, 128, &e);
    if (f) icu.udat_close(f);
    if (U_FAILURE(e) || n <= 0 || n >= 128) return -1;
    return date_pattern(p, n, out, cap, date == UDAT_NONE);
}

static int icu_skeleton(const char *loc, const WCHAR *skel, WCHAR *out, int cap)
{
    UErrorCode e = 0;
    WCHAR p[128];
    void *g = icu.udatpg_open(loc, &e);
    int n = U_FAILURE(e) ? -1 : icu.udatpg_getBestPattern(g, skel, -1, p, 128, &e);
    if (g) icu.udatpg_close(g);
    if (U_FAILURE(e) || n <= 0 || n >= 128) return -1;
    return date_pattern(p, n, out, cap, FALSE);
}

static int date_symbol(const char *loc, int type, int index, WCHAR *out, int cap)
{
    UErrorCode e = 0;
    void *f = icu.udat_open(UDAT_DEFAULT_STYLE_, UDAT_DEFAULT_STYLE_, loc, NULL, 0, NULL, 0, &e);
    int n = U_FAILURE(e) ? -1 : icu.udat_getSymbols(f, type, index, out, cap, &e);
    if (f) icu.udat_close(f);
    return U_FAILURE(e) ? -1 : n;
}

static int cal_attr(const char *loc, int attr)
{
    UErrorCode e = 0;
    void *c = icu.ucal_open(NULL, 0, loc, 0 /* UCAL_TRADITIONAL */, &e);
    int v = U_FAILURE(e) ? -1 : icu.ucal_getAttribute(c, attr);
    if (c) icu.ucal_close(c);
    return v;
}

/* the first character of @pat that separates fields (LOCALE_SDATE, STIME) */
static int separator(const WCHAR *pat, WCHAR *out, int cap)
{
    for (int i = 0; pat[i]; i++) {
        WCHAR c = pat[i];
        if (c == '\'') { while (pat[++i] && pat[i] != '\'') { } if (!pat[i]) break; continue; }
        if ((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z')) continue;
        if (cap > 1) { out[0] = c; out[1] = 0; return 1; }
    }
    return -1;
}

static BOOL has(const WCHAR *pat, const char *s)
{
    for (int i = 0; pat[i]; i++) {
        int k = 0;
        while (s[k] && pat[i + k] == (WCHAR)s[k]) k++;
        if (!s[k]) return TRUE;
    }
    return FALSE;
}

/* "3;0" (and "3;2;0" for Indian-style groups) */
static int grouping(const char *loc, int style, WCHAR *out, int cap)
{
    int p = num_attr(loc, style, UNUM_GROUPING_SIZE), s = num_attr(loc, style, UNUM_SECONDARY_GROUPING_SIZE);
    if (p < 0) return -1;
    char g[16];
    int k = 0;
    g[k++] = (char)('0' + p % 10);
    if (s > 0 && s != p) { g[k++] = ';'; g[k++] = (char)('0' + s % 10); }
    g[k++] = ';'; g[k++] = '0'; g[k] = 0;
    return ascii_out(g, out, cap);
}

/* LOCALE_IDATE/ILDATE: 0 month-day-year, 1 day-month-year, 2 year-month-day */
static int date_order(const WCHAR *pat)
{
    int y = -1, m = -1, d = -1;
    for (int i = 0; pat[i]; i++) {
        WCHAR c = pat[i];
        if (c == '\'') { while (pat[++i] && pat[i] != '\'') { } if (!pat[i]) break; continue; }
        if (c == 'y' && y < 0) y = i;
        if (c == 'M' && m < 0) m = i;
        if (c == 'd' && d < 0 && !(pat[i + 1] == 'd' && pat[i + 2] == 'd')) d = i;
    }
    if (y >= 0 && (m < 0 || y < m) && (d < 0 || y < d)) return 2;
    if (d >= 0 && m >= 0 && d < m) return 1;
    return 0;
}

static int icu_value(int idx, DWORD t, DWORD flags, WCHAR *out, int cap)
{
    char loc[32];
    icu_id(idx, loc);
    UErrorCode e = 0;
    char a[32];
    int n = -1;
    switch (t) {
    case 0x02: case 0x72: n = icu.uloc_getDisplayName(loc, "en", out, cap, &e); break;
    case 0x73: n = icu.uloc_getDisplayName(loc, loc, out, cap, &e); break;
    case 0x04: n = icu.uloc_getDisplayLanguage(loc, loc, out, cap, &e); break;
    case 0x1001: case 0x6F: n = icu.uloc_getDisplayLanguage(loc, "en", out, cap, &e); break;
    case 0x08: n = icu.uloc_getDisplayCountry(loc, loc, out, cap, &e); break;
    case 0x06: case 0x1002: n = icu.uloc_getDisplayCountry(loc, "en", out, cap, &e); break;
    case 0x59: n = icu.uloc_getLanguage(loc, a, sizeof(a), &e); if (!U_FAILURE(e)) n = ascii_out(a, out, cap); break;
    case 0x5A: n = icu.uloc_getCountry(loc, a, sizeof(a), &e); if (!U_FAILURE(e)) n = ascii_out(a, out, cap); break;
    case 0x67: n = ascii_out(icu.uloc_getISO3Language(loc), out, cap); break;
    case 0x68: case 0x07: n = ascii_out(icu.uloc_getISO3Country(loc), out, cap); break;
    case 0x6C: {                                             /* LOCALE_SSCRIPTS */
        char full[64], s[16];
        icu.uloc_addLikelySubtags(loc, full, sizeof(full), &e);
        if (!U_FAILURE(e)) icu.uloc_getScript(full, s, sizeof(s), &e);
        if (!U_FAILURE(e) && s[0]) { n = ascii_out(s, out, cap - 1); out[n++] = ';'; out[n] = 0; }
        break;
    }
    case 0x70: n = icu.uloc_getCharacterOrientation(loc, &e) == 1 ? ascii_out("1", out, cap) : ascii_out("0", out, cap); break;
    case 0x0E: n = symbol(loc, UNUM_DECIMAL, 0, out, cap); break;
    case 0x0F: n = symbol(loc, UNUM_DECIMAL, 1, out, cap); break;
    case 0x16: n = symbol(loc, UNUM_CURRENCY, 10, out, cap); break;
    case 0x17: n = symbol(loc, UNUM_CURRENCY, 17, out, cap); break;
    case 0x14:                                               /* LOCALE_SCURRENCY */
        n = symbol(loc, UNUM_CURRENCY, 8, out, cap);
        if (n == 1 && out[0] == 0xFFE5) out[0] = 0xA5;       /* Windows' yen sign is the narrow one */
        break;
    case 0x15: n = symbol(loc, UNUM_CURRENCY, 9, out, cap); break;
    case 0x51: n = symbol(loc, UNUM_DECIMAL, 6, out, cap); break;
    case 0x76: n = symbol(loc, UNUM_DECIMAL, 3, out, cap); break;
    case 0x77: n = symbol(loc, UNUM_DECIMAL, 12, out, cap); break;
    case 0x69: n = symbol(loc, UNUM_DECIMAL, 15, out, cap); break;
    case 0x6A: n = symbol(loc, UNUM_DECIMAL, 14, out, cap); break;
    case 0x6B: {
        int m = symbol(loc, UNUM_DECIMAL, 6, out, cap);
        if (m > 0 && m < cap - 1) { int r = symbol(loc, UNUM_DECIMAL, 14, out + m, cap - m); n = r < 0 ? -1 : m + r; }
        break;
    }
    case 0x13: {                                             /* LOCALE_SNATIVEDIGITS */
        if (cap < 11) break;
        static const int sym[10] = { 4, 18, 19, 20, 21, 22, 23, 24, 25, 26 };
        n = 10;
        for (int d = 0; d < 10; d++) {
            WCHAR w[4];
            if (symbol(loc, UNUM_DECIMAL, sym[d], w, 4) != 1) { n = -1; break; }
            out[d] = w[0];
        }
        if (n == 10) out[10] = 0;
        break;
    }
    case 0x10: n = grouping(loc, UNUM_DECIMAL, out, cap); break;
    case 0x18: n = grouping(loc, UNUM_CURRENCY, out, cap); break;
    case 0x19: case 0x1A: {
        int v = num_attr(loc, UNUM_CURRENCY, UNUM_MAX_FRACTION_DIGITS);
        if (v >= 0) n = dec_out(v, out, cap);
        break;
    }
    case 0x1B: {
        static const char *const p[] = { "Cn", "nC", "C n", "n C" };
        n = dec_out(number_pattern(loc, UNUM_CURRENCY, 0, p, 4, 0), out, cap);
        break;
    }
    case 0x1C: {
        static const char *const p[] = { "(Cn)", "-Cn", "C-n", "Cn-", "(nC)", "-nC", "n-C", "nC-", "-n C", "-C n",
                                         "n C-", "C n-", "C -n", "n- C", "(C n)", "(n C)", "C- n" };
        n = dec_out(number_pattern(loc, UNUM_CURRENCY, 1, p, 17, 0), out, cap);
        break;
    }
    case 0x1010: {
        static const char *const p[] = { "(n)", "-n", "- n", "n-", "n -" };
        n = dec_out(number_pattern(loc, UNUM_DECIMAL, 1, p, 5, 1), out, cap);
        break;
    }
    case 0x74: {
        static const char *const p[] = { "-n %", "-n%", "-%n", "%-n", "%n-", "n-%", "n%-", "-% n", "n %-", "% n-",
                                         "% -n", "n- %" };
        n = dec_out(number_pattern(loc, UNUM_PERCENT, 1, p, 12, 0), out, cap);
        break;
    }
    case 0x75: {
        static const char *const p[] = { "n %", "n%", "%n", "% n" };
        n = dec_out(number_pattern(loc, UNUM_PERCENT, 0, p, 4, 0), out, cap);
        break;
    }
    case 0x1F:                                               /* LOCALE_SSHORTDATE */
        n = icu_pattern(loc, UDAT_SHORT, UDAT_NONE, out, cap);
        if (n > 0 && !has(out, "yyy") && has(out, "yy") && n + 2 < cap) {   /* yy -> yyyy, as Windows */
            int y = 0;
            while (!(out[y] == 'y' && out[y + 1] == 'y')) y++;
            for (int j = n; j >= y; j--) out[j + 2] = out[j];
            n += 2;
        }
        break;
    case 0x20:                                               /* LOCALE_SLONGDATE */
        n = icu_pattern(loc, UDAT_FULL, UDAT_NONE, out, cap);
        /* Windows' long dates for Chinese and Japanese have no weekday
         * ("yyyy年M月d日"): where ICU's full date ends in one glued to the
         * day, as there, take its long date instead */
        if (n > 4 && out[n - 1] == 'd' && out[n - 2] == 'd' && out[n - 3] == 'd' && out[n - 4] == 'd' &&
            out[n - 5] != ' ' && out[n - 5] != ',' && out[n - 5] != '\'')
            n = icu_pattern(loc, UDAT_LONG, UDAT_NONE, out, cap);
        break;
    case 0x1003: n = icu_pattern(loc, UDAT_NONE, UDAT_MEDIUM, out, cap); break;
    case 0x79: n = icu_pattern(loc, UDAT_NONE, UDAT_SHORT, out, cap); break;
    case 0x1006: n = icu_skeleton(loc, L"yMMMM", out, cap); break;
    case 0x78: n = icu_skeleton(loc, L"MMMMd", out, cap); break;
    case 0x1D: case 0x21: case 0x24: case 0x26: case 0x27: {
        WCHAR p[128];
        if (icu_pattern(loc, UDAT_SHORT, UDAT_NONE, p, 128) <= 0) break;
        if (t == 0x1D) n = separator(p, out, cap);
        else if (t == 0x21) n = dec_out(date_order(p), out, cap);
        else if (t == 0x24) n = ascii_out("1", out, cap);    /* (SSHORTDATE always has yyyy) */
        else n = ascii_out(has(p, t == 0x26 ? "dd" : "MM") ? "1" : "0", out, cap);
        break;
    }
    case 0x22: {
        WCHAR p[128];
        if (icu_pattern(loc, UDAT_FULL, UDAT_NONE, p, 128) > 0) n = dec_out(date_order(p), out, cap);
        break;
    }
    case 0x1E: case 0x23: case 0x25: {
        WCHAR p[128];
        if (icu_pattern(loc, UDAT_NONE, UDAT_MEDIUM, p, 128) <= 0) break;
        if (t == 0x1E) n = separator(p, out, cap);
        else if (t == 0x23) n = ascii_out(has(p, "H") ? "1" : "0", out, cap);
        else n = ascii_out(has(p, "HH") || has(p, "hh") ? "1" : "0", out, cap);
        break;
    }
    case 0x28: n = date_symbol(loc, UDAT_AM_PMS, 0, out, cap); break;
    case 0x29: n = date_symbol(loc, UDAT_AM_PMS, 1, out, cap); break;
    case 0x100C: {                                           /* ICU: Sunday 1; Windows: Monday 0 */
        int d = cal_attr(loc, 1 /* UCAL_FIRST_DAY_OF_WEEK */);
        if (d >= 1) n = dec_out((d + 5) % 7, out, cap);
        break;
    }
    case 0x100D: {
        int m = cal_attr(loc, 2 /* UCAL_MINIMAL_DAYS_IN_FIRST_WEEK */);
        if (m >= 1) n = dec_out(m == 1 ? 0 : m == 7 ? 1 : 2, out, cap);
        break;
    }
    case 0x0D: {
        int ms = icu.ulocdata_getMeasurementSystem(loc, &e);
        if (!U_FAILURE(e)) n = ascii_out(ms == 1 ? "1" : "0", out, cap);
        break;
    }
    case 0x100A: {
        int h = 0, w = 0;
        icu.ulocdata_getPaperSize(loc, &h, &w, &e);
        if (!U_FAILURE(e)) n = ascii_out(h == 279 ? "1" : h == 356 ? "5" : "9", out, cap);
        break;
    }
    case 0x1007: case 0x1008: {                              /* currency names */
        WCHAR code[4];
        icu.ucurr_forLocale(loc, code, 4, &e);
        if (U_FAILURE(e)) break;
        signed char choice = 0;
        int len = 0;
        const WCHAR *s = icu.ucurr_getName(code, t == 0x1007 ? "en" : loc, 1 /* UCURR_LONG_NAME */, &choice, &len, &e);
        if (!U_FAILURE(e) && s && len < cap) { memcpy(out, s, 2 * (SIZE_T)len); out[len] = 0; n = len; }
        break;
    }
    default:
        if (t >= 0x2A && t <= 0x37) {                        /* day names, Monday first */
            int d = (t - 0x2A) % 7;
            n = date_symbol(loc, t < 0x31 ? UDAT_WEEKDAYS : UDAT_SHORT_WEEKDAYS, d == 6 ? 1 : d + 2, out, cap);
        } else if (t >= 0x60 && t <= 0x66) {
            int d = t - 0x60;
            n = date_symbol(loc, UDAT_SHORTER_WEEKDAYS, d == 6 ? 1 : d + 2, out, cap);
        } else if (t >= 0x38 && t <= 0x4F) {                 /* month names */
            BOOL abbr = t >= 0x44, gen = (flags & LOCALE_RETURN_GENITIVE_NAMES_) != 0;
            int type = abbr ? (gen ? UDAT_SHORT_MONTHS : UDAT_STANDALONE_SHORT_MONTHS)
                            : (gen ? UDAT_MONTHS : UDAT_STANDALONE_MONTHS);
            n = date_symbol(loc, type, (int)(t - (abbr ? 0x44 : 0x38)), out, cap);
        }
        break;
    }
    if (U_FAILURE(e) || n < 0 || n >= cap) return -1;
    out[n] = 0;
    return n;
}

/* what the table itself says (every locale); -1: not one of these */
static int table_value(int i, DWORD t, WCHAR *out, int cap)
{
    const NovaLocale *l = &g_locales[i];
    char buf[LOCALE_NAME_MAX_LENGTH + 1];
    switch (t) {
    case 0x01: {                                             /* LOCALE_ILANGUAGE: 4 hex digits */
        char h[5];
        for (int k = 3, v = (int)(l->lcid & 0xFFFF); k >= 0; k--, v >>= 4) h[k] = "0123456789abcdef"[v & 15];
        h[4] = 0;
        return ascii_out(h, out, cap);
    }
    case 0x5C: return ascii_out(l->name, out, cap);          /* LOCALE_SNAME */
    case 0x6D: return ascii_out(parent_of(i, buf), out, cap);
    case 0x71: return ascii_out(is_neutral(i) ? "1" : "0", out, cap);
    case 0x03: return ascii_out(l->abbrev, out, cap);
    case 0x1004: return dec_out(l->ansi, out, cap);
    case 0x0B: return dec_out(l->oem, out, cap);
    case 0x1011: return dec_out(l->mac, out, cap);
    case 0x1012: return dec_out(l->ebcdic, out, cap);
    case 0x5B: return dec_out((int)l->geo, out, cap);
    case 0x1014: return dec_out(l->sep & 0xF, out, cap);
    case 0x0C: {
        static const WCHAR seps[5][3] = { L",", L";", L"\x060C", L"\x061B", L",," };
        int k = l->sep >> 4;
        if (k > 4) k = 0;
        int n = wlen(seps[k]);
        if (cap <= n) return -1;
        memcpy(out, seps[k], 2 * (SIZE_T)(n + 1));
        return n;
    }
    case 0x6E: return ascii_out(l->console >= 0 ? g_locales[l->console].name : "en-US", out, cap);
    case 0x7B: return ascii_out(l->name, out, cap);          /* LOCALE_SSORTLOCALE */
    case 0x7A: return ascii_out(l->abbrev, out, cap);        /* (OpenType tags are mostly the same) */
    case 0x50: return ascii_out("", out, cap);               /* LOCALE_SPOSITIVESIGN */
    case 0x11: return ascii_out("2", out, cap);              /* LOCALE_IDIGITS */
    case 0x1009: return ascii_out("1", out, cap);            /* LOCALE_ICALENDARTYPE: Gregorian */
    }
    return -1;
}

/* LOCALE_* @type of locale @idx (a table index or LOC_INVARIANT) into @out */
static int locale_info(int idx, DWORD type, WCHAR *out, int cap)
{
    DWORD t = type & 0xFFFF;
    int en = idx == LOC_INVARIANT ? LOC_INV : idx == en_us() ? LOC_EN_US :
             !cmp_lower(g_locales[idx].name, "en") ? LOC_EN : -1;
    if (en < 0) {
        int n = table_value(idx, t, out, cap);
        if (n >= 0) return n;
        if (icu_load() && (n = icu_value(idx, t, type, out, cap)) >= 0) return n;
        en = LOC_EN_US;                                      /* no better answer: en-US's */
    }
    const char *v = english_value(en, t);
    if (!v) return -2;
    return u2w(v, -1, out, cap - 1);
}

static int get_info(int idx, DWORD type, LPWSTR buf, int n)
{
    if (idx == LOC_NONE) { SetLastError(ERROR_INVALID_PARAMETER); return 0; }
    if (n < 0 || (n && !buf)) { SetLastError(ERROR_INVALID_PARAMETER); return 0; }
    WCHAR w[256];
    int k = locale_info(idx, type, w, 256);
    if (k == -2 || k < 0) { SetLastError(1004 /* ERROR_INVALID_FLAGS */); return 0; }
    w[k] = 0;
    if (type & LOCALE_RETURN_NUMBER_) {
        DWORD num = 0, t = type & 0xFFFF;
        if (t == 0x01) num = idx == LOC_INVARIANT ? 0x7F : g_locales[idx].lcid;  /* (hex) */
        else for (const WCHAR *c = w; *c >= '0' && *c <= '9'; c++) num = num * 10 + (DWORD)(*c - '0');
        if (!n) return 2;
        if (n < 2) { SetLastError(ERROR_INSUFFICIENT_BUFFER); return 0; }
        memcpy(buf, &num, 4);
        return 2;
    }
    if (!n) return k + 1;
    if (n <= k) { SetLastError(ERROR_INSUFFICIENT_BUFFER); return 0; }
    memcpy(buf, w, 2 * (SIZE_T)(k + 1));
    return k + 1;
}

K32 int WINAPI GetLocaleInfoEx(LPCWSTR name, LCTYPE_ type, LPWSTR buf, int n)
{
    return get_info(locale_index(name), type, buf, n);
}

K32 int WINAPI GetLocaleInfoW(LCID lcid, LCTYPE_ type, LPWSTR buf, int n)
{
    return get_info(lcid_index(lcid), type, buf, n);
}

K32 int WINAPI GetLocaleInfoA(LCID lcid, LCTYPE_ type, LPSTR buf, int n)
{
    WCHAR w[256];
    int k = get_info(lcid_index(lcid), type & ~LOCALE_RETURN_NUMBER_, w, 256);
    if (!k) return 0;
    if (type & LOCALE_RETURN_NUMBER_) {
        DWORD num;
        if (!get_info(lcid_index(lcid), type, (LPWSTR)&num, 2)) return 0;
        if (!n) return 4;
        if (n < 4) { SetLastError(ERROR_INSUFFICIENT_BUFFER); return 0; }
        memcpy(buf, &num, 4);
        return 4;
    }
    return WideCharToMultiByte(CP_ACP, 0, w, -1, buf, n, NULL, NULL);
}

/* -----------------------------------------------------------------------
 * For the formatting functions (nlsformat.c)
 * ----------------------------------------------------------------------- */
int nls_lcid(LCID lcid)        { return lcid_index(lcid); }
int nls_name(LPCWSTR name)     { return locale_index(name); }

/* LOCALE_* @type of locale @idx into @out (cap 256 is plenty): its length,
 * or -1 */
int nls_info(int idx, DWORD type, WCHAR *out, int cap)
{
    if (idx == LOC_NONE) return -1;
    int n = locale_info(idx, type, out, cap);
    if (n < 0 || n >= cap) return -1;
    out[n] = 0;
    return n;
}

/* the Gregorian era's abbreviation ("A.D.", "n. Chr.", "西暦") */
int nls_era(int idx, WCHAR *out, int cap)
{
    int n = -1;
    if (idx >= 0 && idx != en_us() && cmp_lower(g_locales[idx].name, "en") && icu_load()) {
        char loc[32];
        icu_id(idx, loc);
        n = date_symbol(loc, 0 /* UDAT_ERAS */, 1, out, cap);
    }
    if (n < 0 || n >= cap) n = u2w("A.D.", -1, out, cap - 1);
    out[n] = 0;
    return n;
}
