/* userland_files.h — the Windows userland embedded in the kernel image
 * (generated by tools/build_userland.py; installed on drive C: at boot) */
#pragma once

typedef struct {
    const char          *path;      /* e.g. "\\Windows\\System32\\kernel32.dll" */
    const unsigned char *data;
    unsigned int         size;
} UserlandFile;

extern const UserlandFile g_userland_files[];
extern const int          g_userland_file_count;
