/*
 * timezone.h — time zones and local time
 *
 * The hardware clock keeps UTC.  The time zone the user chose (first-boot
 * setup, Settings, or a program calling SetDynamicTimeZoneInformation) is
 * kept where Windows keeps it, HKLM\SYSTEM\CurrentControlSet\Control\
 * TimeZoneInformation (Bias, StandardName/Bias/Start, DaylightName/Bias/
 * Start, TimeZoneKeyName), and local time comes from those values: the
 * desktop clock, the Start menu, the Terminal's date and time, Calendar.
 * kernel32 reads the same values for GetTimeZoneInformation and
 * GetLocalTime.
 *
 * The zones on offer are tzdata.inc, generated by tools/gen_timezones.py
 * from Unicode CLDR's Windows zone names and the IANA tz database's rules.
 */

#pragma once

#include "../include/types.h"
#include "../hal/rtc.h"

/* A change between standard and daylight time, as Windows writes it in a
 * SYSTEMTIME: in month, the week-th (5 = the last) weekday dow (0 =
 * Sunday), at hour:minute local time.  month 0: the zone has no daylight
 * saving time. */
typedef struct {
    UINT8 month, dow, week, hour, minute;
} TzRule;

typedef struct {
    const char *key;            /* the Windows name ("W. Europe Standard Time") */
    const char *display;        /* "(UTC+01:00) Berlin, Rome, Amsterdam" */
    const char *std, *dlt;      /* StandardName, DaylightName */
    INT32  bias;                /* minutes: UTC = local + bias */
    INT32  dst_bias;            /* added to bias in daylight time (-60) */
    TzRule std_date;            /* back to standard time (in daylight time) */
    TzRule dst_date;            /* into daylight time (in standard time) */
} TzZone;

/* Windows' SYSTEMTIME and REG_TZI_FORMAT (the TZI registry value) */
typedef struct {
    UINT16 year, month, dow, day, hour, minute, second, ms;
} TzSystemTime;

typedef struct {
    INT32 bias, std_bias, dst_bias;
    TzSystemTime std_date, dst_date;
} TzTzi;

int           TzCount(void);
const TzZone *TzAt(int i);
int           TzFind(const char *key);         /* its index, or -1 */
void          TzToTzi(const TzZone *z, TzTzi *out);

/* The zone in effect (TimeZoneKeyName): its index; that of UTC when the
 * name is not one of the table's */
int  TzCurrent(void);

/* Make zone @i the system's: the TimeZoneInformation values, and
 * HKLM\SOFTWARE\NovaOS\Setup TimeZone.  Programs started afterwards and
 * the desktop clock show its time. */
void TzSet(int i);

/* The bias (minutes, UTC = local + bias) in effect at UTC time @utc,
 * from the TimeZoneInformation values; *dst says if that is daylight time */
INT32 TzBiasAt(const RtcTime *utc, bool *dst);

/* The local time now; local time for a UTC time */
void TzLocalNow(RtcTime *out);
void TzToLocal(const RtcTime *utc, RtcTime *out);

/* The local time now in zone @i (the table's rule, whatever is set); its
 * bias then */
INT32 TzZoneLocalNow(int i, RtcTime *out, bool *dst);
