# msiscript.dll's build hooks (tools/build_userland.py calls them with
# itself as b).  The engine is mujs (third_party/mujs, ISC), compiled into
# the DLL; runtime.js, vbslib.js and vbscript.js become C strings in the
# generated msiscript_js.h.
import os, threading

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
MUJS = os.path.join(ROOT, 'third_party', 'mujs')
SCRIPTS = ['runtime', 'vbslib', 'vbscript']


def c_string(text):
    out = []
    for line in text.splitlines(True):
        esc = line.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n').replace('\r', '')
        out.append('"' + esc + '"')
    return '\n'.join(out) or '""'


def cflags(b):
    """flags for msiscript's own sources; writes msiscript_js.h"""
    gen = os.path.join(b.out, 'include', 'msiscript_js.h')
    text = '/* generated by userland/msiscript/build.py */\n'
    for name in SCRIPTS:
        text += f'static const char js_{name}[] =\n' + c_string(open(os.path.join(HERE, name + '.js')).read()) + ';\n'
    if not os.path.exists(gen) or open(gen).read() != text:
        tmp = f'{gen}.{os.getpid()}.{threading.get_ident()}.tmp'    # (the x64 and x86 passes can both write it)
        open(tmp, 'w').write(text)
        os.replace(tmp, gen)
    return ['-I', MUJS]


def objs(b, odir):
    """mujs for this architecture (one translation unit, one.c)"""
    flags = b.cflags() + ['-I', MUJS, '-I', os.path.join(HERE, 'include'), '-w']
    headers = [os.path.join(MUJS, h) for h in os.listdir(MUJS) if h.endswith('.h')]
    return b.compile_many([os.path.join(MUJS, 'one.c')], odir, 'mujs_', flags, headers)
