/*
 * msiscript.dll — the script engine behind Windows Installer's script
 * custom actions (JScript: types 5, 21, 37, 53; VBScript: 6, 22, 38, 54).
 *
 * msi.dll loads it when a package runs a script action and calls
 * NovaRunScript with the session handle, the script and the function to
 * call.  JScript runs on mujs (third_party/mujs, ISC licence; patched so
 * that Session.Property("X") = "1" compiles, as Microsoft's JScript
 * allows).  VBScript is translated to JavaScript by vbscript.js and runs on
 * the same engine.  The objects scripts use (Session, Installer, Database,
 * View, Record, Scripting.FileSystemObject, Scripting.Dictionary,
 * WScript.Shell) are runtime.js's, written on the __nova calls below; the
 * Windows Installer ones go through msi.dll's own API with the session
 * handle, in the installing process.
 */
#include <windows.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <wchar.h>
#include "mujs.h"
#include "msiscript_js.h"            /* runtime.js, vbslib.js, vbscript.js (generated by build.py) */

int _fltused = 0x9875;                /* floating point in use (the compiler references it) */

typedef unsigned long MSIHANDLE;
#define MSIIMP __declspec(dllimport) UINT WINAPI
MSIIMP MsiGetPropertyW(MSIHANDLE h, LPCWSTR name, LPWSTR buf, DWORD *pcch);
MSIIMP MsiSetPropertyW(MSIHANDLE h, LPCWSTR name, LPCWSTR v);
MSIIMP MsiGetTargetPathW(MSIHANDLE h, LPCWSTR f, LPWSTR buf, DWORD *pcch);
MSIIMP MsiSetTargetPathW(MSIHANDLE h, LPCWSTR f, LPCWSTR p);
MSIIMP MsiGetSourcePathW(MSIHANDLE h, LPCWSTR f, LPWSTR buf, DWORD *pcch);
__declspec(dllimport) BOOL WINAPI MsiGetMode(MSIHANDLE h, int mode);
MSIIMP MsiSetMode(MSIHANDLE h, int mode, BOOL state);
__declspec(dllimport) LANGID WINAPI MsiGetLanguage(MSIHANDLE h);
MSIIMP MsiGetFeatureStateW(MSIHANDLE h, LPCWSTR f, int *i, int *a);
MSIIMP MsiSetFeatureStateW(MSIHANDLE h, LPCWSTR f, int s);
MSIIMP MsiGetComponentStateW(MSIHANDLE h, LPCWSTR f, int *i, int *a);
MSIIMP MsiSetComponentStateW(MSIHANDLE h, LPCWSTR f, int s);
__declspec(dllimport) int WINAPI MsiEvaluateConditionW(MSIHANDLE h, LPCWSTR c);
MSIIMP MsiFormatRecordW(MSIHANDLE inst, MSIHANDLE rec, LPWSTR buf, DWORD *pcch);
__declspec(dllimport) int WINAPI MsiProcessMessage(MSIHANDLE h, int type, MSIHANDLE rec);
MSIIMP MsiDoActionW(MSIHANDLE h, LPCWSTR a);
MSIIMP MsiSequenceW(MSIHANDLE h, LPCWSTR t, int mode);
MSIIMP MsiSetInstallLevel(MSIHANDLE h, int level);
__declspec(dllimport) MSIHANDLE WINAPI MsiGetActiveDatabase(MSIHANDLE inst);
MSIIMP MsiOpenDatabaseW(LPCWSTR path, LPCWSTR persist, MSIHANDLE *out);
MSIIMP MsiDatabaseCommit(MSIHANDLE db);
__declspec(dllimport) int WINAPI MsiGetDatabaseState(MSIHANDLE db);
MSIIMP MsiDatabaseGetPrimaryKeysW(MSIHANDLE db, LPCWSTR table, MSIHANDLE *out);
MSIIMP MsiDatabaseOpenViewW(MSIHANDLE db, LPCWSTR sql, MSIHANDLE *out);
MSIIMP MsiViewExecute(MSIHANDLE v, MSIHANDLE rec);
MSIIMP MsiViewFetch(MSIHANDLE v, MSIHANDLE *out);
MSIIMP MsiViewModify(MSIHANDLE v, int mode, MSIHANDLE rec);
MSIIMP MsiViewClose(MSIHANDLE v);
MSIIMP MsiViewGetColumnInfo(MSIHANDLE v, int type, MSIHANDLE *out);
__declspec(dllimport) MSIHANDLE WINAPI MsiCreateRecord(UINT n);
MSIIMP MsiRecordGetFieldCount(MSIHANDLE h);
MSIIMP MsiRecordGetStringW(MSIHANDLE h, UINT i, LPWSTR buf, DWORD *pcch);
MSIIMP MsiRecordSetStringW(MSIHANDLE h, UINT i, LPCWSTR s);
__declspec(dllimport) int WINAPI MsiRecordGetInteger(MSIHANDLE h, UINT i);
MSIIMP MsiRecordSetInteger(MSIHANDLE h, UINT i, int v);
__declspec(dllimport) BOOL WINAPI MsiRecordIsNull(MSIHANDLE h, UINT i);
MSIIMP MsiRecordDataSize(MSIHANDLE h, UINT i);
MSIIMP MsiRecordClearData(MSIHANDLE h);
__declspec(dllimport) int WINAPI MsiQueryProductStateW(LPCWSTR product);
__declspec(dllimport) DWORD WINAPI GetFileVersionInfoSizeW(LPCWSTR name, LPDWORD handle);
__declspec(dllimport) BOOL WINAPI GetFileVersionInfoW(LPCWSTR name, DWORD handle, DWORD len, LPVOID data);
__declspec(dllimport) BOOL WINAPI VerQueryValueW(LPCVOID block, LPCWSTR sub, LPVOID *buf, PUINT len);
typedef struct {
    DWORD dwSignature, dwStrucVersion, dwFileVersionMS, dwFileVersionLS, dwProductVersionMS, dwProductVersionLS;
    DWORD dwFileFlagsMask, dwFileFlags, dwFileOS, dwFileType, dwFileSubtype, dwFileDateMS, dwFileDateLS;
} FileVersion;

#ifndef ERROR_MORE_DATA
#define ERROR_MORE_DATA 234
#endif
#define ERROR_NO_MORE_ITEMS_ 259
#define ERROR_INSTALL_USEREXIT 1602
#define ERROR_INSTALL_FAILURE_ 1603

typedef void (*NovaScriptLog)(void *ctx, const char *text);
static NovaScriptLog g_log;
static void *g_log_ctx;

static void say(const char *fmt, ...)
{
    char buf[2048];
    va_list ap;
    va_start(ap, fmt);
    vsnprintf(buf, sizeof(buf), fmt, ap);
    va_end(ap);
    if (g_log) g_log(g_log_ctx, buf);
}

/* -----------------------------------------------------------------------
 * Strings: mujs speaks UTF-8, Windows UTF-16
 * ----------------------------------------------------------------------- */
static WCHAR *wide(const char *u8)
{
    int n = MultiByteToWideChar(CP_UTF8, 0, u8, -1, NULL, 0);
    WCHAR *w = malloc((size_t)(n > 0 ? n : 1) * sizeof(WCHAR));
    if (!w) return NULL;
    if (n <= 0) { w[0] = 0; return w; }
    MultiByteToWideChar(CP_UTF8, 0, u8, -1, w, n);
    return w;
}

static char *utf8(const WCHAR *w, int len)
{
    int n = WideCharToMultiByte(CP_UTF8, 0, w, len, NULL, 0, NULL, NULL);
    char *s = malloc((size_t)n + 1);
    if (!s) return NULL;
    WideCharToMultiByte(CP_UTF8, 0, w, len, s, n, NULL, NULL);
    s[n] = 0;
    return s;
}

static void push_w(js_State *J, const WCHAR *w)
{
    char *s = utf8(w, -1);
    js_pushstring(J, s ? s : "");
    free(s);
}

/* argument @i as a wide string (freed by the caller) */
static WCHAR *arg_w(js_State *J, int i) { return wide(js_isdefined(J, i) && !js_isnull(J, i) ? js_tostring(J, i) : ""); }
static WCHAR *arg_w_or_null(js_State *J, int i) { return js_isdefined(J, i) && !js_isnull(J, i) ? wide(js_tostring(J, i)) : NULL; }
static MSIHANDLE arg_h(js_State *J, int i) { return (MSIHANDLE)js_tointeger(J, i); }

/* an MSI call's failure as a script error with that number */
static void check(js_State *J, UINT r, const char *what)
{
    if (!r) return;
    js_newerror(J, what);
    js_pushnumber(J, (double)r);
    js_setproperty(J, -2, "number");
    js_throw(J);
}

/* text from an MSI call that fills a buffer: fn(h, name, buf, &n) */
typedef UINT (WINAPI *StrFn)(MSIHANDLE, LPCWSTR, LPWSTR, DWORD *);
static void push_msi_str(js_State *J, StrFn fn, MSIHANDLE h, const WCHAR *name, const char *what)
{
    WCHAR small[256];
    DWORD n = 256;
    UINT r = fn(h, name, small, &n);
    if (r == ERROR_MORE_DATA) {
        WCHAR *big = malloc((n + 1) * sizeof(WCHAR));
        n++;
        r = big ? fn(h, name, big, &n) : 8;
        if (!r) push_w(J, big);
        free(big);
        check(J, r, what);
        return;
    }
    check(J, r, what);
    push_w(J, small);
}

/* -----------------------------------------------------------------------
 * __nova: Windows Installer
 * ----------------------------------------------------------------------- */
static void n_prop_get(js_State *J)
{
    WCHAR *name = arg_w(J, 2);
    push_msi_str(J, MsiGetPropertyW, arg_h(J, 1), name, "Session.Property");
    free(name);
}

static void n_prop_set(js_State *J)
{
    WCHAR *name = arg_w(J, 2), *v = arg_w(J, 3);
    UINT r = MsiSetPropertyW(arg_h(J, 1), name, v);
    free(name); free(v);
    check(J, r, "Session.Property");
    js_pushundefined(J);
}

static void n_target_get(js_State *J)
{
    WCHAR *d = arg_w(J, 2);
    push_msi_str(J, MsiGetTargetPathW, arg_h(J, 1), d, "Session.TargetPath");
    free(d);
}

static void n_source_get(js_State *J)
{
    WCHAR *d = arg_w(J, 2);
    push_msi_str(J, MsiGetSourcePathW, arg_h(J, 1), d, "Session.SourcePath");
    free(d);
}

static void n_target_set(js_State *J)
{
    WCHAR *d = arg_w(J, 2), *p = arg_w(J, 3);
    UINT r = MsiSetTargetPathW(arg_h(J, 1), d, p);
    free(d); free(p);
    check(J, r, "Session.TargetPath");
    js_pushundefined(J);
}

static void n_mode_get(js_State *J) { js_pushboolean(J, MsiGetMode(arg_h(J, 1), js_tointeger(J, 2))); }
static void n_mode_set(js_State *J) { check(J, MsiSetMode(arg_h(J, 1), js_tointeger(J, 2), js_toboolean(J, 3)), "Session.Mode"); js_pushundefined(J); }
static void n_language(js_State *J) { js_pushnumber(J, MsiGetLanguage(arg_h(J, 1))); }

static void push_state(js_State *J, UINT (WINAPI *fn)(MSIHANDLE, LPCWSTR, int *, int *), const char *what)
{
    WCHAR *f = arg_w(J, 2);
    int installed = 0, action = 0;
    UINT r = fn(arg_h(J, 1), f, &installed, &action);
    free(f);
    check(J, r, what);
    js_newarray(J);
    js_pushnumber(J, installed);
    js_setindex(J, -2, 0);
    js_pushnumber(J, action);
    js_setindex(J, -2, 1);
}

static void n_feature_state(js_State *J) { push_state(J, MsiGetFeatureStateW, "Session.FeatureRequestState"); }
static void n_comp_state(js_State *J) { push_state(J, MsiGetComponentStateW, "Session.ComponentRequestState"); }

static void n_feature_set(js_State *J)
{
    WCHAR *f = arg_w(J, 2);
    UINT r = MsiSetFeatureStateW(arg_h(J, 1), f, js_tointeger(J, 3));
    free(f);
    check(J, r, "Session.FeatureRequestState");
    js_pushundefined(J);
}

static void n_comp_set(js_State *J)
{
    WCHAR *c = arg_w(J, 2);
    UINT r = MsiSetComponentStateW(arg_h(J, 1), c, js_tointeger(J, 3));
    free(c);
    check(J, r, "Session.ComponentRequestState");
    js_pushundefined(J);
}

static void n_eval_cond(js_State *J)
{
    WCHAR *c = arg_w(J, 2);
    js_pushnumber(J, MsiEvaluateConditionW(arg_h(J, 1), c));
    free(c);
}

static void n_format(js_State *J)
{
    MSIHANDLE inst = arg_h(J, 1), rec = arg_h(J, 2);
    DWORD n = 0;
    WCHAR empty[1];
    UINT r = MsiFormatRecordW(inst, rec, empty, &n);
    if (r && r != ERROR_MORE_DATA) check(J, r, "FormatRecord");
    WCHAR *buf = malloc((n + 1) * sizeof(WCHAR));
    n++;
    r = buf ? MsiFormatRecordW(inst, rec, buf, &n) : 8;
    if (!r) push_w(J, buf);
    free(buf);
    check(J, r, "FormatRecord");
}

static void n_message(js_State *J) { js_pushnumber(J, MsiProcessMessage(arg_h(J, 1), js_tointeger(J, 2), arg_h(J, 3))); }

static void n_do_action(js_State *J)
{
    WCHAR *a = arg_w(J, 2);
    js_pushnumber(J, MsiDoActionW(arg_h(J, 1), a));
    free(a);
}

static void n_sequence(js_State *J)
{
    WCHAR *t = arg_w(J, 2);
    js_pushnumber(J, MsiSequenceW(arg_h(J, 1), t, 0));
    free(t);
}

static void n_set_level(js_State *J) { check(J, MsiSetInstallLevel(arg_h(J, 1), js_tointeger(J, 2)), "Session.SetInstallLevel"); js_pushundefined(J); }

static void n_active_db(js_State *J)
{
    MSIHANDLE db = MsiGetActiveDatabase(arg_h(J, 1));
    if (!db) check(J, 6 /* ERROR_INVALID_HANDLE */, "Session.Database");
    js_pushnumber(J, db);
}

static void n_open_db(js_State *J)
{
    WCHAR *p = arg_w(J, 1);
    MSIHANDLE db = 0;
    UINT r = MsiOpenDatabaseW(p, (LPCWSTR)(ULONG_PTR)js_tointeger(J, 2), &db);
    free(p);
    check(J, r, "Installer.OpenDatabase");
    js_pushnumber(J, db);
}

static void n_db_commit(js_State *J) { check(J, MsiDatabaseCommit(arg_h(J, 1)), "Database.Commit"); js_pushundefined(J); }
static void n_db_state(js_State *J) { js_pushnumber(J, MsiGetDatabaseState(arg_h(J, 1))); }

static void n_primary_keys(js_State *J)
{
    WCHAR *t = arg_w(J, 2);
    MSIHANDLE rec = 0;
    UINT r = MsiDatabaseGetPrimaryKeysW(arg_h(J, 1), t, &rec);
    free(t);
    check(J, r, "Database.PrimaryKeys");
    js_pushnumber(J, rec);
}

static void n_open_view(js_State *J)
{
    WCHAR *sql = arg_w(J, 2);
    MSIHANDLE v = 0;
    UINT r = MsiDatabaseOpenViewW(arg_h(J, 1), sql, &v);
    free(sql);
    check(J, r, "Database.OpenView");
    js_pushnumber(J, v);
}

static void n_view_execute(js_State *J) { check(J, MsiViewExecute(arg_h(J, 1), arg_h(J, 2)), "View.Execute"); js_pushundefined(J); }

static void n_view_fetch(js_State *J)
{
    MSIHANDLE rec = 0;
    UINT r = MsiViewFetch(arg_h(J, 1), &rec);
    if (r == ERROR_NO_MORE_ITEMS_) rec = 0;
    else check(J, r, "View.Fetch");
    js_pushnumber(J, rec);
}

static void n_view_modify(js_State *J) { check(J, MsiViewModify(arg_h(J, 1), js_tointeger(J, 2), arg_h(J, 3)), "View.Modify"); js_pushundefined(J); }
static void n_view_close(js_State *J) { check(J, MsiViewClose(arg_h(J, 1)), "View.Close"); js_pushundefined(J); }

static void n_view_colinfo(js_State *J)
{
    MSIHANDLE rec = 0;
    check(J, MsiViewGetColumnInfo(arg_h(J, 1), js_tointeger(J, 2), &rec), "View.ColumnInfo");
    js_pushnumber(J, rec);
}

static void n_rec_create(js_State *J) { js_pushnumber(J, MsiCreateRecord((UINT)js_tointeger(J, 1))); }
static void n_rec_count(js_State *J) { js_pushnumber(J, MsiRecordGetFieldCount(arg_h(J, 1))); }

static UINT WINAPI rec_get_str(MSIHANDLE h, LPCWSTR field, LPWSTR buf, DWORD *pcch)
{
    return MsiRecordGetStringW(h, (UINT)(ULONG_PTR)field, buf, pcch);
}

static void n_rec_get(js_State *J) { push_msi_str(J, rec_get_str, arg_h(J, 1), (LPCWSTR)(ULONG_PTR)js_tointeger(J, 2), "Record.StringData"); }

static void n_rec_set(js_State *J)
{
    WCHAR *s = arg_w(J, 3);
    UINT r = MsiRecordSetStringW(arg_h(J, 1), (UINT)js_tointeger(J, 2), s);
    free(s);
    check(J, r, "Record.StringData");
    js_pushundefined(J);
}

static void n_rec_getint(js_State *J) { js_pushnumber(J, MsiRecordGetInteger(arg_h(J, 1), (UINT)js_tointeger(J, 2))); }
static void n_rec_setint(js_State *J) { check(J, MsiRecordSetInteger(arg_h(J, 1), (UINT)js_tointeger(J, 2), js_tointeger(J, 3)), "Record.IntegerData"); js_pushundefined(J); }
static void n_rec_isnull(js_State *J) { js_pushboolean(J, MsiRecordIsNull(arg_h(J, 1), (UINT)js_tointeger(J, 2))); }
static void n_rec_size(js_State *J) { js_pushnumber(J, MsiRecordDataSize(arg_h(J, 1), (UINT)js_tointeger(J, 2))); }
static void n_rec_clear(js_State *J) { check(J, MsiRecordClearData(arg_h(J, 1)), "Record.ClearData"); js_pushundefined(J); }

static void n_product_state(js_State *J)
{
    WCHAR *p = arg_w(J, 1);
    js_pushnumber(J, MsiQueryProductStateW(p));
    free(p);
}

/* -----------------------------------------------------------------------
 * __nova: files, the environment, the registry, programs
 * ----------------------------------------------------------------------- */

static bool valid_utf8(const unsigned char *p, size_t n)
{
    for (size_t i = 0; i < n;) {
        unsigned c = p[i], k = c < 0x80 ? 0 : (c & 0xE0) == 0xC0 ? 1 : (c & 0xF0) == 0xE0 ? 2 : (c & 0xF8) == 0xF0 ? 3 : 9;
        if (k == 9 || i + k >= n + (k ? 0 : 1)) return false;
        for (unsigned j = 1; j <= k; j++) if ((p[i + j] & 0xC0) != 0x80) return false;
        i += k + 1;
    }
    return true;
}

/* a script file or text file's bytes as UTF-8: UTF-16 with its byte-order
 * mark, UTF-8 (with or without one), else the ANSI code page */
static char *text_of(const unsigned char *p, size_t n)
{
    if (n >= 2 && p[0] == 0xFF && p[1] == 0xFE) return utf8((const WCHAR *)(p + 2), (int)((n - 2) / 2));
    if (n >= 3 && p[0] == 0xEF && p[1] == 0xBB && p[2] == 0xBF) { p += 3; n -= 3; }
    if (n == 0) return calloc(1, 1);
    if (valid_utf8(p, n)) {
        char *s = malloc(n + 1);
        if (s) { memcpy(s, p, n); s[n] = 0; }
        return s;
    }
    int wn = MultiByteToWideChar(CP_ACP, 0, (const char *)p, (int)n, NULL, 0);
    WCHAR *w = malloc((size_t)(wn + 1) * sizeof(WCHAR));
    if (!w) return NULL;
    MultiByteToWideChar(CP_ACP, 0, (const char *)p, (int)n, w, wn);
    char *s = utf8(w, wn);
    free(w);
    return s;
}

static void n_file_read(js_State *J)
{
    WCHAR *p = arg_w(J, 1);
    HANDLE h = CreateFileW(p, GENERIC_READ, FILE_SHARE_READ | FILE_SHARE_WRITE, NULL, OPEN_EXISTING, 0, NULL);
    free(p);
    if (h == INVALID_HANDLE_VALUE) { js_pushnull(J); return; }
    DWORD size = GetFileSize(h, NULL), got = 0;
    unsigned char *data = malloc((size_t)size + 1);
    BOOL ok = data && ReadFile(h, data, size, &got, NULL);
    CloseHandle(h);
    char *s = ok ? text_of(data, got) : NULL;
    free(data);
    if (s) js_pushstring(J, s);
    else js_pushnull(J);
    free(s);
}

static void n_file_write(js_State *J)
{
    WCHAR *p = arg_w(J, 1);
    const char *text = js_tostring(J, 2);
    BOOL append = js_toboolean(J, 3);
    HANDLE h = CreateFileW(p, append ? FILE_APPEND_DATA : GENERIC_WRITE, FILE_SHARE_READ, NULL,
                           append ? OPEN_ALWAYS : CREATE_ALWAYS, FILE_ATTRIBUTE_NORMAL, NULL);
    free(p);
    if (h == INVALID_HANDLE_VALUE) { js_pushboolean(J, 0); return; }
    DWORD len = (DWORD)strlen(text), wr = 0;
    if (append) SetFilePointer(h, 0, NULL, FILE_END);
    BOOL ok = !len || (WriteFile(h, text, len, &wr, NULL) && wr == len);
    CloseHandle(h);
    js_pushboolean(J, ok);
}

static void n_attr(js_State *J)
{
    WCHAR *p = arg_w(J, 1);
    DWORD a = GetFileAttributesW(p);
    free(p);
    js_pushnumber(J, a == INVALID_FILE_ATTRIBUTES ? -1 : (double)a);
}

static void n_size(js_State *J)
{
    WCHAR *p = arg_w(J, 1);
    WIN32_FILE_ATTRIBUTE_DATA d;
    BOOL ok = GetFileAttributesExW(p, GetFileExInfoStandard, &d);
    free(p);
    js_pushnumber(J, ok ? (double)d.nFileSizeLow + (double)d.nFileSizeHigh * 4294967296.0 : 0);
}

static void n_mkdir(js_State *J)
{
    WCHAR *p = arg_w(J, 1);
    js_pushboolean(J, CreateDirectoryW(p, NULL));
    free(p);
}

static void n_rmfile(js_State *J)
{
    WCHAR *p = arg_w(J, 1);
    SetFileAttributesW(p, FILE_ATTRIBUTE_NORMAL);
    js_pushboolean(J, DeleteFileW(p));
    free(p);
}

static BOOL remove_tree(const WCHAR *dir)
{
    WCHAR pat[MAX_PATH + 4];
    _snwprintf(pat, MAX_PATH + 4, L"%s\\*", dir);
    WIN32_FIND_DATAW fd;
    HANDLE f = FindFirstFileW(pat, &fd);
    if (f != INVALID_HANDLE_VALUE) {
        do {
            if (!wcscmp(fd.cFileName, L".") || !wcscmp(fd.cFileName, L"..")) continue;
            WCHAR sub[MAX_PATH * 2];
            _snwprintf(sub, MAX_PATH * 2, L"%s\\%s", dir, fd.cFileName);
            if (fd.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY) remove_tree(sub);
            else { SetFileAttributesW(sub, FILE_ATTRIBUTE_NORMAL); DeleteFileW(sub); }
        } while (FindNextFileW(f, &fd));
        FindClose(f);
    }
    return RemoveDirectoryW(dir);
}

static void n_rmdir(js_State *J)
{
    WCHAR *p = arg_w(J, 1);
    js_pushboolean(J, js_toboolean(J, 2) ? remove_tree(p) : RemoveDirectoryW(p));
    free(p);
}

static void n_copy(js_State *J)
{
    WCHAR *a = arg_w(J, 1), *b = arg_w(J, 2);
    js_pushboolean(J, CopyFileW(a, b, !js_toboolean(J, 3)));
    free(a); free(b);
}

static void n_move(js_State *J)
{
    WCHAR *a = arg_w(J, 1), *b = arg_w(J, 2);
    js_pushboolean(J, MoveFileExW(a, b, MOVEFILE_COPY_ALLOWED));
    free(a); free(b);
}

static void n_list(js_State *J)
{
    WCHAR *dir = arg_w(J, 1), pat[MAX_PATH + 4];
    BOOL dirs = js_toboolean(J, 2);
    _snwprintf(pat, MAX_PATH + 4, L"%s\\*", dir);
    free(dir);
    js_newarray(J);
    WIN32_FIND_DATAW fd;
    HANDLE f = FindFirstFileW(pat, &fd);
    if (f == INVALID_HANDLE_VALUE) return;
    int i = 0;
    do {
        if (!wcscmp(fd.cFileName, L".") || !wcscmp(fd.cFileName, L"..")) continue;
        if (!(fd.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY) == !dirs) continue;
        push_w(J, fd.cFileName);
        js_setindex(J, -2, i++);
    } while (FindNextFileW(f, &fd));
    FindClose(f);
}

static void n_special(js_State *J)
{
    WCHAR buf[MAX_PATH];
    int which = js_tointeger(J, 1);
    if (which == 0) GetWindowsDirectoryW(buf, MAX_PATH);
    else if (which == 1) GetSystemDirectoryW(buf, MAX_PATH);
    else {
        GetTempPathW(MAX_PATH, buf);
        size_t n = wcslen(buf);
        if (n > 3 && buf[n - 1] == L'\\') buf[n - 1] = 0;
    }
    push_w(J, buf);
}

static void n_full(js_State *J)
{
    WCHAR *p = arg_w(J, 1), buf[MAX_PATH * 2];
    DWORD n = GetFullPathNameW(p, MAX_PATH * 2, buf, NULL);
    if (!n || n >= MAX_PATH * 2) push_w(J, p);
    else push_w(J, buf);
    free(p);
}

static void n_version(js_State *J)
{
    WCHAR *p = arg_w(J, 1);
    DWORD dummy = 0, size = GetFileVersionInfoSizeW(p, &dummy);
    void *data = size ? malloc(size) : NULL;
    FileVersion *fi = NULL;
    UINT len = 0;
    if (data && GetFileVersionInfoW(p, 0, size, data) && VerQueryValueW(data, L"\\", (void **)&fi, &len) && fi) {
        char v[64];
        snprintf(v, sizeof(v), "%u.%u.%u.%u", (unsigned)HIWORD(fi->dwFileVersionMS), (unsigned)LOWORD(fi->dwFileVersionMS),
                 (unsigned)HIWORD(fi->dwFileVersionLS), (unsigned)LOWORD(fi->dwFileVersionLS));
        js_pushstring(J, v);
    } else js_pushstring(J, "");
    free(data);
    free(p);
}

static void n_env_get(js_State *J)
{
    WCHAR *name = arg_w(J, 1), buf[1024];
    DWORD n = GetEnvironmentVariableW(name, buf, 1024);
    free(name);
    if (!n || n >= 1024) buf[0] = 0;
    push_w(J, buf);
}

static void n_env_set(js_State *J)
{
    WCHAR *name = arg_w(J, 1), *v = arg_w_or_null(J, 2);
    SetEnvironmentVariableW(name, v);
    free(name); free(v);
    js_pushundefined(J);
}

static void n_env_expand(js_State *J)
{
    WCHAR *s = arg_w(J, 1);
    DWORD n = ExpandEnvironmentStringsW(s, NULL, 0);
    WCHAR *buf = malloc((n + 1) * sizeof(WCHAR));
    if (buf && ExpandEnvironmentStringsW(s, buf, n + 1)) push_w(J, buf);
    else push_w(J, s);
    free(buf);
    free(s);
}

static HKEY root_key(int r)
{
    switch (r) {
    case 0: return HKEY_CLASSES_ROOT;
    case 1: return HKEY_CURRENT_USER;
    case 3: return HKEY_USERS;
    case 5: return HKEY_CURRENT_CONFIG;
    default: return HKEY_LOCAL_MACHINE;
    }
}

static void n_reg_key(js_State *J)
{
    WCHAR *key = arg_w(J, 2);
    HKEY k;
    LONG r = RegOpenKeyExW(root_key(js_tointeger(J, 1)), key, 0, KEY_READ, &k);
    free(key);
    if (!r) RegCloseKey(k);
    js_pushboolean(J, !r);
}

static void n_reg_read(js_State *J)
{
    WCHAR *key = arg_w(J, 2), *name = arg_w_or_null(J, 3);
    HKEY k;
    js_pushundefined(J);
    if (RegOpenKeyExW(root_key(js_tointeger(J, 1)), key, 0, KEY_READ, &k)) { free(key); free(name); return; }
    DWORD type = 0, size = 0;
    if (!RegQueryValueExW(k, name, NULL, &type, NULL, &size)) {
        BYTE *data = calloc(1, size + 4);
        if (data && !RegQueryValueExW(k, name, NULL, &type, data, &size)) {
            js_pop(J, 1);
            if (type == REG_DWORD) js_pushnumber(J, *(DWORD *)data);
            else if (type == REG_SZ || type == REG_EXPAND_SZ) push_w(J, (WCHAR *)data);
            else if (type == REG_MULTI_SZ) {
                js_newarray(J);
                int i = 0;
                for (WCHAR *s = (WCHAR *)data; *s; s += wcslen(s) + 1) { push_w(J, s); js_setindex(J, -2, i++); }
            } else {
                js_newarray(J);
                for (DWORD i = 0; i < size; i++) { js_pushnumber(J, data[i]); js_setindex(J, -2, (int)i); }
            }
        }
        free(data);
    }
    RegCloseKey(k);
    free(key);
    free(name);
}

static void n_reg_write(js_State *J)
{
    WCHAR *key = arg_w(J, 2), *name = arg_w_or_null(J, 3);
    const char *type = js_tostring(J, 5);
    HKEY k;
    LONG r = RegCreateKeyExW(root_key(js_tointeger(J, 1)), key, 0, NULL, 0, KEY_WRITE, NULL, &k, NULL);
    if (!r) {
        if (!strcmp(type, "REG_DWORD")) {
            DWORD v = (DWORD)js_tointeger(J, 4);
            r = RegSetValueExW(k, name, 0, REG_DWORD, (BYTE *)&v, 4);
        } else {
            WCHAR *v = arg_w(J, 4);
            r = RegSetValueExW(k, name, 0, !strcmp(type, "REG_EXPAND_SZ") ? REG_EXPAND_SZ : REG_SZ, (BYTE *)v,
                               (DWORD)((wcslen(v) + 1) * sizeof(WCHAR)));
            free(v);
        }
        RegCloseKey(k);
    }
    free(key);
    free(name);
    js_pushboolean(J, !r);
}

static void n_reg_delete(js_State *J)
{
    WCHAR *key = arg_w(J, 2), *name = arg_w_or_null(J, 3);
    HKEY root = root_key(js_tointeger(J, 1)), k;
    LONG r;
    if (!name) r = RegDeleteKeyW(root, key);
    else if (!(r = RegOpenKeyExW(root, key, 0, KEY_WRITE, &k))) { r = RegDeleteValueW(k, name); RegCloseKey(k); }
    free(key);
    free(name);
    js_pushboolean(J, !r);
}

static void n_run(js_State *J)
{
    WCHAR *cmd = arg_w(J, 1);
    STARTUPINFOW si;
    PROCESS_INFORMATION pi;
    memset(&si, 0, sizeof(si));
    si.cb = sizeof(si);
    say("Running %s", js_tostring(J, 1));
    BOOL ok = CreateProcessW(NULL, cmd, NULL, NULL, FALSE, 0, NULL, NULL, &si, &pi);
    free(cmd);
    if (!ok) check(J, GetLastError(), "WScript.Shell.Run");
    DWORD code = 0;
    if (js_toboolean(J, 2)) {
        WaitForSingleObject(pi.hProcess, INFINITE);
        GetExitCodeProcess(pi.hProcess, &code);
    }
    CloseHandle(pi.hThread);
    CloseHandle(pi.hProcess);
    js_pushnumber(J, code);
}

static void n_log(js_State *J) { say("%s", js_tostring(J, 1)); js_pushundefined(J); }
static void n_sleep(js_State *J) { Sleep((DWORD)js_tointeger(J, 1)); js_pushundefined(J); }

static const struct { const char *name; js_CFunction fn; int n; } natives[] = {
    { "prop_get", n_prop_get, 2 }, { "prop_set", n_prop_set, 3 }, { "target_get", n_target_get, 2 },
    { "target_set", n_target_set, 3 }, { "source_get", n_source_get, 2 }, { "mode_get", n_mode_get, 2 },
    { "mode_set", n_mode_set, 3 }, { "language", n_language, 1 }, { "feature_state", n_feature_state, 2 },
    { "feature_set", n_feature_set, 3 }, { "comp_state", n_comp_state, 2 }, { "comp_set", n_comp_set, 3 },
    { "eval_cond", n_eval_cond, 2 }, { "format", n_format, 2 }, { "message", n_message, 3 },
    { "do_action", n_do_action, 2 }, { "sequence", n_sequence, 2 }, { "set_level", n_set_level, 2 },
    { "active_db", n_active_db, 1 }, { "open_db", n_open_db, 2 }, { "db_commit", n_db_commit, 1 },
    { "db_state", n_db_state, 1 }, { "primary_keys", n_primary_keys, 2 }, { "open_view", n_open_view, 2 },
    { "view_execute", n_view_execute, 2 }, { "view_fetch", n_view_fetch, 1 }, { "view_modify", n_view_modify, 3 },
    { "view_close", n_view_close, 1 }, { "view_colinfo", n_view_colinfo, 2 }, { "rec_create", n_rec_create, 1 },
    { "rec_count", n_rec_count, 1 }, { "rec_get", n_rec_get, 2 }, { "rec_set", n_rec_set, 3 },
    { "rec_getint", n_rec_getint, 2 }, { "rec_setint", n_rec_setint, 3 }, { "rec_isnull", n_rec_isnull, 2 },
    { "rec_size", n_rec_size, 2 }, { "rec_clear", n_rec_clear, 1 }, { "product_state", n_product_state, 1 },
    { "file_read", n_file_read, 1 }, { "file_write", n_file_write, 3 }, { "attr", n_attr, 1 }, { "size", n_size, 1 },
    { "mkdir", n_mkdir, 1 }, { "rmfile", n_rmfile, 1 }, { "rmdir", n_rmdir, 2 }, { "copy", n_copy, 3 },
    { "move", n_move, 2 }, { "list", n_list, 2 }, { "special", n_special, 1 }, { "full", n_full, 1 },
    { "version", n_version, 1 }, { "env_get", n_env_get, 1 }, { "env_set", n_env_set, 2 },
    { "env_expand", n_env_expand, 1 }, { "reg_key", n_reg_key, 2 }, { "reg_read", n_reg_read, 3 },
    { "reg_write", n_reg_write, 5 }, { "reg_delete", n_reg_delete, 3 }, { "run", n_run, 2 }, { "log", n_log, 1 },
    { "sleep", n_sleep, 1 },
};

/* -----------------------------------------------------------------------
 * Running a script
 * ----------------------------------------------------------------------- */

/* the error on top of the stack, logged: its text and where it happened */
static void report(js_State *J, const char *what)
{
    char line[64] = "";
    if (js_isobject(J, -1)) {
        js_getproperty(J, -1, "line");
        if (js_isnumber(J, -1)) snprintf(line, sizeof(line), " (line %d)", js_tointeger(J, -1));
        js_pop(J, 1);
        js_getproperty(J, -1, "number");
        int number = js_isnumber(J, -1) ? js_tointeger(J, -1) : 0;
        js_pop(J, 1);
        /* the stack's frames in the script (named "[script]") give the line */
        js_getproperty(J, -1, "stack");
        const char *stack = js_isstring(J, -1) ? js_tostring(J, -1) : "";
        const char *at = strstr(stack, "[script]:");
        if (at && !line[0]) snprintf(line, sizeof(line), " (line %d)", atoi(at + 9));
        js_pop(J, 1);
        js_getproperty(J, -1, "message");
        if (number) say("%s: %s (error %d)%s", what, js_tostring(J, -1), number, line);
        else say("%s: %s%s", what, js_tostring(J, -1), line);
        js_pop(J, 1);
    } else say("%s: %s", what, js_tostring(J, -1));
}

static bool run_builtin(js_State *J, const char *name, const char *src)
{
    if (js_ploadstring(J, name, src)) { report(J, name); return false; }
    js_pushundefined(J);
    if (js_pcall(J, 0)) { report(J, name); return false; }
    js_pop(J, 1);
    return true;
}

static void engine_report(js_State *J, const char *message) { (void)J; say("script engine: %s", message); }

/* Runs @source (JScript, or VBScript if @vbscript) for the session
 * @session, then calls its function @entry if one is named.  The result
 * is what the custom action returns to the installer: 0, 1602 (user exit)
 * or 1603 (failure; the reason is logged through @log). */
__declspec(dllexport) UINT WINAPI NovaRunScript(MSIHANDLE session, int vbscript, const char *source, unsigned len,
                                                const char *entry, NovaScriptLog log, void *ctx)
{
    g_log = log;
    g_log_ctx = ctx;
    const char *lang = vbscript ? "VBScript" : "JScript";
    char *text = text_of((const unsigned char *)source, len);
    if (!text) return ERROR_INSTALL_FAILURE_;
    js_State *J = js_newstate(NULL, NULL, 0);
    if (!J) { free(text); return ERROR_INSTALL_FAILURE_; }
    js_setreport(J, engine_report);
    UINT result = ERROR_INSTALL_FAILURE_;

    js_newobject(J);
    for (size_t i = 0; i < sizeof(natives) / sizeof(natives[0]); i++) {
        js_newcfunction(J, natives[i].fn, natives[i].name, natives[i].n);
        js_setproperty(J, -2, natives[i].name);
    }
    js_setglobal(J, "__nova");
    if (!run_builtin(J, "runtime.js", js_runtime) || !run_builtin(J, "vbslib.js", js_vbslib) ||
        (vbscript && !run_builtin(J, "vbscript.js", js_vbscript)))
        goto out;

    /* Session, for both languages ($session in translated VBScript) */
    js_getglobal(J, "__Session");
    js_pushnumber(J, session);
    if (js_pconstruct(J, 1)) { report(J, "Session"); goto out; }
    js_dup(J);
    js_setglobal(J, "Session");
    js_setglobal(J, "$session");

    const char *code = text;
    if (vbscript) {
        js_getglobal(J, "__vbs_translate");
        js_pushundefined(J);
        js_pushstring(J, text);
        if (js_pcall(J, 1)) { report(J, "VBScript"); goto out; }
        code = js_tostring(J, -1);
    }
    if (js_ploadstring(J, "[script]", code)) { report(J, lang); goto out; }
    js_pushundefined(J);
    if (js_pcall(J, 0)) { report(J, lang); goto out; }
    js_pop(J, 1);

    result = 0;
    if (entry && *entry) {
        char name[256];
        snprintf(name, sizeof(name), vbscript ? "$%s" : "%s", entry);
        if (vbscript) for (char *p = name; *p; p++) if (*p >= 'A' && *p <= 'Z') *p += 32;
        js_getglobal(J, name);
        if (!js_iscallable(J, -1)) {
            say("%s: the script has no function %s", lang, entry);
            result = ERROR_INSTALL_FAILURE_;
            goto out;
        }
        js_pushundefined(J);
        if (js_pcall(J, 0)) { report(J, lang); result = ERROR_INSTALL_FAILURE_; goto out; }
        if (js_isnumber(J, -1)) {
            /* msiDoActionStatus: 2 user exit, 3 failure, 4 suspend */
            int r = js_tointeger(J, -1);
            if (r == 2) result = ERROR_INSTALL_USEREXIT;
            else if (r == 3 || r == 4) { say("%s: %s returned %d (failure)", lang, entry, r); result = ERROR_INSTALL_FAILURE_; }
        }
    }
out:
    js_freestate(J);
    free(text);
    return result;
}
