/*
 * kbdlayout.h — keyboard layouts
 *
 * The keys a PC keyboard sends are the same everywhere; what they type
 * depends on the layout the user chose (first-boot setup, Settings): US,
 * UK, German, French...  The tables are userland/include/kbdlayouts.h,
 * generated by tools/gen_keyboards.py from xkeyboard-config, and user32
 * reads the same ones (ToUnicode, MapVirtualKey, VkKeyScan,
 * GetKeyboardLayout).  The choice is kept where Windows keeps it,
 * HKCU\Keyboard Layout\Preload "1" (the layout id, "00000407"), and the
 * one in effect is published to programs in KUSER_SHARED_DATA
 * (UM_KUSD_KBD_HKL in um.h).
 */
#pragma once

#include "../include/types.h"

int         KbdCount(void);
const char *KbdName(int i);            /* "German" */
const char *KbdKlid(int i);            /* "00000407" */
UINT32      KbdHkl(int i);             /* 0x04070407 */
int         KbdFind(const char *klid); /* its index, or -1 */

/* The layout in effect (its index); follows HKCU\Keyboard Layout\Preload
 * when a program changes it */
int  KbdCurrent(void);

/* Make layout @i the user's: Preload "1", the desktop and Terminal type
 * with it from the next key on, programs from their next key too */
void KbdSet(int i);

/* Read the user's choice from the registry (at boot, once it is loaded) */
void KbdLoad(void);

/* The layout in effect has AltGr characters (right Alt, or Ctrl+Alt) */
bool KbdHasAltGr(void);

/* The Windows virtual-key code of a typing key (non-extended set-1 scan
 * code) in the layout in effect; 0 for keys the layout does not change */
UINT8 KbdVk(UINT8 sc);

/* What typing key @sc types at @level (0 plain, 1 Shift, 2 AltGr, 3
 * Shift+AltGr) with Caps Lock @caps: false when @sc is not a typing key.
 * *ch is 0 when the key types nothing at that level; *dead says it is a
 * dead key (an accent for the next letter) */
bool KbdKeyChar(UINT8 sc, int level, bool caps, UINT16 *ch, bool *dead);

/* A dead key's accent @dead on @base: the accented letter, or 0 */
UINT16 KbdComposeChar(UINT16 dead, UINT16 base);

/* The other way: an accented letter's letter and accent (for drawing it
 * with a font that has only ASCII) */
bool KbdDecompose(UINT16 c, UINT16 *base, UINT16 *accent);
