/* commctrl.h — the common controls (comctl32) */
#pragma once
#include <windows.h>

#ifdef NOVA_BUILD_COMCTL32
#define CCAPI_ __declspec(dllexport)
#else
#define CCAPI_ __declspec(dllimport)
#endif
#define WINCOMMCTRLAPI CCAPI_

typedef struct _IMAGELIST *HIMAGELIST;
typedef struct _TREEITEM *HTREEITEM;
typedef struct _PSP *HPROPSHEETPAGE;

typedef struct tagINITCOMMONCONTROLSEX { DWORD dwSize, dwICC; } INITCOMMONCONTROLSEX, *LPINITCOMMONCONTROLSEX;
#define ICC_LISTVIEW_CLASSES 0x00000001
#define ICC_TREEVIEW_CLASSES 0x00000002
#define ICC_BAR_CLASSES 0x00000004
#define ICC_TAB_CLASSES 0x00000008
#define ICC_UPDOWN_CLASS 0x00000010
#define ICC_PROGRESS_CLASS 0x00000020
#define ICC_WIN95_CLASSES 0x000000FF
#define ICC_STANDARD_CLASSES 0x00004000

/* class names */
#define WC_LISTVIEWW L"SysListView32"
#define WC_HEADERW L"SysHeader32"
#define WC_TREEVIEWW L"SysTreeView32"
#define WC_TABCONTROLW L"SysTabControl32"
#define WC_COMBOBOXEXW L"ComboBoxEx32"
#define TOOLBARCLASSNAMEW L"ToolbarWindow32"
#define REBARCLASSNAMEW L"ReBarWindow32"
#define STATUSCLASSNAMEW L"msctls_statusbar32"
#define PROGRESS_CLASSW L"msctls_progress32"
#define TRACKBAR_CLASSW L"msctls_trackbar32"
#define UPDOWN_CLASSW L"msctls_updown32"
#define TOOLTIPS_CLASSW L"tooltips_class32"
#define WC_LINK L"SysLink"
#define WC_LISTVIEW WC_LISTVIEWW
#define WC_HEADER WC_HEADERW
#define WC_TABCONTROL WC_TABCONTROLW
#define TOOLBARCLASSNAME TOOLBARCLASSNAMEW
#define STATUSCLASSNAME STATUSCLASSNAMEW
#define PROGRESS_CLASS PROGRESS_CLASSW

/* common notifications */
#define NM_FIRST 0u
#define NM_OUTOFMEMORY (NM_FIRST - 1)
#define NM_CLICK (NM_FIRST - 2)
#define NM_DBLCLK (NM_FIRST - 3)
#define NM_RETURN (NM_FIRST - 4)
#define NM_RCLICK (NM_FIRST - 5)
#define NM_RDBLCLK (NM_FIRST - 6)
#define NM_SETFOCUS (NM_FIRST - 7)
#define NM_KILLFOCUS (NM_FIRST - 8)
#define NM_CUSTOMDRAW (NM_FIRST - 12)
#define NM_HOVER (NM_FIRST - 13)
#define NM_RELEASEDCAPTURE (NM_FIRST - 16)
#define NM_KEYDOWN (NM_FIRST - 15)
#define NM_CHAR (NM_FIRST - 18)
#define NM_TOOLTIPSCREATED (NM_FIRST - 19)
#define CCM_FIRST 0x2000
#define CCM_SETBKCOLOR (CCM_FIRST + 1)
#define CCM_SETCOLORSCHEME (CCM_FIRST + 2)
#define CCM_GETCOLORSCHEME (CCM_FIRST + 3)
#define CCM_GETDROPTARGET (CCM_FIRST + 4)
#define CCM_SETUNICODEFORMAT (CCM_FIRST + 5)
#define CCM_GETUNICODEFORMAT (CCM_FIRST + 6)
#define CCM_SETVERSION (CCM_FIRST + 7)
#define CCM_GETVERSION (CCM_FIRST + 8)
#define CCM_SETWINDOWTHEME (CCM_FIRST + 0xB)
#define CCS_TOP 0x00000001L
#define CCS_NOMOVEY 0x00000002L
#define CCS_BOTTOM 0x00000003L
#define CCS_NORESIZE 0x00000004L
#define CCS_NOPARENTALIGN 0x00000008L
#define CCS_ADJUSTABLE 0x00000020L
#define CCS_NODIVIDER 0x00000040L
#define CCS_VERT 0x00000080L
#define CLR_NONE 0xFFFFFFFFL
#define CLR_DEFAULT 0xFF000000L
#define CLR_INVALID 0xFFFFFFFF
#define I_IMAGECALLBACK (-1)
#define I_IMAGENONE (-2)
#define I_CHILDRENCALLBACK (-1)
#define LPSTR_TEXTCALLBACKW ((LPWSTR)-1L)

typedef struct tagNMMOUSE { NMHDR hdr; DWORD_PTR dwItemSpec, dwItemData; POINT pt; LPARAM dwHitInfo; } NMMOUSE, *LPNMMOUSE;
typedef NMMOUSE NMCLICK;
typedef struct tagNMKEY { NMHDR hdr; UINT nVKey, uFlags; } NMKEY, *LPNMKEY;
typedef struct tagNMCUSTOMDRAWINFO { NMHDR hdr; DWORD dwDrawStage; HDC hdc; RECT rc; DWORD_PTR dwItemSpec; UINT uItemState; LPARAM lItemlParam; } NMCUSTOMDRAW, *LPNMCUSTOMDRAW;
#define CDDS_PREPAINT 0x00000001
#define CDDS_POSTPAINT 0x00000002
#define CDDS_ITEM 0x00010000
#define CDDS_ITEMPREPAINT (CDDS_ITEM | CDDS_PREPAINT)
#define CDDS_SUBITEM 0x00020000
#define CDRF_DODEFAULT 0x00000000
#define CDRF_NEWFONT 0x00000002
#define CDRF_SKIPDEFAULT 0x00000004
#define CDRF_NOTIFYITEMDRAW 0x00000020
#define CDRF_NOTIFYSUBITEMDRAW 0x00000020
#define CDRF_NOTIFYPOSTPAINT 0x00000010

/* ---- image lists ---- */
#define ILC_MASK 0x00000001
#define ILC_COLOR 0x00000000
#define ILC_COLORDDB 0x000000FE
#define ILC_COLOR4 0x00000004
#define ILC_COLOR8 0x00000008
#define ILC_COLOR16 0x00000010
#define ILC_COLOR24 0x00000018
#define ILC_COLOR32 0x00000020
#define ILC_MIRROR 0x00002000
#define ILD_NORMAL 0x00000000
#define ILD_TRANSPARENT 0x00000001
#define ILD_MASK 0x00000010
#define ILD_IMAGE 0x00000020
#define ILD_BLEND25 0x00000002
#define ILD_BLEND50 0x00000004
#define ILD_SELECTED ILD_BLEND50
#define ILD_FOCUS ILD_BLEND25
#define ILD_OVERLAYMASK 0x00000F00
#define INDEXTOOVERLAYMASK(i) ((i) << 8)
typedef struct _IMAGEINFO { HBITMAP hbmImage, hbmMask; int Unused1, Unused2; RECT rcImage; } IMAGEINFO, *LPIMAGEINFO;
typedef struct _IMAGELISTDRAWPARAMS { DWORD cbSize; HIMAGELIST himl; int i; HDC hdcDst; int x, y, cx, cy, xBitmap, yBitmap; COLORREF rgbBk, rgbFg; UINT fStyle; DWORD dwRop, fState, Frame; COLORREF crEffect; } IMAGELISTDRAWPARAMS;

/* ---- progress bar ---- */
#define PBS_SMOOTH 0x01
#define PBS_VERTICAL 0x04
#define PBS_MARQUEE 0x08
#define PBM_SETRANGE (WM_USER + 1)
#define PBM_SETPOS (WM_USER + 2)
#define PBM_DELTAPOS (WM_USER + 3)
#define PBM_SETSTEP (WM_USER + 4)
#define PBM_STEPIT (WM_USER + 5)
#define PBM_SETRANGE32 (WM_USER + 6)
#define PBM_GETRANGE (WM_USER + 7)
#define PBM_GETPOS (WM_USER + 8)
#define PBM_SETBARCOLOR (WM_USER + 9)
#define PBM_SETMARQUEE (WM_USER + 10)
#define PBM_GETSTEP (WM_USER + 13)
#define PBM_GETBKCOLOR (WM_USER + 14)
#define PBM_GETBARCOLOR (WM_USER + 15)
#define PBM_SETSTATE (WM_USER + 16)
#define PBM_GETSTATE (WM_USER + 17)
#define PBM_SETBKCOLOR CCM_SETBKCOLOR
#define PBST_NORMAL 1
#define PBST_ERROR 2
#define PBST_PAUSED 3
typedef struct { int iLow, iHigh; } PBRANGE, *PPBRANGE;

/* ---- status bar ---- */
#define SBARS_SIZEGRIP 0x0100
#define SBARS_TOOLTIPS 0x0800
#define SB_SETTEXTW (WM_USER + 11)
#define SB_SETTEXTA (WM_USER + 1)
#define SB_GETTEXTW (WM_USER + 13)
#define SB_GETTEXTA (WM_USER + 2)
#define SB_GETTEXTLENGTHW (WM_USER + 12)
#define SB_GETTEXTLENGTHA (WM_USER + 3)
#define SB_SETPARTS (WM_USER + 4)
#define SB_GETPARTS (WM_USER + 6)
#define SB_GETBORDERS (WM_USER + 7)
#define SB_SETMINHEIGHT (WM_USER + 8)
#define SB_SIMPLE (WM_USER + 9)
#define SB_GETRECT (WM_USER + 10)
#define SB_ISSIMPLE (WM_USER + 14)
#define SB_SETICON (WM_USER + 15)
#define SB_SETTIPTEXTW (WM_USER + 17)
#define SB_GETTIPTEXTW (WM_USER + 19)
#define SB_GETICON (WM_USER + 20)
#define SB_SETBKCOLOR CCM_SETBKCOLOR
#define SB_SIMPLEID 0x00FF
#define SBT_OWNERDRAW 0x1000
#define SBT_NOBORDERS 0x0100
#define SBT_POPOUT 0x0200
#define SBT_RTLREADING 0x0400
#define SBT_NOTABPARSING 0x0800

/* ---- tooltips ---- */
#define TTS_ALWAYSTIP 0x01
#define TTS_NOPREFIX 0x02
#define TTS_BALLOON 0x40
#define TTF_IDISHWND 0x0001
#define TTF_CENTERTIP 0x0002
#define TTF_SUBCLASS 0x0010
#define TTF_TRACK 0x0020
#define TTF_ABSOLUTE 0x0080
#define TTM_ACTIVATE (WM_USER + 1)
#define TTM_SETDELAYTIME (WM_USER + 3)
#define TTM_ADDTOOLW (WM_USER + 50)
#define TTM_DELTOOLW (WM_USER + 51)
#define TTM_NEWTOOLRECTW (WM_USER + 52)
#define TTM_RELAYEVENT (WM_USER + 7)
#define TTM_GETTOOLINFOW (WM_USER + 53)
#define TTM_SETTOOLINFOW (WM_USER + 54)
#define TTM_UPDATETIPTEXTW (WM_USER + 57)
#define TTM_TRACKACTIVATE (WM_USER + 17)
#define TTM_TRACKPOSITION (WM_USER + 18)
#define TTM_SETMAXTIPWIDTH (WM_USER + 24)
#define TTM_POP (WM_USER + 28)
#define TTN_FIRST (0u - 520u)
#define TTN_GETDISPINFOW (TTN_FIRST - 10)
#define TTN_GETDISPINFOA (TTN_FIRST - 0)
#define TTN_NEEDTEXTW TTN_GETDISPINFOW
#define TTN_SHOW (TTN_FIRST - 1)
#define TTN_POP (TTN_FIRST - 2)
typedef struct tagTOOLINFOW { UINT cbSize, uFlags; HWND hwnd; UINT_PTR uId; RECT rect; HINSTANCE hinst; LPWSTR lpszText; LPARAM lParam; void *lpReserved; } TTTOOLINFOW, TOOLINFOW, *LPTOOLINFOW;
typedef struct tagNMTTDISPINFOW { NMHDR hdr; LPWSTR lpszText; WCHAR szText[80]; HINSTANCE hinst; UINT uFlags; LPARAM lParam; } NMTTDISPINFOW, *LPNMTTDISPINFOW, TOOLTIPTEXTW;

/* ---- up-down ---- */
#define UDS_WRAP 0x0001
#define UDS_SETBUDDYINT 0x0002
#define UDS_ALIGNRIGHT 0x0004
#define UDS_ALIGNLEFT 0x0008
#define UDS_AUTOBUDDY 0x0010
#define UDS_ARROWKEYS 0x0020
#define UDS_HORZ 0x0040
#define UDS_NOTHOUSANDS 0x0080
#define UDS_HOTTRACK 0x0100
#define UDM_SETRANGE (WM_USER + 101)
#define UDM_GETRANGE (WM_USER + 102)
#define UDM_SETPOS (WM_USER + 103)
#define UDM_GETPOS (WM_USER + 104)
#define UDM_SETBUDDY (WM_USER + 105)
#define UDM_GETBUDDY (WM_USER + 106)
#define UDM_SETACCEL (WM_USER + 107)
#define UDM_GETACCEL (WM_USER + 108)
#define UDM_SETBASE (WM_USER + 109)
#define UDM_GETBASE (WM_USER + 110)
#define UDM_SETRANGE32 (WM_USER + 111)
#define UDM_GETRANGE32 (WM_USER + 112)
#define UDM_SETPOS32 (WM_USER + 113)
#define UDM_GETPOS32 (WM_USER + 114)
#define UDN_FIRST (0u - 721u)
#define UDN_DELTAPOS (UDN_FIRST - 1)
typedef struct _NM_UPDOWN { NMHDR hdr; int iPos, iDelta; } NMUPDOWN, *LPNMUPDOWN;

/* ---- trackbar ---- */
#define TBS_AUTOTICKS 0x0001
#define TBS_VERT 0x0002
#define TBS_HORZ 0x0000
#define TBS_NOTICKS 0x0010
#define TBS_BOTH 0x0008
#define TBM_GETPOS (WM_USER)
#define TBM_GETRANGEMIN (WM_USER + 1)
#define TBM_GETRANGEMAX (WM_USER + 2)
#define TBM_SETTIC (WM_USER + 4)
#define TBM_SETPOS (WM_USER + 5)
#define TBM_SETRANGE (WM_USER + 6)
#define TBM_SETRANGEMIN (WM_USER + 7)
#define TBM_SETRANGEMAX (WM_USER + 8)
#define TBM_CLEARTICS (WM_USER + 9)
#define TBM_SETSEL (WM_USER + 10)
#define TBM_SETPAGESIZE (WM_USER + 21)
#define TBM_GETPAGESIZE (WM_USER + 22)
#define TBM_SETLINESIZE (WM_USER + 23)
#define TBM_GETLINESIZE (WM_USER + 24)
#define TBM_SETTICFREQ (WM_USER + 20)
#define TB_LINEUP 0
#define TB_LINEDOWN 1
#define TB_PAGEUP 2
#define TB_PAGEDOWN 3
#define TB_THUMBPOSITION 4
#define TB_THUMBTRACK 5
#define TB_TOP 6
#define TB_BOTTOM 7
#define TB_ENDTRACK 8

/* ---- tabs ---- */
#define TCS_BUTTONS 0x0100
#define TCS_MULTILINE 0x0200
#define TCS_FIXEDWIDTH 0x0400
#define TCS_FOCUSNEVER 0x8000
#define TCIF_TEXT 0x0001
#define TCIF_IMAGE 0x0002
#define TCIF_PARAM 0x0008
#define TCIF_STATE 0x0010
#define TCM_FIRST 0x1300
#define TCM_GETIMAGELIST (TCM_FIRST + 2)
#define TCM_SETIMAGELIST (TCM_FIRST + 3)
#define TCM_GETITEMCOUNT (TCM_FIRST + 4)
#define TCM_GETITEMW (TCM_FIRST + 60)
#define TCM_SETITEMW (TCM_FIRST + 61)
#define TCM_INSERTITEMW (TCM_FIRST + 62)
#define TCM_GETITEMA (TCM_FIRST + 5)
#define TCM_SETITEMA (TCM_FIRST + 6)
#define TCM_INSERTITEMA (TCM_FIRST + 7)
#define TCM_DELETEITEM (TCM_FIRST + 8)
#define TCM_DELETEALLITEMS (TCM_FIRST + 9)
#define TCM_GETITEMRECT (TCM_FIRST + 10)
#define TCM_GETCURSEL (TCM_FIRST + 11)
#define TCM_SETCURSEL (TCM_FIRST + 12)
#define TCM_HITTEST (TCM_FIRST + 13)
#define TCM_ADJUSTRECT (TCM_FIRST + 40)
#define TCM_SETITEMSIZE (TCM_FIRST + 41)
#define TCM_GETROWCOUNT (TCM_FIRST + 44)
#define TCM_GETCURFOCUS (TCM_FIRST + 47)
#define TCM_SETCURFOCUS (TCM_FIRST + 48)
#define TCN_FIRST (0u - 550u)
#define TCN_KEYDOWN (TCN_FIRST - 0)
#define TCN_SELCHANGE (TCN_FIRST - 1)
#define TCN_SELCHANGING (TCN_FIRST - 2)
typedef struct tagTCHITTESTINFO { POINT pt; UINT flags; } TCHITTESTINFO, *LPTCHITTESTINFO;
typedef struct tagTCITEMW { UINT mask; DWORD dwState, dwStateMask; LPWSTR pszText; int cchTextMax, iImage; LPARAM lParam; } TCITEMW, *LPTCITEMW;

/* ---- header ---- */
#define HDS_HORZ 0x0000
#define HDS_BUTTONS 0x0002
#define HDS_HOTTRACK 0x0004
#define HDS_HIDDEN 0x0008
#define HDS_DRAGDROP 0x0040
#define HDS_FULLDRAG 0x0080
#define HDI_WIDTH 0x0001
#define HDI_HEIGHT HDI_WIDTH
#define HDI_TEXT 0x0002
#define HDI_FORMAT 0x0004
#define HDI_LPARAM 0x0008
#define HDI_BITMAP 0x0010
#define HDI_IMAGE 0x0020
#define HDI_ORDER 0x0080
#define HDF_LEFT 0x0000
#define HDF_RIGHT 0x0001
#define HDF_CENTER 0x0002
#define HDF_JUSTIFYMASK 0x0003
#define HDF_STRING 0x4000
#define HDF_SORTUP 0x0400
#define HDF_SORTDOWN 0x0200
#define HDF_IMAGE 0x0800
#define HDM_FIRST 0x1200
#define HDM_GETITEMCOUNT (HDM_FIRST + 0)
#define HDM_INSERTITEMW (HDM_FIRST + 10)
#define HDM_DELETEITEM (HDM_FIRST + 2)
#define HDM_GETITEMW (HDM_FIRST + 11)
#define HDM_SETITEMW (HDM_FIRST + 12)
#define HDM_LAYOUT (HDM_FIRST + 5)
#define HDM_HITTEST (HDM_FIRST + 6)
#define HDM_GETITEMRECT (HDM_FIRST + 7)
#define HDM_SETIMAGELIST (HDM_FIRST + 8)
#define HDM_GETIMAGELIST (HDM_FIRST + 9)
#define HDM_ORDERTOINDEX (HDM_FIRST + 15)
#define HDM_GETORDERARRAY (HDM_FIRST + 17)
#define HDM_SETORDERARRAY (HDM_FIRST + 18)
#define HDN_FIRST (0u - 300u)
#define HDN_ITEMCHANGINGW (HDN_FIRST - 20)
#define HDN_ITEMCHANGEDW (HDN_FIRST - 21)
#define HDN_ITEMCLICKW (HDN_FIRST - 22)
#define HDN_DIVIDERDBLCLICKW (HDN_FIRST - 25)
#define HDN_BEGINTRACKW (HDN_FIRST - 26)
#define HDN_ENDTRACKW (HDN_FIRST - 27)
#define HDN_TRACKW (HDN_FIRST - 28)
typedef struct _HD_ITEMW { UINT mask; int cxy; LPWSTR pszText; HBITMAP hbm; int cchTextMax, fmt; LPARAM lParam; int iImage, iOrder; UINT type; void *pvFilter; UINT state; } HDITEMW, *LPHDITEMW;
typedef struct _HD_LAYOUT { RECT *prc; WINDOWPOS *pwpos; } HDLAYOUT, *LPHDLAYOUT;
typedef struct _HD_HITTESTINFO { POINT pt; UINT flags; int iItem; } HDHITTESTINFO, *LPHDHITTESTINFO;
typedef struct tagNMHEADERW { NMHDR hdr; int iItem, iButton; HDITEMW *pitem; } NMHEADERW, *LPNMHEADERW;
#define HHT_ONHEADER 0x0002
#define HHT_ONDIVIDER 0x0004
#define HHT_NOWHERE 0x0001

/* ---- list view ---- */
#define LVS_ICON 0x0000
#define LVS_REPORT 0x0001
#define LVS_SMALLICON 0x0002
#define LVS_LIST 0x0003
#define LVS_TYPEMASK 0x0003
#define LVS_SINGLESEL 0x0004
#define LVS_SHOWSELALWAYS 0x0008
#define LVS_SORTASCENDING 0x0010
#define LVS_SORTDESCENDING 0x0020
#define LVS_SHAREIMAGELISTS 0x0040
#define LVS_NOLABELWRAP 0x0080
#define LVS_AUTOARRANGE 0x0100
#define LVS_EDITLABELS 0x0200
#define LVS_OWNERDATA 0x1000
#define LVS_NOSCROLL 0x2000
#define LVS_ALIGNTOP 0x0000
#define LVS_OWNERDRAWFIXED 0x0400
#define LVS_NOCOLUMNHEADER 0x4000
#define LVS_NOSORTHEADER 0x8000
#define LVS_EX_GRIDLINES 0x00000001
#define LVS_EX_SUBITEMIMAGES 0x00000002
#define LVS_EX_CHECKBOXES 0x00000004
#define LVS_EX_TRACKSELECT 0x00000008
#define LVS_EX_HEADERDRAGDROP 0x00000010
#define LVS_EX_FULLROWSELECT 0x00000020
#define LVS_EX_ONECLICKACTIVATE 0x00000040
#define LVS_EX_TWOCLICKACTIVATE 0x00000080
#define LVS_EX_INFOTIP 0x00000400
#define LVS_EX_LABELTIP 0x00004000
#define LVS_EX_DOUBLEBUFFER 0x00010000
#define LVSIL_NORMAL 0
#define LVSIL_SMALL 1
#define LVSIL_STATE 2
#define LVIF_TEXT 0x00000001
#define LVIF_IMAGE 0x00000002
#define LVIF_PARAM 0x00000004
#define LVIF_STATE 0x00000008
#define LVIF_INDENT 0x00000010
#define LVIF_NORECOMPUTE 0x00000800
#define LVIF_GROUPID 0x00000100
#define LVIF_COLUMNS 0x00000200
#define LVIF_DI_SETITEM 0x00001000
#define LVIS_FOCUSED 0x0001
#define LVIS_SELECTED 0x0002
#define LVIS_CUT 0x0004
#define LVIS_DROPHILITED 0x0008
#define LVIS_OVERLAYMASK 0x0F00
#define LVIS_STATEIMAGEMASK 0xF000
#define INDEXTOSTATEIMAGEMASK(i) ((i) << 12)
#define LVNI_ALL 0x0000
#define LVNI_FOCUSED 0x0001
#define LVNI_SELECTED 0x0002
#define LVNI_CUT 0x0004
#define LVNI_DROPHILITED 0x0008
#define LVNI_ABOVE 0x0100
#define LVNI_BELOW 0x0200
#define LVNI_TOLEFT 0x0400
#define LVNI_TORIGHT 0x0800
#define LVCF_FMT 0x0001
#define LVCF_WIDTH 0x0002
#define LVCF_TEXT 0x0004
#define LVCF_SUBITEM 0x0008
#define LVCF_IMAGE 0x0010
#define LVCF_ORDER 0x0020
#define LVCFMT_LEFT 0x0000
#define LVCFMT_RIGHT 0x0001
#define LVCFMT_CENTER 0x0002
#define LVCFMT_JUSTIFYMASK 0x0003
#define LVSCW_AUTOSIZE (-1)
#define LVSCW_AUTOSIZE_USEHEADER (-2)
#define LVIR_BOUNDS 0
#define LVIR_ICON 1
#define LVIR_LABEL 2
#define LVIR_SELECTBOUNDS 3
#define LVHT_NOWHERE 0x0001
#define LVHT_ONITEMICON 0x0002
#define LVHT_ONITEMLABEL 0x0004
#define LVHT_ONITEMSTATEICON 0x0008
#define LVHT_ONITEM (LVHT_ONITEMICON | LVHT_ONITEMLABEL | LVHT_ONITEMSTATEICON)
#define LVHT_ABOVE 0x0008
#define LVHT_BELOW 0x0010
#define LVHT_TORIGHT 0x0020
#define LVHT_TOLEFT 0x0040
#define LVFI_PARAM 0x0001
#define LVFI_STRING 0x0002
#define LVFI_PARTIAL 0x0008
#define LVFI_WRAP 0x0020
#define LVSICF_NOINVALIDATEALL 0x00000001
#define LVSICF_NOSCROLL 0x00000002
#define LV_VIEW_ICON 0
#define LV_VIEW_DETAILS 1
#define LV_VIEW_SMALLICON 2
#define LV_VIEW_LIST 3
#define LV_VIEW_TILE 4
#define LVM_FIRST 0x1000
#define LVM_GETBKCOLOR (LVM_FIRST + 0)
#define LVM_SETBKCOLOR (LVM_FIRST + 1)
#define LVM_GETIMAGELIST (LVM_FIRST + 2)
#define LVM_SETIMAGELIST (LVM_FIRST + 3)
#define LVM_GETITEMCOUNT (LVM_FIRST + 4)
#define LVM_GETITEMA (LVM_FIRST + 5)
#define LVM_GETITEMW (LVM_FIRST + 75)
#define LVM_SETITEMA (LVM_FIRST + 6)
#define LVM_SETITEMW (LVM_FIRST + 76)
#define LVM_INSERTITEMA (LVM_FIRST + 7)
#define LVM_INSERTITEMW (LVM_FIRST + 77)
#define LVM_DELETEITEM (LVM_FIRST + 8)
#define LVM_DELETEALLITEMS (LVM_FIRST + 9)
#define LVM_GETCALLBACKMASK (LVM_FIRST + 10)
#define LVM_SETCALLBACKMASK (LVM_FIRST + 11)
#define LVM_GETNEXTITEM (LVM_FIRST + 12)
#define LVM_FINDITEMA (LVM_FIRST + 13)
#define LVM_FINDITEMW (LVM_FIRST + 83)
#define LVM_GETITEMRECT (LVM_FIRST + 14)
#define LVM_SETITEMPOSITION (LVM_FIRST + 15)
#define LVM_GETITEMPOSITION (LVM_FIRST + 16)
#define LVM_GETSTRINGWIDTHA (LVM_FIRST + 17)
#define LVM_GETSTRINGWIDTHW (LVM_FIRST + 87)
#define LVM_HITTEST (LVM_FIRST + 18)
#define LVM_ENSUREVISIBLE (LVM_FIRST + 19)
#define LVM_SCROLL (LVM_FIRST + 20)
#define LVM_REDRAWITEMS (LVM_FIRST + 21)
#define LVM_ARRANGE (LVM_FIRST + 22)
#define LVM_EDITLABELA (LVM_FIRST + 23)
#define LVM_EDITLABELW (LVM_FIRST + 118)
#define LVM_GETEDITCONTROL (LVM_FIRST + 24)
#define LVM_GETCOLUMNA (LVM_FIRST + 25)
#define LVM_GETCOLUMNW (LVM_FIRST + 95)
#define LVM_SETCOLUMNA (LVM_FIRST + 26)
#define LVM_SETCOLUMNW (LVM_FIRST + 96)
#define LVM_INSERTCOLUMNA (LVM_FIRST + 27)
#define LVM_INSERTCOLUMNW (LVM_FIRST + 97)
#define LVM_DELETECOLUMN (LVM_FIRST + 28)
#define LVM_GETCOLUMNWIDTH (LVM_FIRST + 29)
#define LVM_SETCOLUMNWIDTH (LVM_FIRST + 30)
#define LVM_GETHEADER (LVM_FIRST + 31)
#define LVM_CREATEDRAGIMAGE (LVM_FIRST + 33)
#define LVM_GETVIEWRECT (LVM_FIRST + 34)
#define LVM_GETTEXTCOLOR (LVM_FIRST + 35)
#define LVM_SETTEXTCOLOR (LVM_FIRST + 36)
#define LVM_GETTEXTBKCOLOR (LVM_FIRST + 37)
#define LVM_SETTEXTBKCOLOR (LVM_FIRST + 38)
#define LVM_GETTOPINDEX (LVM_FIRST + 39)
#define LVM_GETCOUNTPERPAGE (LVM_FIRST + 40)
#define LVM_GETORIGIN (LVM_FIRST + 41)
#define LVM_UPDATE (LVM_FIRST + 42)
#define LVM_SETITEMSTATE (LVM_FIRST + 43)
#define LVM_GETITEMSTATE (LVM_FIRST + 44)
#define LVM_GETITEMTEXTA (LVM_FIRST + 45)
#define LVM_GETITEMTEXTW (LVM_FIRST + 115)
#define LVM_SETITEMTEXTA (LVM_FIRST + 46)
#define LVM_SETITEMTEXTW (LVM_FIRST + 116)
#define LVM_SETITEMCOUNT (LVM_FIRST + 47)
#define LVM_SORTITEMS (LVM_FIRST + 48)
#define LVM_SETITEMPOSITION32 (LVM_FIRST + 49)
#define LVM_GETSELECTEDCOUNT (LVM_FIRST + 50)
#define LVM_GETITEMSPACING (LVM_FIRST + 51)
#define LVM_GETISEARCHSTRINGW (LVM_FIRST + 117)
#define LVM_SETICONSPACING (LVM_FIRST + 53)
#define LVM_SETEXTENDEDLISTVIEWSTYLE (LVM_FIRST + 54)
#define LVM_GETEXTENDEDLISTVIEWSTYLE (LVM_FIRST + 55)
#define LVM_GETSUBITEMRECT (LVM_FIRST + 56)
#define LVM_SUBITEMHITTEST (LVM_FIRST + 57)
#define LVM_SETCOLUMNORDERARRAY (LVM_FIRST + 58)
#define LVM_GETCOLUMNORDERARRAY (LVM_FIRST + 59)
#define LVM_SETHOTITEM (LVM_FIRST + 60)
#define LVM_GETHOTITEM (LVM_FIRST + 61)
#define LVM_SETHOTCURSOR (LVM_FIRST + 62)
#define LVM_APPROXIMATEVIEWRECT (LVM_FIRST + 64)
#define LVM_GETSELECTIONMARK (LVM_FIRST + 66)
#define LVM_SETSELECTIONMARK (LVM_FIRST + 67)
#define LVM_SETHOVERTIME (LVM_FIRST + 71)
#define LVM_SETTOOLTIPS (LVM_FIRST + 74)
#define LVM_GETTOOLTIPS (LVM_FIRST + 78)
#define LVM_SORTITEMSEX (LVM_FIRST + 81)
#define LVM_SETVIEW (LVM_FIRST + 142)
#define LVM_GETVIEW (LVM_FIRST + 143)
#define LVM_ENABLEGROUPVIEW (LVM_FIRST + 157)
#define LVM_SETSELECTEDCOLUMN (LVM_FIRST + 140)
#define LVM_GETSELECTEDCOLUMN (LVM_FIRST + 174)
#define LVM_ISITEMVISIBLE (LVM_FIRST + 182)
#define LVN_FIRST (0u - 100u)
#define LVN_ITEMCHANGING (LVN_FIRST - 0)
#define LVN_ITEMCHANGED (LVN_FIRST - 1)
#define LVN_INSERTITEM (LVN_FIRST - 2)
#define LVN_DELETEITEM (LVN_FIRST - 3)
#define LVN_DELETEALLITEMS (LVN_FIRST - 4)
#define LVN_BEGINLABELEDITW (LVN_FIRST - 75)
#define LVN_ENDLABELEDITW (LVN_FIRST - 76)
#define LVN_COLUMNCLICK (LVN_FIRST - 8)
#define LVN_BEGINDRAG (LVN_FIRST - 9)
#define LVN_BEGINRDRAG (LVN_FIRST - 11)
#define LVN_ODCACHEHINT (LVN_FIRST - 13)
#define LVN_ODFINDITEMW (LVN_FIRST - 79)
#define LVN_ITEMACTIVATE (LVN_FIRST - 14)
#define LVN_ODSTATECHANGED (LVN_FIRST - 15)
#define LVN_HOTTRACK (LVN_FIRST - 21)
#define LVN_GETDISPINFOW (LVN_FIRST - 77)
#define LVN_GETDISPINFOA (LVN_FIRST - 50)
#define LVN_SETDISPINFOW (LVN_FIRST - 78)
#define LVN_KEYDOWN (LVN_FIRST - 55)
#define LVN_MARQUEEBEGIN (LVN_FIRST - 56)
#define LVN_GETINFOTIPW (LVN_FIRST - 58)
typedef struct tagLVITEMW { UINT mask; int iItem, iSubItem; UINT state, stateMask; LPWSTR pszText; int cchTextMax, iImage; LPARAM lParam; int iIndent, iGroupId; UINT cColumns; PUINT puColumns; int *piColFmt; int iGroup; } LVITEMW, *LPLVITEMW;
typedef struct tagLVCOLUMNW { UINT mask; int fmt, cx; LPWSTR pszText; int cchTextMax, iSubItem, iImage, iOrder, cxMin, cxDefault, cxIdeal; } LVCOLUMNW, *LPLVCOLUMNW;
typedef struct tagLVHITTESTINFO { POINT pt; UINT flags; int iItem, iSubItem, iGroup; } LVHITTESTINFO, *LPLVHITTESTINFO;
typedef struct tagLVFINDINFOW { UINT flags; LPCWSTR psz; LPARAM lParam; POINT pt; UINT vkDirection; } LVFINDINFOW, *LPFINDINFOW;
typedef struct tagNMLISTVIEW { NMHDR hdr; int iItem, iSubItem; UINT uNewState, uOldState, uChanged; POINT ptAction; LPARAM lParam; } NMLISTVIEW, *LPNMLISTVIEW;
typedef struct tagNMITEMACTIVATE { NMHDR hdr; int iItem, iSubItem; UINT uNewState, uOldState, uChanged; POINT ptAction; LPARAM lParam; UINT uKeyFlags; } NMITEMACTIVATE, *LPNMITEMACTIVATE;
typedef struct tagLVDISPINFOW { NMHDR hdr; LVITEMW item; } NMLVDISPINFOW, *LPNMLVDISPINFOW, LV_DISPINFOW;
typedef struct tagLVKEYDOWN { NMHDR hdr; WORD wVKey; UINT flags; } NMLVKEYDOWN, *LPNMLVKEYDOWN;
typedef struct tagNMLVCACHEHINT { NMHDR hdr; int iFrom, iTo; } NMLVCACHEHINT, *LPNMLVCACHEHINT;
typedef struct tagNMLVFINDITEMW { NMHDR hdr; int iStart; LVFINDINFOW lvfi; } NMLVFINDITEMW, *LPNMLVFINDITEMW;
typedef struct tagNMLVCUSTOMDRAW { NMCUSTOMDRAW nmcd; COLORREF clrText, clrTextBk; int iSubItem; DWORD dwItemType; COLORREF clrFace; int iIconEffect, iIconPhase, iPartId, iStateId; RECT rcText; UINT uAlign; } NMLVCUSTOMDRAW, *LPNMLVCUSTOMDRAW;
typedef struct tagNMLVODSTATECHANGE { NMHDR hdr; int iFrom, iTo; UINT uNewState, uOldState; } NMLVODSTATECHANGE, *LPNMLVODSTATECHANGE;
typedef int (CALLBACK *PFNLVCOMPARE)(LPARAM, LPARAM, LPARAM);

/* ---- toolbar ---- */
#define TBSTYLE_BUTTON 0x0000
#define TBSTYLE_SEP 0x0001
#define TBSTYLE_CHECK 0x0002
#define TBSTYLE_GROUP 0x0004
#define TBSTYLE_CHECKGROUP (TBSTYLE_GROUP | TBSTYLE_CHECK)
#define TBSTYLE_DROPDOWN 0x0008
#define TBSTYLE_AUTOSIZE 0x0010
#define TBSTYLE_NOPREFIX 0x0020
#define TBSTYLE_TOOLTIPS 0x0100
#define TBSTYLE_WRAPABLE 0x0200
#define TBSTYLE_ALTDRAG 0x0400
#define TBSTYLE_FLAT 0x0800
#define TBSTYLE_LIST 0x1000
#define TBSTYLE_CUSTOMERASE 0x2000
#define TBSTYLE_TRANSPARENT 0x8000
#define TBSTYLE_EX_DRAWDDARROWS 0x00000001
#define TBSTYLE_EX_MIXEDBUTTONS 0x00000008
#define TBSTYLE_EX_HIDECLIPPEDBUTTONS 0x00000010
#define BTNS_BUTTON TBSTYLE_BUTTON
#define BTNS_SEP TBSTYLE_SEP
#define BTNS_CHECK TBSTYLE_CHECK
#define BTNS_GROUP TBSTYLE_GROUP
#define BTNS_CHECKGROUP TBSTYLE_CHECKGROUP
#define BTNS_DROPDOWN TBSTYLE_DROPDOWN
#define BTNS_AUTOSIZE TBSTYLE_AUTOSIZE
#define BTNS_NOPREFIX TBSTYLE_NOPREFIX
#define BTNS_SHOWTEXT 0x0040
#define BTNS_WHOLEDROPDOWN 0x0080
#define TBSTATE_CHECKED 0x01
#define TBSTATE_PRESSED 0x02
#define TBSTATE_ENABLED 0x04
#define TBSTATE_HIDDEN 0x08
#define TBSTATE_INDETERMINATE 0x10
#define TBSTATE_WRAP 0x20
#define TBSTATE_ELLIPSES 0x40
#define TBSTATE_MARKED 0x80
#define TB_ENABLEBUTTON (WM_USER + 1)
#define TB_CHECKBUTTON (WM_USER + 2)
#define TB_PRESSBUTTON (WM_USER + 3)
#define TB_HIDEBUTTON (WM_USER + 4)
#define TB_INDETERMINATE (WM_USER + 5)
#define TB_MARKBUTTON (WM_USER + 6)
#define TB_ISBUTTONENABLED (WM_USER + 9)
#define TB_ISBUTTONCHECKED (WM_USER + 10)
#define TB_ISBUTTONPRESSED (WM_USER + 11)
#define TB_ISBUTTONHIDDEN (WM_USER + 12)
#define TB_SETSTATE (WM_USER + 17)
#define TB_GETSTATE (WM_USER + 18)
#define TB_ADDBITMAP (WM_USER + 19)
#define TB_ADDBUTTONSA (WM_USER + 20)
#define TB_INSERTBUTTONA (WM_USER + 21)
#define TB_DELETEBUTTON (WM_USER + 22)
#define TB_GETBUTTON (WM_USER + 23)
#define TB_BUTTONCOUNT (WM_USER + 24)
#define TB_COMMANDTOINDEX (WM_USER + 25)
#define TB_CUSTOMIZE (WM_USER + 27)
#define TB_ADDSTRINGA (WM_USER + 28)
#define TB_GETITEMRECT (WM_USER + 29)
#define TB_BUTTONSTRUCTSIZE (WM_USER + 30)
#define TB_SETBUTTONSIZE (WM_USER + 31)
#define TB_SETBITMAPSIZE (WM_USER + 32)
#define TB_AUTOSIZE (WM_USER + 33)
#define TB_GETTOOLTIPS (WM_USER + 35)
#define TB_SETTOOLTIPS (WM_USER + 36)
#define TB_SETPARENT (WM_USER + 37)
#define TB_SETROWS (WM_USER + 39)
#define TB_GETROWS (WM_USER + 40)
#define TB_SETCMDID (WM_USER + 42)
#define TB_CHANGEBITMAP (WM_USER + 43)
#define TB_GETBITMAP (WM_USER + 44)
#define TB_GETBUTTONTEXTA (WM_USER + 45)
#define TB_GETBUTTONTEXTW (WM_USER + 75)
#define TB_REPLACEBITMAP (WM_USER + 46)
#define TB_SETINDENT (WM_USER + 47)
#define TB_SETIMAGELIST (WM_USER + 48)
#define TB_GETIMAGELIST (WM_USER + 49)
#define TB_LOADIMAGES (WM_USER + 50)
#define TB_GETRECT (WM_USER + 51)
#define TB_SETHOTIMAGELIST (WM_USER + 52)
#define TB_GETHOTIMAGELIST (WM_USER + 53)
#define TB_SETDISABLEDIMAGELIST (WM_USER + 54)
#define TB_GETDISABLEDIMAGELIST (WM_USER + 55)
#define TB_SETSTYLE (WM_USER + 56)
#define TB_GETSTYLE (WM_USER + 57)
#define TB_GETBUTTONSIZE (WM_USER + 58)
#define TB_SETBUTTONWIDTH (WM_USER + 59)
#define TB_SETMAXTEXTROWS (WM_USER + 60)
#define TB_GETTEXTROWS (WM_USER + 61)
#define TB_GETHOTITEM (WM_USER + 71)
#define TB_SETHOTITEM (WM_USER + 72)
#define TB_SETEXTENDEDSTYLE (WM_USER + 84)
#define TB_GETEXTENDEDSTYLE (WM_USER + 85)
#define TB_GETPADDING (WM_USER + 86)
#define TB_SETPADDING (WM_USER + 87)
#define TB_HITTEST (WM_USER + 69)
#define TB_GETBUTTONINFOW (WM_USER + 63)
#define TB_SETBUTTONINFOW (WM_USER + 64)
#define TB_INSERTBUTTONW (WM_USER + 67)
#define TB_ADDBUTTONSW (WM_USER + 68)
#define TB_ADDSTRINGW (WM_USER + 77)
#define TB_GETMAXSIZE (WM_USER + 83)
#define TB_GETIDEALSIZE (WM_USER + 99)
#define TB_SETDRAWTEXTFLAGS (WM_USER + 70)
#define TB_ADDBUTTONS TB_ADDBUTTONSW
#define TB_INSERTBUTTON TB_INSERTBUTTONW
#define TBN_FIRST (0u - 700u)
#define TBN_DROPDOWN (TBN_FIRST - 10)
#define TBN_HOTITEMCHANGE (TBN_FIRST - 13)
#define TBN_GETINFOTIPW (TBN_FIRST - 19)
#define TBDDRET_DEFAULT 0
#define TBIF_IMAGE 0x00000001
#define TBIF_TEXT 0x00000002
#define TBIF_STATE 0x00000004
#define TBIF_STYLE 0x00000008
#define TBIF_LPARAM 0x00000010
#define TBIF_COMMAND 0x00000020
#define TBIF_SIZE 0x00000040
#define TBIF_BYINDEX 0x80000000
#define HINST_COMMCTRL ((HINSTANCE)-1)
#define IDB_STD_SMALL_COLOR 0
#define IDB_STD_LARGE_COLOR 1
#define IDB_VIEW_SMALL_COLOR 4
#define IDB_VIEW_LARGE_COLOR 5
typedef struct _TBBUTTON { int iBitmap, idCommand; BYTE fsState, fsStyle; BYTE bReserved[6]; DWORD_PTR dwData; INT_PTR iString; } TBBUTTON, *PTBBUTTON, *LPTBBUTTON;
typedef const TBBUTTON *LPCTBBUTTON;
typedef struct tagTBADDBITMAP { HINSTANCE hInst; UINT_PTR nID; } TBADDBITMAP, *LPTBADDBITMAP;
typedef struct { UINT cbSize, dwMask; int idCommand, iImage; BYTE fsState, fsStyle; WORD cx; DWORD_PTR lParam; LPWSTR pszText; int cchText; } TBBUTTONINFOW, *LPTBBUTTONINFOW;
typedef struct tagNMTOOLBARW { NMHDR hdr; int iItem; TBBUTTON tbButton; int cchText; LPWSTR pszText; RECT rcButton; } NMTOOLBARW, *LPNMTOOLBARW;

/* ---- rebar ---- */
#define RBS_TOOLTIPS 0x00000100
#define RBS_VARHEIGHT 0x00000200
#define RBS_BANDBORDERS 0x00000400
#define RBS_FIXEDORDER 0x00000800
#define RBS_AUTOSIZE 0x00002000
#define RBS_DBLCLKTOGGLE 0x00008000
#define RBBS_BREAK 0x00000001
#define RBBS_FIXEDSIZE 0x00000002
#define RBBS_CHILDEDGE 0x00000004
#define RBBS_HIDDEN 0x00000008
#define RBBS_GRIPPERALWAYS 0x00000080
#define RBBS_NOGRIPPER 0x00000100
#define RBBS_USECHEVRON 0x00000200
#define RBBIM_STYLE 0x00000001
#define RBBIM_COLORS 0x00000002
#define RBBIM_TEXT 0x00000004
#define RBBIM_IMAGE 0x00000008
#define RBBIM_CHILD 0x00000010
#define RBBIM_CHILDSIZE 0x00000020
#define RBBIM_SIZE 0x00000040
#define RBBIM_BACKGROUND 0x00000080
#define RBBIM_ID 0x00000100
#define RBBIM_IDEALSIZE 0x00000200
#define RBBIM_LPARAM 0x00000400
#define RBBIM_HEADERSIZE 0x00000800
#define RB_INSERTBANDW (WM_USER + 10)
#define RB_DELETEBAND (WM_USER + 2)
#define RB_GETBARINFO (WM_USER + 3)
#define RB_SETBARINFO (WM_USER + 4)
#define RB_SETBANDINFOW (WM_USER + 11)
#define RB_GETBANDINFOW (WM_USER + 28)
#define RB_GETBANDCOUNT (WM_USER + 12)
#define RB_GETROWCOUNT (WM_USER + 13)
#define RB_GETROWHEIGHT (WM_USER + 14)
#define RB_IDTOINDEX (WM_USER + 16)
#define RB_GETBARHEIGHT (WM_USER + 27)
#define RB_SHOWBAND (WM_USER + 35)
#define RB_MAXIMIZEBAND (WM_USER + 31)
#define RB_MINIMIZEBAND (WM_USER + 30)
#define RB_GETRECT (WM_USER + 9)
#define RBN_FIRST (0u - 831u)
#define RBN_HEIGHTCHANGE (RBN_FIRST - 0)
typedef struct tagREBARBANDINFOW { UINT cbSize, fMask, fStyle; COLORREF clrFore, clrBack; LPWSTR lpText; UINT cch; int iImage; HWND hwndChild; UINT cxMinChild, cyMinChild, cx; HBITMAP hbmBack; UINT wID, cyChild, cyMaxChild, cyIntegral, cxIdeal; LPARAM lParam; UINT cxHeader; RECT rcChevronLocation; UINT uChevronState; } REBARBANDINFOW, *LPREBARBANDINFOW;
typedef struct tagREBARINFO { UINT cbSize, fMask; HIMAGELIST himl; } REBARINFO, *LPREBARINFO;

/* ---- ComboBoxEx ---- */
#define CBEIF_TEXT 0x00000001
#define CBEIF_IMAGE 0x00000002
#define CBEIF_SELECTEDIMAGE 0x00000004
#define CBEIF_OVERLAY 0x00000008
#define CBEIF_INDENT 0x00000010
#define CBEIF_LPARAM 0x00000020
#define CBEM_INSERTITEMW (WM_USER + 11)
#define CBEM_SETIMAGELIST (WM_USER + 2)
#define CBEM_GETIMAGELIST (WM_USER + 3)
#define CBEM_DELETEITEM CB_DELETESTRING
#define CBEM_GETCOMBOCONTROL (WM_USER + 6)
#define CBEM_GETEDITCONTROL (WM_USER + 7)
#define CBEM_SETEXSTYLE (WM_USER + 8)
#define CBEM_SETEXTENDEDSTYLE (WM_USER + 14)
#define CBEM_GETEXSTYLE (WM_USER + 9)
#define CBEM_GETEXTENDEDSTYLE (WM_USER + 9)
#define CBEM_HASEDITCHANGED (WM_USER + 10)
#define CBEM_SETITEMW (WM_USER + 12)
#define CBEM_GETITEMW (WM_USER + 13)
#define CBEN_FIRST (0u - 800u)
#define CBEN_GETDISPINFOW (CBEN_FIRST - 7)
#define CBEN_INSERTITEM (CBEN_FIRST - 1)
#define CBEN_DELETEITEM (CBEN_FIRST - 2)
#define CBEN_BEGINEDIT (CBEN_FIRST - 4)
#define CBEN_ENDEDITW (CBEN_FIRST - 6)
#define CBENF_KILLFOCUS 1
#define CBENF_RETURN 2
#define CBENF_ESCAPE 3
#define CBENF_DROPDOWN 4
typedef struct tagCOMBOBOXEXITEMW { UINT mask; INT_PTR iItem; LPWSTR pszText; int cchTextMax, iImage, iSelectedImage, iOverlay, iIndent; LPARAM lParam; } COMBOBOXEXITEMW, *PCOMBOBOXEXITEMW;
typedef const COMBOBOXEXITEMW *PCCOMBOEXITEMW;
typedef struct { NMHDR hdr; COMBOBOXEXITEMW ceItem; } NMCOMBOBOXEXW, *PNMCOMBOBOXEXW;
typedef struct { NMHDR hdr; BOOL fChanged; int iNewSelection; WCHAR szText[260]; int iWhy; } NMCBEENDEDITW, *PNMCBEENDEDITW;

/* ---- property sheets ---- */
#define PSP_DEFAULT 0x00000000
#define PSP_DLGINDIRECT 0x00000001
#define PSP_USEHICON 0x00000002
#define PSP_USEICONID 0x00000004
#define PSP_USETITLE 0x00000008
#define PSP_RTLREADING 0x00000010
#define PSP_HASHELP 0x00000020
#define PSP_USEREFPARENT 0x00000040
#define PSP_USECALLBACK 0x00000080
#define PSH_DEFAULT 0x00000000
#define PSH_PROPTITLE 0x00000001
#define PSH_USEHICON 0x00000002
#define PSH_USEICONID 0x00000004
#define PSH_PROPSHEETPAGE 0x00000008
#define PSH_WIZARD 0x00000020
#define PSH_USEPSTARTPAGE 0x00000040
#define PSH_NOAPPLYNOW 0x00000080
#define PSH_USECALLBACK 0x00000100
#define PSH_HASHELP 0x00000200
#define PSH_MODELESS 0x00000400
#define PSH_NOCONTEXTHELP 0x02000000
#define PSN_FIRST (0u - 200u)
#define PSN_SETACTIVE (PSN_FIRST - 0)
#define PSN_KILLACTIVE (PSN_FIRST - 1)
#define PSN_APPLY (PSN_FIRST - 2)
#define PSN_RESET (PSN_FIRST - 3)
#define PSN_HELP (PSN_FIRST - 5)
#define PSN_QUERYCANCEL (PSN_FIRST - 9)
#define PSM_SETCURSEL (WM_USER + 101)
#define PSM_CHANGED (WM_USER + 104)
#define PSM_UNCHANGED (WM_USER + 109)
#define PSM_GETCURRENTPAGEHWND (WM_USER + 118)
#define PSM_GETTABCONTROL (WM_USER + 116)
#define PSM_PRESSBUTTON (WM_USER + 113)
#define PSM_SETTITLEW (WM_USER + 120)
#define PSM_APPLY (WM_USER + 110)
#define PSM_QUERYSIBLINGS (WM_USER + 108)
#define PSNRET_NOERROR 0
#define PSNRET_INVALID 1
#define PSNRET_INVALID_NOCHANGEPAGE 2
#define PSPCB_ADDREF 0
#define PSPCB_RELEASE 1
#define PSPCB_CREATE 2
#define PSCB_INITIALIZED 1
#define PSCB_PRECREATE 2
#define ID_PSRESTARTWINDOWS 0x2
#define ID_PSREBOOTSYSTEM (ID_PSRESTARTWINDOWS | 0x1)
typedef struct _PROPSHEETPAGEW *LPPROPSHEETPAGEW;
typedef UINT (CALLBACK *LPFNPSPCALLBACKW)(HWND, UINT, LPPROPSHEETPAGEW);
typedef struct _PROPSHEETPAGEW { DWORD dwSize, dwFlags; HINSTANCE hInstance; union { LPCWSTR pszTemplate; LPCDLGTEMPLATEW pResource; }; union { HICON hIcon; LPCWSTR pszIcon; }; LPCWSTR pszTitle; DLGPROC pfnDlgProc; LPARAM lParam; LPFNPSPCALLBACKW pfnCallback; UINT *pcRefParent; LPCWSTR pszHeaderTitle, pszHeaderSubTitle; HANDLE hActCtx; } PROPSHEETPAGEW;
typedef const PROPSHEETPAGEW *LPCPROPSHEETPAGEW;
typedef int (CALLBACK *PFNPROPSHEETCALLBACK)(HWND, UINT, LPARAM);
typedef struct _PROPSHEETHEADERW { DWORD dwSize, dwFlags; HWND hwndParent; HINSTANCE hInstance; union { HICON hIcon; LPCWSTR pszIcon; }; LPCWSTR pszCaption; UINT nPages; union { UINT nStartPage; LPCWSTR pStartPage; }; union { LPCPROPSHEETPAGEW ppsp; HPROPSHEETPAGE *phpage; }; PFNPROPSHEETCALLBACK pfnCallback; union { HBITMAP hbmWatermark; LPCWSTR pszbmWatermark; }; HPALETTE hplWatermark; union { HBITMAP hbmHeader; LPCWSTR pszbmHeader; }; } PROPSHEETHEADERW, *LPPROPSHEETHEADERW;
typedef const PROPSHEETHEADERW *LPCPROPSHEETHEADERW;
typedef struct _PSHNOTIFY { NMHDR hdr; LPARAM lParam; } PSHNOTIFY, *LPPSHNOTIFY;

/* ---- subclassing ---- */
typedef LRESULT (CALLBACK *SUBCLASSPROC)(HWND, UINT, WPARAM, LPARAM, UINT_PTR, DWORD_PTR);

/* ---- functions ---- */
CCAPI_ void WINAPI InitCommonControls(void);
CCAPI_ BOOL WINAPI InitCommonControlsEx(const INITCOMMONCONTROLSEX *icc);
CCAPI_ HIMAGELIST WINAPI ImageList_Create(int cx, int cy, UINT flags, int initial, int grow);
CCAPI_ BOOL WINAPI ImageList_Destroy(HIMAGELIST h);
CCAPI_ int WINAPI ImageList_Add(HIMAGELIST h, HBITMAP img, HBITMAP mask);
CCAPI_ int WINAPI ImageList_AddMasked(HIMAGELIST h, HBITMAP img, COLORREF mask);
CCAPI_ int WINAPI ImageList_ReplaceIcon(HIMAGELIST h, int i, HICON icon);
CCAPI_ int WINAPI ImageList_GetImageCount(HIMAGELIST h);
CCAPI_ BOOL WINAPI ImageList_SetImageCount(HIMAGELIST h, UINT n);
CCAPI_ BOOL WINAPI ImageList_GetIconSize(HIMAGELIST h, int *cx, int *cy);
CCAPI_ BOOL WINAPI ImageList_Draw(HIMAGELIST h, int i, HDC dc, int x, int y, UINT style);
CCAPI_ BOOL WINAPI ImageList_DrawEx(HIMAGELIST h, int i, HDC dc, int x, int y, int cx, int cy, COLORREF bk, COLORREF fg, UINT style);
CCAPI_ HICON WINAPI ImageList_GetIcon(HIMAGELIST h, int i, UINT flags);
CCAPI_ BOOL WINAPI ImageList_Remove(HIMAGELIST h, int i);
CCAPI_ COLORREF WINAPI ImageList_SetBkColor(HIMAGELIST h, COLORREF c);
#define ImageList_AddIcon(h, icon) ImageList_ReplaceIcon(h, -1, icon)
CCAPI_ BOOL WINAPI SetWindowSubclass(HWND h, SUBCLASSPROC fn, UINT_PTR id, DWORD_PTR data);
CCAPI_ BOOL WINAPI GetWindowSubclass(HWND h, SUBCLASSPROC fn, UINT_PTR id, DWORD_PTR *data);
CCAPI_ BOOL WINAPI RemoveWindowSubclass(HWND h, SUBCLASSPROC fn, UINT_PTR id);
CCAPI_ LRESULT WINAPI DefSubclassProc(HWND h, UINT msg, WPARAM wp, LPARAM lp);
CCAPI_ HWND WINAPI CreateStatusWindowW(LONG style, LPCWSTR text, HWND parent, UINT id);
CCAPI_ HPROPSHEETPAGE WINAPI CreatePropertySheetPageW(LPCPROPSHEETPAGEW p);
CCAPI_ BOOL WINAPI DestroyPropertySheetPage(HPROPSHEETPAGE p);
CCAPI_ INT_PTR WINAPI PropertySheetW(LPCPROPSHEETHEADERW h);
