#pragma once
#include <_nova.h>
_NOVA_BEGIN
_CRTIMP int *_errno(void);
#define errno (*_errno())
_NOVA_END
#define EPERM   1
#define ENOENT  2
#define EINTR   4
#define EIO     5
#define EBADF   9
#define EAGAIN  11
#define ENOMEM  12
#define EACCES  13
#define EFAULT  14
#define EEXIST  17
#define ENOTDIR 20
#define EISDIR  21
#define EINVAL  22
#define EMFILE  24
#define ENOSPC  28
#define ESPIPE  29
#define EPIPE   32
#define EDOM    33
#define ERANGE  34
#define ENOSYS  40
#define ENOTEMPTY 41
#define EILSEQ  42
/* the rest of the MSVC/POSIX set */
#define ESRCH        3
#define E2BIG        7
#define ENOEXEC      8
#define ECHILD       10
#define EBUSY        16
#define EXDEV        18
#define ENODEV       19
#define ENFILE       23
#define ENOTTY       25
#define EFBIG        27
#define EROFS        30
#define EMLINK       31
#define EDEADLK      36
#define ENAMETOOLONG 38
#define ENOLCK       39
#define ENXIO        6
#define EADDRINUSE   100
#define EADDRNOTAVAIL 101
#define EAFNOSUPPORT 102
#define EALREADY     103
#define ECONNABORTED 106
#define ECONNREFUSED 107
#define ECONNRESET   108
#define EHOSTUNREACH 110
#define EINPROGRESS  112
#define EISCONN      113
#define ELOOP        114
#define EMSGSIZE     115
#define ENETDOWN     116
#define ENETUNREACH  118
#define ENOBUFS      119
#define ENOTCONN     126
#define ENOTSOCK     128
#define ENOTSUP      129
#define EOPNOTSUPP   130
#define EOVERFLOW    132
#define ETIMEDOUT    138
#define EWOULDBLOCK  140
