/* inttypes.h — C99 format macros and conversions */
#pragma once
#include <_nova.h>
#include <stdint.h>
_NOVA_BEGIN
#define PRId8  "d"
#define PRId16 "d"
#define PRId32 "d"
#define PRId64 "lld"
#define PRIi8  "i"
#define PRIi16 "i"
#define PRIi32 "i"
#define PRIi64 "lli"
#define PRIu8  "u"
#define PRIu16 "u"
#define PRIu32 "u"
#define PRIu64 "llu"
#define PRIx8  "x"
#define PRIx16 "x"
#define PRIx32 "x"
#define PRIx64 "llx"
#define PRIX8  "X"
#define PRIX16 "X"
#define PRIX32 "X"
#define PRIX64 "llX"
#define PRIo32 "o"
#define PRIo64 "llo"
#define PRIdPTR "lld"
#define PRIiPTR "lli"
#define PRIuPTR "llu"
#define PRIxPTR "llx"
#define PRIXPTR "llX"
#define PRIdMAX "lld"
#define PRIuMAX "llu"
#define PRIxMAX "llx"
#define PRIdFAST32 "d"
#define PRIuFAST32 "u"
#define PRIdLEAST32 "d"
#define PRIuLEAST32 "u"
#define SCNd8  "hhd"
#define SCNd16 "hd"
#define SCNd32 "d"
#define SCNd64 "lld"
#define SCNu8  "hhu"
#define SCNu16 "hu"
#define SCNu32 "u"
#define SCNu64 "llu"
#define SCNx32 "x"
#define SCNx64 "llx"
#define SCNi32 "i"
typedef struct { intmax_t quot, rem; } imaxdiv_t;
_CRTIMP intmax_t  strtoimax(const char *s, char **end, int base);
_CRTIMP uintmax_t strtoumax(const char *s, char **end, int base);
_CRTIMP intmax_t  imaxabs(intmax_t x);
_NOVA_END
