/* winbase2.h — more of kernel32 (included by windows.h): overlapped I/O and
 * completion ports, file mapping, processes, file information, NLS,
 * console, time zones, waitable timers, interlocked lists */
#pragma once
typedef DWORD_PTR *PDWORD_PTR;
typedef ULONG64 *PULONG64;
typedef ULONGLONG *PULONGLONG;

typedef struct _OVERLAPPED {
    ULONG_PTR Internal, InternalHigh;
    union { struct { DWORD Offset, OffsetHigh; }; PVOID Pointer; };
    HANDLE hEvent;
} OVERLAPPED, *LPOVERLAPPED;
typedef struct _OVERLAPPED_ENTRY {
    ULONG_PTR lpCompletionKey;
    LPOVERLAPPED lpOverlapped;
    ULONG_PTR Internal;
    DWORD dwNumberOfBytesTransferred;
} OVERLAPPED_ENTRY, *LPOVERLAPPED_ENTRY;
typedef VOID (WINAPI *LPOVERLAPPED_COMPLETION_ROUTINE)(DWORD err, DWORD bytes, LPOVERLAPPED ov);

typedef struct _BY_HANDLE_FILE_INFORMATION {
    DWORD dwFileAttributes;
    FILETIME ftCreationTime, ftLastAccessTime, ftLastWriteTime;
    DWORD dwVolumeSerialNumber, nFileSizeHigh, nFileSizeLow, nNumberOfLinks, nFileIndexHigh, nFileIndexLow;
} BY_HANDLE_FILE_INFORMATION, *LPBY_HANDLE_FILE_INFORMATION;

typedef enum _FILE_INFO_BY_HANDLE_CLASS {
    FileBasicInfo, FileStandardInfo, FileNameInfo, FileRenameInfo, FileDispositionInfo,
    FileAllocationInfo, FileEndOfFileInfo, FileStreamInfo, FileCompressionInfo, FileAttributeTagInfo,
    FileIdBothDirectoryInfo, FileIdBothDirectoryRestartInfo, FileIoPriorityHintInfo, FileRemoteProtocolInfo,
    FileFullDirectoryInfo, FileFullDirectoryRestartInfo, FileStorageInfo, FileAlignmentInfo, FileIdInfo,
    FileIdExtdDirectoryInfo, FileIdExtdDirectoryRestartInfo, FileDispositionInfoEx, FileRenameInfoEx,
} FILE_INFO_BY_HANDLE_CLASS;
typedef struct _FILE_BASIC_INFO { LARGE_INTEGER CreationTime, LastAccessTime, LastWriteTime, ChangeTime; DWORD FileAttributes; } FILE_BASIC_INFO;
typedef struct _FILE_STANDARD_INFO { LARGE_INTEGER AllocationSize, EndOfFile; DWORD NumberOfLinks; BOOLEAN DeletePending, Directory; } FILE_STANDARD_INFO;
typedef struct _FILE_NAME_INFO { DWORD FileNameLength; WCHAR FileName[1]; } FILE_NAME_INFO;
typedef struct _FILE_ATTRIBUTE_TAG_INFO { DWORD FileAttributes, ReparseTag; } FILE_ATTRIBUTE_TAG_INFO;
typedef struct _FILE_DISPOSITION_INFO { BOOLEAN DeleteFile; } FILE_DISPOSITION_INFO;
typedef struct _FILE_END_OF_FILE_INFO { LARGE_INTEGER EndOfFile; } FILE_END_OF_FILE_INFO;
typedef struct _FILE_ID_128 { BYTE Identifier[16]; } FILE_ID_128;
typedef struct _FILE_ID_INFO { ULONGLONG VolumeSerialNumber; FILE_ID_128 FileId; } FILE_ID_INFO;

typedef struct _WIN32_FILE_ATTRIBUTE_DATA {
    DWORD dwFileAttributes;
    FILETIME ftCreationTime, ftLastAccessTime, ftLastWriteTime;
    DWORD nFileSizeHigh, nFileSizeLow;
} WIN32_FILE_ATTRIBUTE_DATA, *LPWIN32_FILE_ATTRIBUTE_DATA;
typedef enum { GetFileExInfoStandard } GET_FILEEX_INFO_LEVELS;
typedef enum { FindExInfoStandard, FindExInfoBasic } FINDEX_INFO_LEVELS;
typedef enum { FindExSearchNameMatch, FindExSearchLimitToDirectories } FINDEX_SEARCH_OPS;

typedef struct _MEMORY_BASIC_INFORMATION {
    PVOID BaseAddress, AllocationBase;
    DWORD AllocationProtect;
    WORD PartitionId;
    SIZE_T RegionSize;
    DWORD State, Protect, Type;
} MEMORY_BASIC_INFORMATION, *PMEMORY_BASIC_INFORMATION;
#define MEM_FREE    0x10000
#define MEM_PRIVATE 0x20000
#define MEM_MAPPED  0x40000
#define MEM_IMAGE   0x1000000

typedef struct _STARTUPINFOW {
    DWORD cb; LPWSTR lpReserved, lpDesktop, lpTitle;
    DWORD dwX, dwY, dwXSize, dwYSize, dwXCountChars, dwYCountChars, dwFillAttribute, dwFlags;
    WORD wShowWindow, cbReserved2; LPBYTE lpReserved2;
    HANDLE hStdInput, hStdOutput, hStdError;
} STARTUPINFOW, *LPSTARTUPINFOW;
typedef struct _PROCESS_INFORMATION { HANDLE hProcess, hThread; DWORD dwProcessId, dwThreadId; } PROCESS_INFORMATION, *LPPROCESS_INFORMATION;
typedef struct _PROC_THREAD_ATTRIBUTE_LIST *LPPROC_THREAD_ATTRIBUTE_LIST;
#define STARTF_USESTDHANDLES 0x00000100
#define STARTF_USESHOWWINDOW 0x00000001
#define CREATE_NO_WINDOW            0x08000000
#define CREATE_NEW_CONSOLE          0x00000010
#define CREATE_UNICODE_ENVIRONMENT  0x00000400
#define DETACHED_PROCESS            0x00000008
#define IDLE_PRIORITY_CLASS         0x00000040
#define NORMAL_PRIORITY_CLASS       0x00000020
#define HIGH_PRIORITY_CLASS         0x00000080
#define REALTIME_PRIORITY_CLASS     0x00000100
#define BELOW_NORMAL_PRIORITY_CLASS 0x00004000
#define ABOVE_NORMAL_PRIORITY_CLASS 0x00008000
#define PROCESS_MODE_BACKGROUND_BEGIN 0x00100000
#define PROCESS_MODE_BACKGROUND_END   0x00200000
#define THREAD_PRIORITY_IDLE          (-15)
#define THREAD_PRIORITY_LOWEST        (-2)
#define THREAD_PRIORITY_BELOW_NORMAL  (-1)
#define THREAD_PRIORITY_NORMAL        0
#define THREAD_PRIORITY_ABOVE_NORMAL  1
#define THREAD_PRIORITY_HIGHEST       2
#define THREAD_PRIORITY_TIME_CRITICAL 15
#define THREAD_PRIORITY_ERROR_RETURN  0x7FFFFFFF

typedef struct _CPINFO { UINT MaxCharSize; BYTE DefaultChar[2]; BYTE LeadByte[12]; } CPINFO, *LPCPINFO;
typedef struct _COORD { SHORT X, Y; } COORD;
typedef struct _SMALL_RECT { SHORT Left, Top, Right, Bottom; } SMALL_RECT;
typedef struct _CONSOLE_SCREEN_BUFFER_INFO {
    COORD dwSize, dwCursorPosition;
    WORD wAttributes;
    SMALL_RECT srWindow;
    COORD dwMaximumWindowSize;
} CONSOLE_SCREEN_BUFFER_INFO, *PCONSOLE_SCREEN_BUFFER_INFO;
typedef BOOL (WINAPI *PHANDLER_ROUTINE)(DWORD type);
#define FOREGROUND_BLUE      0x0001
#define FOREGROUND_GREEN     0x0002
#define FOREGROUND_RED       0x0004
#define FOREGROUND_INTENSITY 0x0008
#define BACKGROUND_BLUE      0x0010
#define BACKGROUND_GREEN     0x0020
#define BACKGROUND_RED       0x0040
#define BACKGROUND_INTENSITY 0x0080
#define ENABLE_VIRTUAL_TERMINAL_PROCESSING 0x0004

typedef struct _TIME_ZONE_INFORMATION {
    LONG Bias; WCHAR StandardName[32]; SYSTEMTIME StandardDate; LONG StandardBias;
    WCHAR DaylightName[32]; SYSTEMTIME DaylightDate; LONG DaylightBias;
} TIME_ZONE_INFORMATION, *LPTIME_ZONE_INFORMATION;
typedef struct _DYNAMIC_TIME_ZONE_INFORMATION {
    LONG Bias; WCHAR StandardName[32]; SYSTEMTIME StandardDate; LONG StandardBias;
    WCHAR DaylightName[32]; SYSTEMTIME DaylightDate; LONG DaylightBias;
    WCHAR TimeZoneKeyName[128]; BOOLEAN DynamicDaylightTimeDisabled;
} DYNAMIC_TIME_ZONE_INFORMATION;
#define TIME_ZONE_ID_UNKNOWN  0
#define TIME_ZONE_ID_STANDARD 1
#define TIME_ZONE_ID_DAYLIGHT 2
#define TIME_ZONE_ID_INVALID  ((DWORD)0xFFFFFFFF)

typedef struct _SLIST_ENTRY { struct _SLIST_ENTRY *Next; } SLIST_ENTRY, *PSLIST_ENTRY;
#ifdef _WIN64
typedef union __attribute__((aligned(16))) _SLIST_HEADER { struct { ULONGLONG Alignment, Region; }; } SLIST_HEADER, *PSLIST_HEADER;
#else   /* 8 bytes on x86: the first entry, then depth and sequence */
typedef union __attribute__((aligned(8))) _SLIST_HEADER {
    ULONGLONG Alignment;
    struct { SLIST_ENTRY Next; USHORT Depth; USHORT Sequence; };
} SLIST_HEADER, *PSLIST_HEADER;
#endif


/* completion ports, overlapped I/O */
WINBASEAPI HANDLE WINAPI CreateIoCompletionPort(HANDLE file, HANDLE port, ULONG_PTR key, DWORD threads);
WINBASEAPI BOOL   WINAPI GetQueuedCompletionStatus(HANDLE port, LPDWORD bytes, PULONG_PTR key, LPOVERLAPPED *ov, DWORD ms);
WINBASEAPI BOOL   WINAPI GetQueuedCompletionStatusEx(HANDLE port, LPOVERLAPPED_ENTRY e, ULONG n, PULONG got, DWORD ms, BOOL alertable);
WINBASEAPI BOOL   WINAPI Wow64DisableWow64FsRedirection(PVOID *old);
WINBASEAPI BOOL   WINAPI Wow64RevertWow64FsRedirection(PVOID old);
WINBASEAPI BOOL   WINAPI PostQueuedCompletionStatus(HANDLE port, DWORD bytes, ULONG_PTR key, LPOVERLAPPED ov);
WINBASEAPI BOOL   WINAPI GetOverlappedResult(HANDLE h, LPOVERLAPPED ov, LPDWORD bytes, BOOL wait);
WINBASEAPI BOOL   WINAPI CancelIo(HANDLE h);
WINBASEAPI BOOL   WINAPI CancelIoEx(HANDLE h, LPOVERLAPPED ov);
WINBASEAPI BOOL   WINAPI ReadFileEx(HANDLE h, LPVOID buf, DWORD n, LPOVERLAPPED ov, LPOVERLAPPED_COMPLETION_ROUTINE fn);
WINBASEAPI BOOL   WINAPI WriteFileEx(HANDLE h, LPCVOID buf, DWORD n, LPOVERLAPPED ov, LPOVERLAPPED_COMPLETION_ROUTINE fn);
WINBASEAPI DWORD  WINAPI SleepEx(DWORD ms, BOOL alertable);
WINBASEAPI BOOL   WINAPI SetFileCompletionNotificationModes(HANDLE h, UCHAR flags);
/* file mapping */
WINBASEAPI HANDLE WINAPI CreateFileMappingW(HANDLE file, LPSECURITY_ATTRIBUTES sa, DWORD protect, DWORD hi, DWORD lo, LPCWSTR name);
WINBASEAPI HANDLE WINAPI CreateFileMappingA(HANDLE file, LPSECURITY_ATTRIBUTES sa, DWORD protect, DWORD hi, DWORD lo, LPCSTR name);
WINBASEAPI LPVOID WINAPI MapViewOfFile(HANDLE map, DWORD access, DWORD hi, DWORD lo, SIZE_T n);
WINBASEAPI HANDLE WINAPI OpenFileMappingA(DWORD access, BOOL inherit, LPCSTR name);
WINBASEAPI HANDLE WINAPI OpenFileMappingW(DWORD access, BOOL inherit, LPCWSTR name);
WINBASEAPI LPVOID WINAPI MapViewOfFileEx(HANDLE map, DWORD access, DWORD hi, DWORD lo, SIZE_T n, LPVOID base);
WINBASEAPI BOOL   WINAPI UnmapViewOfFile(LPCVOID p);
WINBASEAPI BOOL   WINAPI FlushViewOfFile(LPCVOID p, SIZE_T n);
#define FILE_MAP_WRITE 0x0002
#define FILE_MAP_READ  0x0004
#define FILE_MAP_COPY  0x0001
#define FILE_MAP_ALL_ACCESS 0xF001F
#define SECTION_QUERY       0x0001
#define SEC_IMAGE           0x1000000
/* processes */
WINBASEAPI BOOL   WINAPI CreateProcessW(LPCWSTR app, LPWSTR cmd, LPSECURITY_ATTRIBUTES pa, LPSECURITY_ATTRIBUTES ta, BOOL inherit, DWORD flags, LPVOID env, LPCWSTR dir, LPSTARTUPINFOW si, LPPROCESS_INFORMATION pi);
WINBASEAPI BOOL   WINAPI CreateProcessA(LPCSTR app, LPSTR cmd, LPSECURITY_ATTRIBUTES pa, LPSECURITY_ATTRIBUTES ta, BOOL inherit, DWORD flags, LPVOID env, LPCSTR dir, LPSTARTUPINFOA si, LPPROCESS_INFORMATION pi);
WINBASEAPI HANDLE WINAPI OpenProcess(DWORD access, BOOL inherit, DWORD pid);
WINBASEAPI HANDLE WINAPI OpenThread(DWORD access, BOOL inherit, DWORD tid);
WINBASEAPI DWORD  WINAPI GetProcessId(HANDLE h);
WINBASEAPI BOOL   WINAPI InitializeProcThreadAttributeList(LPPROC_THREAD_ATTRIBUTE_LIST l, DWORD n, DWORD flags, PSIZE_T size);
WINBASEAPI BOOL   WINAPI UpdateProcThreadAttribute(LPPROC_THREAD_ATTRIBUTE_LIST l, DWORD flags, DWORD_PTR attr, PVOID v, SIZE_T n, PVOID prev, PSIZE_T ret);
WINBASEAPI VOID   WINAPI DeleteProcThreadAttributeList(LPPROC_THREAD_ATTRIBUTE_LIST l);
typedef struct _STARTUPINFOEXA { STARTUPINFOA StartupInfo; LPPROC_THREAD_ATTRIBUTE_LIST lpAttributeList; } STARTUPINFOEXA, *LPSTARTUPINFOEXA;
typedef struct _STARTUPINFOEXW { STARTUPINFOW StartupInfo; LPPROC_THREAD_ATTRIBUTE_LIST lpAttributeList; } STARTUPINFOEXW, *LPSTARTUPINFOEXW;
#define EXTENDED_STARTUPINFO_PRESENT          0x00080000
#define PROC_THREAD_ATTRIBUTE_PARENT_PROCESS  0x00020000
#define PROC_THREAD_ATTRIBUTE_HANDLE_LIST     0x00020002
WINBASEAPI VOID   WINAPI GetStartupInfoW(LPSTARTUPINFOW si);
WINBASEAPI BOOL   WINAPI GetProcessAffinityMask(HANDLE p, PDWORD_PTR proc, PDWORD_PTR sys);
WINBASEAPI BOOL   WINAPI SetProcessAffinityMask(HANDLE p, DWORD_PTR mask);
WINBASEAPI BOOL   WINAPI SetProcessPriorityBoost(HANDLE p, BOOL disable);
WINBASEAPI int    WINAPI GetThreadPriority(HANDLE t);
WINBASEAPI BOOL   WINAPI SetThreadPriority(HANDLE t, int prio);
WINBASEAPI BOOL   WINAPI GetProcessPriorityBoost(HANDLE p, BOOL *disabled);
WINBASEAPI BOOL   WINAPI SetThreadPriorityBoost(HANDLE t, BOOL disable);
WINBASEAPI BOOL   WINAPI GetThreadPriorityBoost(HANDLE t, BOOL *disabled);
WINBASEAPI DWORD  WINAPI GetPriorityClass(HANDLE p);
WINBASEAPI BOOL   WINAPI SetPriorityClass(HANDLE p, DWORD c);
WINBASEAPI BOOL   WINAPI Beep(DWORD freq, DWORD ms);
typedef struct _SYSTEM_POWER_STATUS {
    BYTE  ACLineStatus;              /* 0 offline, 1 online, 255 unknown */
    BYTE  BatteryFlag;               /* 1 high, 2 low, 4 critical, 8 charging, 128 none, 255 unknown */
    BYTE  BatteryLifePercent;        /* 0-100, 255 unknown */
    BYTE  SystemStatusFlag;          /* 1: battery saver on */
    DWORD BatteryLifeTime;           /* seconds, (DWORD)-1 unknown */
    DWORD BatteryFullLifeTime;
} SYSTEM_POWER_STATUS, *LPSYSTEM_POWER_STATUS;
WINBASEAPI BOOL   WINAPI GetSystemPowerStatus(LPSYSTEM_POWER_STATUS status);
WINBASEAPI BOOL   WINAPI SetThreadStackGuarantee(PULONG size);
WINBASEAPI UINT   WINAPI SetErrorMode(UINT mode);
WINBASEAPI UINT   WINAPI GetErrorMode(void);
WINBASEAPI BOOL   WINAPI IsProcessorFeaturePresent(DWORD f);
WINBASEAPI PVOID  WINAPI EncodePointer(PVOID p);
WINBASEAPI PVOID  WINAPI DecodePointer(PVOID p);
/* files and paths */
WINBASEAPI BOOL   WINAPI GetFileInformationByHandle(HANDLE h, LPBY_HANDLE_FILE_INFORMATION info);
WINBASEAPI BOOL   WINAPI GetFileTime(HANDLE h, LPFILETIME created, LPFILETIME accessed, LPFILETIME written);
WINBASEAPI BOOL   WINAPI SetFileTime(HANDLE h, const FILETIME *created, const FILETIME *accessed, const FILETIME *written);
WINBASEAPI BOOL   WINAPI GetFileInformationByHandleEx(HANDLE h, FILE_INFO_BY_HANDLE_CLASS c, LPVOID buf, DWORD n);
WINBASEAPI BOOL   WINAPI SetFileInformationByHandle(HANDLE h, FILE_INFO_BY_HANDLE_CLASS c, LPVOID buf, DWORD n);
WINBASEAPI DWORD  WINAPI GetFinalPathNameByHandleW(HANDLE h, LPWSTR buf, DWORD n, DWORD flags);
WINBASEAPI DWORD  WINAPI GetFinalPathNameByHandleA(HANDLE h, LPSTR buf, DWORD n, DWORD flags);
WINBASEAPI DWORD  WINAPI GetFullPathNameW(LPCWSTR name, DWORD n, LPWSTR buf, LPWSTR *part);
WINBASEAPI DWORD  WINAPI SearchPathW(LPCWSTR path, LPCWSTR file, LPCWSTR ext, DWORD n, LPWSTR buf, LPWSTR *part);
WINBASEAPI DWORD  WINAPI SearchPathA(LPCSTR path, LPCSTR file, LPCSTR ext, DWORD n, LPSTR buf, LPSTR *part);
WINBASEAPI BOOL   WINAPI GetFileAttributesExW(LPCWSTR name, GET_FILEEX_INFO_LEVELS l, LPVOID info);
WINBASEAPI BOOL   WINAPI GetFileAttributesExA(LPCSTR name, GET_FILEEX_INFO_LEVELS l, LPVOID info);
WINBASEAPI BOOL   WINAPI SetFileAttributesW(LPCWSTR name, DWORD attr);
WINBASEAPI BOOL   WINAPI SetFileAttributesA(LPCSTR name, DWORD attr);
WINBASEAPI HANDLE WINAPI FindFirstFileExW(LPCWSTR name, FINDEX_INFO_LEVELS l, LPVOID data, FINDEX_SEARCH_OPS op, LPVOID filter, DWORD flags);
WINBASEAPI BOOL   WINAPI MoveFileExW(LPCWSTR from, LPCWSTR to, DWORD flags);
WINBASEAPI BOOL   WINAPI MoveFileExA(LPCSTR from, LPCSTR to, DWORD flags);
WINBASEAPI BOOL   WINAPI CreateHardLinkA(LPCSTR link, LPCSTR target, LPSECURITY_ATTRIBUTES sa);
WINBASEAPI BOOL   WINAPI CreateHardLinkW(LPCWSTR link, LPCWSTR target, LPSECURITY_ATTRIBUTES sa);
WINBASEAPI BOOL   WINAPI MoveFileW(LPCWSTR from, LPCWSTR to);
WINBASEAPI BOOL   WINAPI MoveFileA(LPCSTR from, LPCSTR to);
WINBASEAPI BOOL   WINAPI CopyFileW(LPCWSTR from, LPCWSTR to, BOOL fail_if_exists);
WINBASEAPI BOOL   WINAPI CopyFileA(LPCSTR from, LPCSTR to, BOOL fail_if_exists);
WINBASEAPI BOOL   WINAPI RemoveDirectoryW(LPCWSTR name);
WINBASEAPI BOOL   WINAPI SetCurrentDirectoryW(LPCWSTR path);
WINBASEAPI UINT   WINAPI GetSystemDirectoryW(LPWSTR buf, UINT n);
WINBASEAPI UINT   WINAPI GetSystemDirectoryA(LPSTR buf, UINT n);
WINBASEAPI UINT   WINAPI GetWindowsDirectoryW(LPWSTR buf, UINT n);
WINBASEAPI UINT   WINAPI GetWindowsDirectoryA(LPSTR buf, UINT n);
WINBASEAPI DWORD  WINAPI GetTempPathW(DWORD n, LPWSTR buf);
WINBASEAPI DWORD  WINAPI GetTempPathA(DWORD n, LPSTR buf);
WINBASEAPI UINT   WINAPI GetTempFileNameW(LPCWSTR dir, LPCWSTR prefix, UINT unique, LPWSTR out);
WINBASEAPI UINT   WINAPI GetTempFileNameA(LPCSTR dir, LPCSTR prefix, UINT unique, LPSTR out);
WINBASEAPI DWORD  WINAPI GetLongPathNameW(LPCWSTR s, LPWSTR l, DWORD n);
WINBASEAPI DWORD  WINAPI GetShortPathNameW(LPCWSTR s, LPWSTR l, DWORD n);
WINBASEAPI BOOL   WINAPI GetHandleInformation(HANDLE h, LPDWORD flags);
WINBASEAPI BOOL   WINAPI SetHandleInformation(HANDLE h, DWORD mask, DWORD flags);
WINBASEAPI BOOL   WINAPI GetDiskFreeSpaceExW(LPCWSTR dir, PULARGE_INTEGER avail, PULARGE_INTEGER total, PULARGE_INTEGER free);
WINBASEAPI BOOL   WINAPI GetVolumeInformationW(LPCWSTR root, LPWSTR name, DWORD nn, LPDWORD serial, LPDWORD maxlen, LPDWORD flags, LPWSTR fs, DWORD nfs);
WINBASEAPI UINT   WINAPI GetDriveTypeW(LPCWSTR root);
WINBASEAPI DWORD  WINAPI GetLogicalDrives(void);
WINBASEAPI DWORD  WINAPI GetLogicalDriveStringsW(DWORD n, LPWSTR buf);
WINBASEAPI DWORD  WINAPI GetLogicalDriveStringsA(DWORD n, LPSTR buf);
WINBASEAPI BOOL   WINAPI AreFileApisANSI(void);
/* modules */
WINBASEAPI HMODULE WINAPI LoadLibraryExW(LPCWSTR name, HANDLE f, DWORD flags);
WINBASEAPI BOOL    WINAPI GetModuleHandleExW(DWORD flags, LPCWSTR name, HMODULE *out);
WINBASEAPI BOOL    WINAPI SetDllDirectoryW(LPCWSTR dir);
typedef PVOID DLL_DIRECTORY_COOKIE;
WINBASEAPI DLL_DIRECTORY_COOKIE WINAPI AddDllDirectory(LPCWSTR dir);
WINBASEAPI BOOL    WINAPI RemoveDllDirectory(DLL_DIRECTORY_COOKIE cookie);
WINBASEAPI BOOL    WINAPI SetDefaultDllDirectories(DWORD flags);
/* resources */
typedef HANDLE HRSRC;
WINBASEAPI HRSRC  WINAPI FindResourceW(HMODULE m, LPCWSTR name, LPCWSTR type);
WINBASEAPI HRSRC  WINAPI FindResourceA(HMODULE m, LPCSTR name, LPCSTR type);
WINBASEAPI HRSRC  WINAPI FindResourceExW(HMODULE m, LPCWSTR type, LPCWSTR name, WORD lang);
WINBASEAPI HGLOBAL WINAPI LoadResource(HMODULE m, HRSRC r);
WINBASEAPI LPVOID WINAPI LockResource(HGLOBAL h);
WINBASEAPI DWORD  WINAPI SizeofResource(HMODULE m, HRSRC r);
#define MAKEINTRESOURCEW(i) ((LPWSTR)(ULONG_PTR)(WORD)(i))
#define MAKEINTRESOURCEA(i) ((LPSTR)(ULONG_PTR)(WORD)(i))
#define MAKEINTRESOURCE MAKEINTRESOURCEA
/* global/local memory */
WINBASEAPI LPVOID  WINAPI GlobalLock(HGLOBAL h);
WINBASEAPI BOOL    WINAPI GlobalUnlock(HGLOBAL h);
WINBASEAPI SIZE_T  WINAPI GlobalSize(HGLOBAL h);
WINBASEAPI HGLOBAL WINAPI GlobalReAlloc(HGLOBAL h, SIZE_T n, UINT flags);
WINBASEAPI LPVOID  WINAPI LocalLock(HLOCAL h);
WINBASEAPI BOOL    WINAPI LocalUnlock(HLOCAL h);
WINBASEAPI SIZE_T  WINAPI LocalSize(HLOCAL h);
WINBASEAPI HLOCAL  WINAPI LocalReAlloc(HLOCAL h, SIZE_T n, UINT flags);
/* memory */
WINBASEAPI SIZE_T WINAPI VirtualQuery(LPCVOID p, PMEMORY_BASIC_INFORMATION mbi, SIZE_T n);
typedef struct _MEMORYSTATUSEX {
    DWORD dwLength, dwMemoryLoad;
    DWORDLONG ullTotalPhys, ullAvailPhys, ullTotalPageFile, ullAvailPageFile, ullTotalVirtual, ullAvailVirtual, ullAvailExtendedVirtual;
} MEMORYSTATUSEX, *LPMEMORYSTATUSEX;
WINBASEAPI BOOL   WINAPI GlobalMemoryStatusEx(LPMEMORYSTATUSEX ms);
/* thread context (another thread: it must be suspended) */
WINBASEAPI BOOL   WINAPI GetThreadContext(HANDLE t, LPCONTEXT c);
WINBASEAPI BOOL   WINAPI SetThreadContext(HANDLE t, const CONTEXT *c);
/* environment, system */
WINBASEAPI BOOL   WINAPI SetEnvironmentVariableW(LPCWSTR name, LPCWSTR value);
WINBASEAPI DWORD  WINAPI ExpandEnvironmentStringsW(LPCWSTR s, LPWSTR out, DWORD n);
WINBASEAPI DWORD  WINAPI ExpandEnvironmentStringsA(LPCSTR s, LPSTR out, DWORD n);
WINBASEAPI BOOL   WINAPI GetComputerNameW(LPWSTR buf, LPDWORD n);
WINBASEAPI BOOL   WINAPI GetComputerNameExW(int type, LPWSTR buf, LPDWORD n);
WINBASEAPI BOOL   WINAPI GetVersionExW(LPVOID vi);
WINBASEAPI DWORD  WINAPI FormatMessageA(DWORD flags, LPCVOID src, DWORD id, DWORD lang, LPSTR buf, DWORD n, va_list *args);
WINBASEAPI DWORD  WINAPI FormatMessageW(DWORD flags, LPCVOID src, DWORD id, DWORD lang, LPWSTR buf, DWORD n, va_list *args);
#define FORMAT_MESSAGE_ALLOCATE_BUFFER 0x00000100
#define FORMAT_MESSAGE_IGNORE_INSERTS  0x00000200
#define FORMAT_MESSAGE_FROM_STRING     0x00000400
#define FORMAT_MESSAGE_FROM_HMODULE    0x00000800
#define FORMAT_MESSAGE_FROM_SYSTEM     0x00001000
#define FORMAT_MESSAGE_ARGUMENT_ARRAY  0x00002000
#define FORMAT_MESSAGE_MAX_WIDTH_MASK  0x000000FF
/* lstr* (UTF-16) */
WINBASEAPI LPWSTR WINAPI lstrcpyW(LPWSTR d, LPCWSTR s);
WINBASEAPI LPWSTR WINAPI lstrcpynW(LPWSTR d, LPCWSTR s, int n);
WINBASEAPI LPSTR  WINAPI lstrcpynA(LPSTR d, LPCSTR s, int n);
WINBASEAPI LPWSTR WINAPI lstrcatW(LPWSTR d, LPCWSTR s);
WINBASEAPI LPSTR  WINAPI lstrcatA(LPSTR d, LPCSTR s);
WINBASEAPI int    WINAPI lstrcmpW(LPCWSTR a, LPCWSTR b);
WINBASEAPI int    WINAPI lstrcmpiW(LPCWSTR a, LPCWSTR b);
/* national language support */
WINBASEAPI BOOL   WINAPI GetCPInfo(UINT cp, LPCPINFO info);
WINBASEAPI UINT   WINAPI GetOEMCP(void);
WINBASEAPI BOOL   WINAPI IsValidCodePage(UINT cp);
WINBASEAPI BOOL   WINAPI IsDBCSLeadByte(BYTE c);
WINBASEAPI BOOL   WINAPI IsDBCSLeadByteEx(UINT cp, BYTE c);
WINBASEAPI int    WINAPI CompareStringW(DWORD lcid, DWORD flags, LPCWSTR a, int na, LPCWSTR b, int nb);
WINBASEAPI int    WINAPI CompareStringEx(LPCWSTR loc, DWORD flags, LPCWSTR a, int na, LPCWSTR b, int nb, LPVOID v, LPVOID r, LONG_PTR p);
WINBASEAPI int    WINAPI CompareStringOrdinal(LPCWSTR a, int na, LPCWSTR b, int nb, BOOL ignore_case);
WINBASEAPI int    WINAPI LCMapStringW(DWORD lcid, DWORD flags, LPCWSTR s, int n, LPWSTR out, int cap);
WINBASEAPI int    WINAPI LCMapStringEx(LPCWSTR loc, DWORD flags, LPCWSTR s, int n, LPWSTR out, int cap, LPVOID v, LPVOID r, LONG_PTR p);
WINBASEAPI BOOL   WINAPI GetStringTypeW(DWORD type, LPCWSTR s, int n, LPWORD out);
WINBASEAPI DWORD  WINAPI GetUserDefaultLCID(void);
WINBASEAPI DWORD  WINAPI GetThreadLocale(void);
WINBASEAPI WORD   WINAPI GetUserDefaultLangID(void);
WINBASEAPI WORD   WINAPI GetUserDefaultUILanguage(void);
WINBASEAPI int    WINAPI GetUserDefaultLocaleName(LPWSTR name, int n);
WINBASEAPI int    WINAPI GetLocaleInfoW(DWORD lcid, DWORD type, LPWSTR buf, int n);
WINBASEAPI int    WINAPI GetLocaleInfoEx(LPCWSTR loc, DWORD type, LPWSTR buf, int n);
WINBASEAPI DWORD  WINAPI GetSystemDefaultLCID(void);
WINBASEAPI DWORD  WINAPI LocaleNameToLCID(LPCWSTR name, DWORD flags);
WINBASEAPI int    WINAPI ResolveLocaleName(LPCWSTR name, LPWSTR out, int cap);
typedef struct { UINT NumDigits, LeadingZero, Grouping; LPSTR lpDecimalSep, lpThousandSep; UINT NegativeOrder; } NUMBERFMTA;
typedef struct { UINT NumDigits, LeadingZero, Grouping; LPWSTR lpDecimalSep, lpThousandSep; UINT NegativeOrder; } NUMBERFMTW;
typedef struct { UINT NumDigits, LeadingZero, Grouping; LPSTR lpDecimalSep, lpThousandSep; UINT NegativeOrder, PositiveOrder;
                 LPSTR lpCurrencySymbol; } CURRENCYFMTA;
typedef struct { UINT NumDigits, LeadingZero, Grouping; LPWSTR lpDecimalSep, lpThousandSep; UINT NegativeOrder, PositiveOrder;
                 LPWSTR lpCurrencySymbol; } CURRENCYFMTW;
WINBASEAPI int    WINAPI GetDateFormatA(DWORD lcid, DWORD flags, const SYSTEMTIME *st, LPCSTR fmt, LPSTR out, int n);
WINBASEAPI int    WINAPI GetDateFormatW(DWORD lcid, DWORD flags, const SYSTEMTIME *st, LPCWSTR fmt, LPWSTR out, int n);
WINBASEAPI int    WINAPI GetDateFormatEx(LPCWSTR loc, DWORD flags, const SYSTEMTIME *st, LPCWSTR fmt, LPWSTR out, int n, LPCWSTR cal);
WINBASEAPI int    WINAPI GetTimeFormatA(DWORD lcid, DWORD flags, const SYSTEMTIME *st, LPCSTR fmt, LPSTR out, int n);
WINBASEAPI int    WINAPI GetTimeFormatW(DWORD lcid, DWORD flags, const SYSTEMTIME *st, LPCWSTR fmt, LPWSTR out, int n);
WINBASEAPI int    WINAPI GetTimeFormatEx(LPCWSTR loc, DWORD flags, const SYSTEMTIME *st, LPCWSTR fmt, LPWSTR out, int n);
WINBASEAPI int    WINAPI GetNumberFormatA(DWORD lcid, DWORD flags, LPCSTR v, const NUMBERFMTA *f, LPSTR out, int n);
WINBASEAPI int    WINAPI GetNumberFormatW(DWORD lcid, DWORD flags, LPCWSTR v, const NUMBERFMTW *f, LPWSTR out, int n);
WINBASEAPI int    WINAPI GetNumberFormatEx(LPCWSTR loc, DWORD flags, LPCWSTR v, const NUMBERFMTW *f, LPWSTR out, int n);
WINBASEAPI int    WINAPI GetCurrencyFormatA(DWORD lcid, DWORD flags, LPCSTR v, const CURRENCYFMTA *f, LPSTR out, int n);
WINBASEAPI int    WINAPI GetCurrencyFormatW(DWORD lcid, DWORD flags, LPCWSTR v, const CURRENCYFMTW *f, LPWSTR out, int n);
WINBASEAPI int    WINAPI GetCurrencyFormatEx(LPCWSTR loc, DWORD flags, LPCWSTR v, const CURRENCYFMTW *f, LPWSTR out, int n);
#define DATE_SHORTDATE      0x01
#define DATE_LONGDATE       0x02
#define DATE_USE_ALT_CALENDAR 0x04
#define DATE_YEARMONTH      0x08
#define DATE_MONTHDAY       0x80
#define TIME_NOMINUTESORSECONDS 0x1
#define TIME_NOSECONDS      0x2
#define TIME_NOTIMEMARKER   0x4
#define TIME_FORCE24HOURFORMAT 0x8
#ifndef LOCALE_NAME_MAX_LENGTH
#define LOCALE_NAME_MAX_LENGTH 85
#endif
#define LOCALE_NOUSEROVERRIDE 0x80000000
#define LOCALE_ILANGUAGE    0x01
#define LOCALE_SABBREVLANGNAME 0x03
#define LOCALE_ICOUNTRY     0x05
#define LOCALE_SLIST        0x0C
#define LOCALE_IMEASURE     0x0D
#define LOCALE_SDECIMAL     0x0E
#define LOCALE_STHOUSAND    0x0F
#define LOCALE_SGROUPING    0x10
#define LOCALE_IDIGITS      0x11
#define LOCALE_ILZERO       0x12
#define LOCALE_SNATIVEDIGITS 0x13
#define LOCALE_SCURRENCY    0x14
#define LOCALE_SMONDECIMALSEP 0x16
#define LOCALE_SMONTHOUSANDSEP 0x17
#define LOCALE_SMONGROUPING 0x18
#define LOCALE_ICURRDIGITS  0x19
#define LOCALE_ICURRENCY    0x1B
#define LOCALE_INEGCURR     0x1C
#define LOCALE_SDATE        0x1D
#define LOCALE_STIME        0x1E
#define LOCALE_SSHORTDATE   0x1F
#define LOCALE_SLONGDATE    0x20
#define LOCALE_IDATE        0x21
#define LOCALE_ITIME        0x23
#define LOCALE_ITLZERO      0x25
#define LOCALE_S1159        0x28
#define LOCALE_S2359        0x29
#define LOCALE_SPOSITIVESIGN 0x50
#define LOCALE_SNEGATIVESIGN 0x51
#define LOCALE_SNAME        0x5C
#define LOCALE_SENGLISHDISPLAYNAME 0x72
#define LOCALE_SSHORTTIME   0x79
#define LOCALE_STIMEFORMAT  0x1003
#define LOCALE_IDIGITSUBSTITUTION 0x1014
#define LOCALE_SENGCOUNTRY  0x1002
#define LOCALE_SYEARMONTH   0x1006
#define LOCALE_ICALENDARTYPE 0x1009
#define LOCALE_IPAPERSIZE   0x100A
#define LOCALE_IFIRSTDAYOFWEEK 0x100C
#define LOCALE_IFIRSTWEEKOFYEAR 0x100D
#define LOCALE_INEGNUMBER   0x1010
#define LOCALE_SDURATION    0x5D
#define LOCALE_ITIMEMARKPOSN 0x1005
#define LOCALE_IOPTIONALCALENDAR 0x100B
#define LOCALE_SMONTHNAME1  0x38
#define LOCALE_RETURN_NUMBER 0x20000000
/* durations, overrides and calendars */
typedef DWORD CALID;
typedef DWORD CALTYPE;
WINBASEAPI int    WINAPI GetDurationFormat(DWORD lcid, DWORD flags, const SYSTEMTIME *d, ULONGLONG ticks, LPCWSTR fmt, LPWSTR out, int n);
WINBASEAPI int    WINAPI GetDurationFormatEx(LPCWSTR loc, DWORD flags, const SYSTEMTIME *d, ULONGLONG ticks, LPCWSTR fmt, LPWSTR out, int n);
WINBASEAPI BOOL   WINAPI SetLocaleInfoW(DWORD lcid, DWORD type, LPCWSTR v);
WINBASEAPI BOOL   WINAPI SetLocaleInfoA(DWORD lcid, DWORD type, LPCSTR v);
WINBASEAPI int    WINAPI GetCalendarInfoW(DWORD lcid, CALID cal, CALTYPE type, LPWSTR out, int n, LPDWORD value);
WINBASEAPI int    WINAPI GetCalendarInfoA(DWORD lcid, CALID cal, CALTYPE type, LPSTR out, int n, LPDWORD value);
WINBASEAPI int    WINAPI GetCalendarInfoEx(LPCWSTR loc, CALID cal, LPCWSTR reserved, CALTYPE type, LPWSTR out, int n, LPDWORD value);
WINBASEAPI BOOL   WINAPI SetCalendarInfoW(DWORD lcid, CALID cal, CALTYPE type, LPCWSTR v);
typedef BOOL (CALLBACK *CALINFO_ENUMPROCW)(LPWSTR);
typedef BOOL (CALLBACK *CALINFO_ENUMPROCEXW)(LPWSTR, CALID);
typedef BOOL (CALLBACK *CALINFO_ENUMPROCEXEX)(LPWSTR, CALID, LPWSTR, LPARAM);
typedef BOOL (CALLBACK *DATEFMT_ENUMPROCW)(LPWSTR);
typedef BOOL (CALLBACK *DATEFMT_ENUMPROCEXW)(LPWSTR, CALID);
typedef BOOL (CALLBACK *DATEFMT_ENUMPROCEXEX)(LPWSTR, CALID, LPARAM);
typedef BOOL (CALLBACK *TIMEFMT_ENUMPROCW)(LPWSTR);
typedef BOOL (CALLBACK *TIMEFMT_ENUMPROCEX)(LPWSTR, LPARAM);
WINBASEAPI BOOL   WINAPI EnumCalendarInfoW(CALINFO_ENUMPROCW fn, DWORD lcid, CALID cal, CALTYPE type);
WINBASEAPI BOOL   WINAPI EnumCalendarInfoExW(CALINFO_ENUMPROCEXW fn, DWORD lcid, CALID cal, CALTYPE type);
WINBASEAPI BOOL   WINAPI EnumCalendarInfoExEx(CALINFO_ENUMPROCEXEX fn, LPCWSTR loc, CALID cal, LPCWSTR reserved, CALTYPE type, LPARAM p);
WINBASEAPI BOOL   WINAPI EnumDateFormatsW(DATEFMT_ENUMPROCW fn, DWORD lcid, DWORD flags);
WINBASEAPI BOOL   WINAPI EnumDateFormatsExW(DATEFMT_ENUMPROCEXW fn, DWORD lcid, DWORD flags);
WINBASEAPI BOOL   WINAPI EnumDateFormatsExEx(DATEFMT_ENUMPROCEXEX fn, LPCWSTR loc, DWORD flags, LPARAM p);
WINBASEAPI BOOL   WINAPI EnumTimeFormatsW(TIMEFMT_ENUMPROCW fn, DWORD lcid, DWORD flags);
WINBASEAPI BOOL   WINAPI EnumTimeFormatsEx(TIMEFMT_ENUMPROCEX fn, LPCWSTR loc, DWORD flags, LPARAM p);
#define ENUM_ALL_CALENDARS 0xFFFFFFFF
#define CAL_NOUSEROVERRIDE  0x80000000
#define CAL_RETURN_NUMBER   0x20000000
#define CAL_RETURN_GENITIVE_NAMES 0x10000000
#define CAL_ICALINTVALUE    0x01
#define CAL_SCALNAME        0x02
#define CAL_IYEAROFFSETRANGE 0x03
#define CAL_SERASTRING      0x04
#define CAL_SSHORTDATE      0x05
#define CAL_SLONGDATE       0x06
#define CAL_SDAYNAME1       0x07
#define CAL_SABBREVDAYNAME1 0x0E
#define CAL_SMONTHNAME1     0x15
#define CAL_SMONTHNAME9     0x1D
#define CAL_SMONTHNAME13    0x21
#define CAL_SABBREVMONTHNAME1 0x22
#define CAL_SYEARMONTH      0x2F
#define CAL_ITWODIGITYEARMAX 0x30
#define CAL_SSHORTESTDAYNAME1 0x31
#define CAL_SMONTHDAY       0x38
#define CAL_SABBREVERASTRING 0x39
#define CAL_SENGLISHERANAME 0x3B
#define CAL_SENGLISHABBREVERANAME 0x3C
#define CAL_SJAPANESEERAFIRSTYEAR 0x3D
#define CAL_GREGORIAN       1
#define CAL_GREGORIAN_US    2
#define CAL_JAPAN           3
#define CAL_TAIWAN          4
#define CAL_KOREA           5
#define CAL_HIJRI           6
#define CAL_THAI            7
#define CAL_HEBREW          8
#define CAL_GREGORIAN_ME_FRENCH 9
#define CAL_GREGORIAN_ARABIC 10
#define CAL_PERSIAN         22
#define CAL_UMALQURA        23
#define ERROR_INVALID_FLAGS 1004
#define CSTR_LESS_THAN    1
#define CSTR_EQUAL        2
#define CSTR_GREATER_THAN 3
#define NORM_IGNORECASE   0x00000001
#ifndef LOCALE_USER_DEFAULT
#define LOCALE_USER_DEFAULT 0x0400
#define LOCALE_SYSTEM_DEFAULT 0x0800
#endif
#define LCMAP_LOWERCASE   0x00000100
#define LCMAP_UPPERCASE   0x00000200
#define CT_CTYPE1 1
#define CT_CTYPE2 2
#define CT_CTYPE3 4
/* console */
WINBASEAPI BOOL   WINAPI GetConsoleScreenBufferInfo(HANDLE h, PCONSOLE_SCREEN_BUFFER_INFO info);
WINBASEAPI BOOL   WINAPI SetConsoleTextAttribute(HANDLE h, WORD attr);
WINBASEAPI BOOL   WINAPI SetConsoleCtrlHandler(PHANDLER_ROUTINE fn, BOOL add);
WINBASEAPI BOOL   WINAPI ReadConsoleW(HANDLE h, LPVOID buf, DWORD n, LPDWORD read, LPVOID c);
WINBASEAPI BOOL   WINAPI SetConsoleCP(UINT cp);
WINBASEAPI BOOL   WINAPI SetConsoleTitleW(LPCWSTR t);
WINBASEAPI BOOL   WINAPI FlushConsoleInputBuffer(HANDLE h);
WINBASEAPI BOOL   WINAPI GetNumberOfConsoleInputEvents(HANDLE h, LPDWORD n);
WINBASEAPI BOOL   WINAPI AllocConsole(void);
WINBASEAPI BOOL   WINAPI FreeConsole(void);
WINBASEAPI BOOL   WINAPI AttachConsole(DWORD pid);
WINBASEAPI HANDLE WINAPI GetConsoleWindow(void);
WINBASEAPI DWORD  WINAPI GetConsoleProcessList(LPDWORD list, DWORD n);
/* time */
WINBASEAPI DWORD  WINAPI GetTimeZoneInformation(LPTIME_ZONE_INFORMATION tz);
WINBASEAPI BOOL   WINAPI GetTimeZoneInformationForYear(USHORT year, DYNAMIC_TIME_ZONE_INFORMATION *d, LPTIME_ZONE_INFORMATION tz);
WINBASEAPI DWORD  WINAPI GetDynamicTimeZoneInformation(DYNAMIC_TIME_ZONE_INFORMATION *d);
WINBASEAPI BOOL   WINAPI SystemTimeToTzSpecificLocalTime(const TIME_ZONE_INFORMATION *tz, const SYSTEMTIME *u, LPSYSTEMTIME l);
WINBASEAPI BOOL   WINAPI FileTimeToLocalFileTime(const FILETIME *u, LPFILETIME l);
WINBASEAPI BOOL   WINAPI TzSpecificLocalTimeToSystemTime(const TIME_ZONE_INFORMATION *tz, const SYSTEMTIME *l, LPSYSTEMTIME u);
WINBASEAPI BOOL   WINAPI SetTimeZoneInformation(const TIME_ZONE_INFORMATION *tz);
WINBASEAPI BOOL   WINAPI SetDynamicTimeZoneInformation(const DYNAMIC_TIME_ZONE_INFORMATION *d);
WINBASEAPI DWORD  WINAPI EnumDynamicTimeZoneInformation(DWORD i, DYNAMIC_TIME_ZONE_INFORMATION *d);
WINBASEAPI BOOL   WINAPI LocalFileTimeToFileTime(const FILETIME *l, LPFILETIME u);
WINBASEAPI VOID   WINAPI GetSystemTimePreciseAsFileTime(LPFILETIME ft);
WINBASEAPI HANDLE WINAPI CreateWaitableTimerExW(LPSECURITY_ATTRIBUTES sa, LPCWSTR name, DWORD flags, DWORD access);
WINBASEAPI HANDLE WINAPI CreateWaitableTimerW(LPSECURITY_ATTRIBUTES sa, BOOL manual, LPCWSTR name);
WINBASEAPI BOOL   WINAPI SetWaitableTimer(HANDLE t, const LARGE_INTEGER *due, LONG period, LPVOID fn, LPVOID arg, BOOL resume);
WINBASEAPI BOOL   WINAPI CancelWaitableTimer(HANDLE t);
WINBASEAPI HANDLE WINAPI CreateWaitableTimerA(LPSECURITY_ATTRIBUTES sa, BOOL manual, LPCSTR name);
WINBASEAPI HANDLE WINAPI OpenWaitableTimerW(DWORD access, BOOL inherit, LPCWSTR name);
WINBASEAPI HANDLE WINAPI OpenWaitableTimerA(DWORD access, BOOL inherit, LPCSTR name);
/* timer queues */
typedef VOID (CALLBACK *WAITORTIMERCALLBACK)(PVOID param, BOOLEAN timer_fired);
#define WT_EXECUTEONLYONCE 0x00000008
WINBASEAPI HANDLE WINAPI CreateTimerQueue(void);
WINBASEAPI BOOL   WINAPI CreateTimerQueueTimer(PHANDLE timer, HANDLE queue, WAITORTIMERCALLBACK fn, PVOID param,
                                               DWORD due, DWORD period, ULONG flags);
WINBASEAPI BOOL   WINAPI ChangeTimerQueueTimer(HANDLE queue, HANDLE timer, ULONG due, ULONG period);
WINBASEAPI BOOL   WINAPI DeleteTimerQueueTimer(HANDLE queue, HANDLE timer, HANDLE completion);
WINBASEAPI BOOL   WINAPI DeleteTimerQueueEx(HANDLE queue, HANDLE completion);
WINBASEAPI BOOL   WINAPI DeleteTimerQueue(HANDLE queue);
/* wait on address */
WINBASEAPI BOOL   WINAPI WaitOnAddress(volatile VOID *addr, PVOID cmp, SIZE_T size, DWORD ms);
WINBASEAPI BOOL   WINAPI CompareObjectHandles(HANDLE first, HANDLE second);
WINBASEAPI VOID   WINAPI WakeByAddressSingle(PVOID addr);
WINBASEAPI VOID   WINAPI WakeByAddressAll(PVOID addr);
/* interlocked singly linked lists */
WINBASEAPI VOID         WINAPI InitializeSListHead(PSLIST_HEADER h);
WINBASEAPI PSLIST_ENTRY WINAPI InterlockedPushEntrySList(PSLIST_HEADER h, PSLIST_ENTRY e);
WINBASEAPI PSLIST_ENTRY WINAPI InterlockedPopEntrySList(PSLIST_HEADER h);
WINBASEAPI PSLIST_ENTRY WINAPI InterlockedFlushSList(PSLIST_HEADER h);
WINBASEAPI USHORT       WINAPI QueryDepthSList(PSLIST_HEADER h);
/* pipes */
#define PIPE_ACCESS_INBOUND            0x00000001
#define PIPE_ACCESS_OUTBOUND           0x00000002
#define PIPE_ACCESS_DUPLEX             0x00000003
#define PIPE_CLIENT_END                0x00000000
#define PIPE_SERVER_END                0x00000001
#define PIPE_WAIT                      0x00000000
#define PIPE_NOWAIT                    0x00000001
#define PIPE_READMODE_BYTE             0x00000000
#define PIPE_READMODE_MESSAGE          0x00000002
#define PIPE_TYPE_BYTE                 0x00000000
#define PIPE_TYPE_MESSAGE              0x00000004
#define PIPE_ACCEPT_REMOTE_CLIENTS     0x00000000
#define PIPE_REJECT_REMOTE_CLIENTS     0x00000008
#define PIPE_UNLIMITED_INSTANCES       255
#define FILE_FLAG_FIRST_PIPE_INSTANCE  0x00080000
#define NMPWAIT_WAIT_FOREVER           0xFFFFFFFF
#define NMPWAIT_NOWAIT                 0x00000001
#define NMPWAIT_USE_DEFAULT_WAIT       0x00000000
#define HANDLE_FLAG_INHERIT            0x00000001
#define HANDLE_FLAG_PROTECT_FROM_CLOSE 0x00000002
WINBASEAPI HANDLE WINAPI CreateNamedPipeA(LPCSTR name, DWORD mode, DWORD pmode, DWORD max, DWORD out, DWORD in, DWORD ms, LPSECURITY_ATTRIBUTES sa);
WINBASEAPI HANDLE WINAPI CreateNamedPipeW(LPCWSTR name, DWORD mode, DWORD pmode, DWORD max, DWORD out, DWORD in, DWORD ms, LPSECURITY_ATTRIBUTES sa);
WINBASEAPI BOOL   WINAPI CreatePipe(PHANDLE r, PHANDLE w, LPSECURITY_ATTRIBUTES sa, DWORD size);
WINBASEAPI BOOL   WINAPI PeekNamedPipe(HANDLE h, LPVOID buf, DWORD n, LPDWORD read, LPDWORD avail, LPDWORD left);
WINBASEAPI BOOL   WINAPI ConnectNamedPipe(HANDLE h, LPOVERLAPPED ov);
WINBASEAPI BOOL   WINAPI DisconnectNamedPipe(HANDLE h);
WINBASEAPI BOOL   WINAPI WaitNamedPipeA(LPCSTR name, DWORD ms);
WINBASEAPI BOOL   WINAPI WaitNamedPipeW(LPCWSTR name, DWORD ms);
WINBASEAPI BOOL   WINAPI TransactNamedPipe(HANDLE h, LPVOID in, DWORD in_len, LPVOID out, DWORD out_len, LPDWORD read, LPOVERLAPPED ov);
WINBASEAPI BOOL   WINAPI CallNamedPipeA(LPCSTR name, LPVOID in, DWORD in_len, LPVOID out, DWORD out_len, LPDWORD read, DWORD ms);
WINBASEAPI BOOL   WINAPI CallNamedPipeW(LPCWSTR name, LPVOID in, DWORD in_len, LPVOID out, DWORD out_len, LPDWORD read, DWORD ms);
WINBASEAPI BOOL   WINAPI GetNamedPipeInfo(HANDLE h, LPDWORD flags, LPDWORD out, LPDWORD in, LPDWORD max);
WINBASEAPI BOOL   WINAPI GetNamedPipeHandleStateA(HANDLE h, LPDWORD state, LPDWORD inst, LPDWORD count, LPDWORD ms, LPSTR user, DWORD user_len);
WINBASEAPI BOOL   WINAPI GetNamedPipeHandleStateW(HANDLE h, LPDWORD state, LPDWORD inst, LPDWORD count, LPDWORD ms, LPWSTR user, DWORD user_len);
WINBASEAPI BOOL   WINAPI SetNamedPipeHandleState(HANDLE h, LPDWORD mode, LPDWORD count, LPDWORD ms);
WINBASEAPI BOOL   WINAPI GetNamedPipeClientProcessId(HANDLE h, PULONG pid);
WINBASEAPI BOOL   WINAPI GetNamedPipeServerProcessId(HANDLE h, PULONG pid);
WINBASEAPI BOOL   WINAPI GetNamedPipeClientSessionId(HANDLE h, PULONG id);
WINBASEAPI BOOL   WINAPI GetNamedPipeServerSessionId(HANDLE h, PULONG id);
WINBASEAPI BOOL   WINAPI SetHandleInformation(HANDLE h, DWORD mask, DWORD flags);
WINBASEAPI BOOL   WINAPI GetHandleInformation(HANDLE h, LPDWORD flags);
WINBASEAPI BOOL   WINAPI CancelIo(HANDLE h);
WINBASEAPI BOOL   WINAPI CancelIoEx(HANDLE h, LPOVERLAPPED ov);
WINBASEAPI BOOL   WINAPI GetOverlappedResultEx(HANDLE h, LPOVERLAPPED ov, LPDWORD bytes, DWORD ms, BOOL alertable);
#define ERROR_IO_PENDING           997
#define ERROR_IO_INCOMPLETE        996
#define ERROR_OPERATION_ABORTED    995
#define ERROR_BROKEN_PIPE          109
#define ERROR_BAD_PIPE             230
#define ERROR_PIPE_BUSY            231
#define ERROR_NO_DATA              232
#define ERROR_PIPE_NOT_CONNECTED   233
#define ERROR_PIPE_CONNECTED       535
#define ERROR_PIPE_LISTENING       536
#define ERROR_SEM_TIMEOUT          121
#define ERROR_NOT_FOUND            1168
#define ERROR_BAD_LENGTH           24
#define ERROR_BUFFER_OVERFLOW      111
#define ERROR_NEGATIVE_SEEK        131
#define ERROR_DIRECTORY            267
#define ERROR_ABANDONED_WAIT_0     735
#define WAIT_IO_COMPLETION         0x000000C0

WINBASEAPI int WINAPI MulDiv(int a, int b, int c);
WINBASEAPI WORD WINAPI GlobalAddAtomW(LPCWSTR s);
WINBASEAPI WORD WINAPI GlobalFindAtomW(LPCWSTR s);
WINBASEAPI UINT WINAPI GlobalGetAtomNameW(WORD a, LPWSTR buf, int n);
WINBASEAPI WORD WINAPI GlobalDeleteAtom(WORD a);
#define LOAD_LIBRARY_AS_DATAFILE 0x00000002
#define ERROR_TIMEOUT 1460
#define ERROR_NO_SYSTEM_RESOURCES 1450
#define ERROR_NOT_ENOUGH_QUOTA 1816
#define ERROR_INVALID_WINDOW_HANDLE 1400
#define ERROR_INVALID_MENU_HANDLE 1401
#define ERROR_CANNOT_FIND_WND_CLASS 1407
#define ERROR_INVALID_THREAD_ID 1444
#define ERROR_CONTROL_ID_NOT_FOUND 1421
#define ERROR_MENU_ITEM_NOT_FOUND 1456
#define ERROR_RESOURCE_NAME_NOT_FOUND 1814
#define ERROR_RESOURCE_TYPE_NOT_FOUND 1813

