/* winhttp.h — Windows' HTTP client API (userland/winhttp) */
#pragma once
#include <windows.h>

#ifndef WINHTTPAPI
#define WINHTTPAPI __declspec(dllimport)
#endif

typedef LPVOID HINTERNET, *LPHINTERNET;
typedef WORD INTERNET_PORT;
typedef int INTERNET_SCHEME;

#define INTERNET_DEFAULT_PORT        0
#define INTERNET_DEFAULT_HTTP_PORT   80
#define INTERNET_DEFAULT_HTTPS_PORT  443
#define INTERNET_SCHEME_HTTP         1
#define INTERNET_SCHEME_HTTPS        2

#define WINHTTP_ACCESS_TYPE_DEFAULT_PROXY   0
#define WINHTTP_ACCESS_TYPE_NO_PROXY        1
#define WINHTTP_ACCESS_TYPE_NAMED_PROXY     3
#define WINHTTP_ACCESS_TYPE_AUTOMATIC_PROXY 4
#define WINHTTP_NO_PROXY_NAME     NULL
#define WINHTTP_NO_PROXY_BYPASS   NULL
#define WINHTTP_NO_REFERER        NULL
#define WINHTTP_DEFAULT_ACCEPT_TYPES NULL
#define WINHTTP_NO_ADDITIONAL_HEADERS NULL
#define WINHTTP_NO_REQUEST_DATA   NULL
#define WINHTTP_HEADER_NAME_BY_INDEX NULL
#define WINHTTP_NO_OUTPUT_BUFFER  NULL
#define WINHTTP_NO_HEADER_INDEX   NULL

#define WINHTTP_FLAG_ASYNC            0x10000000
#define WINHTTP_FLAG_SECURE           0x00800000
#define WINHTTP_FLAG_ESCAPE_PERCENT   0x00000004
#define WINHTTP_FLAG_NULL_CODEPAGE    0x00000008
#define WINHTTP_FLAG_ESCAPE_DISABLE   0x00000040
#define WINHTTP_FLAG_BYPASS_PROXY_CACHE 0x00000100
#define WINHTTP_FLAG_REFRESH          WINHTTP_FLAG_BYPASS_PROXY_CACHE

#define WINHTTP_ADDREQ_FLAG_ADD_IF_NEW 0x10000000
#define WINHTTP_ADDREQ_FLAG_ADD        0x20000000
#define WINHTTP_ADDREQ_FLAG_COALESCE   0x40000000
#define WINHTTP_ADDREQ_FLAG_REPLACE    0x80000000

/* options */
#define WINHTTP_OPTION_CALLBACK                1
#define WINHTTP_OPTION_RESOLVE_TIMEOUT         2
#define WINHTTP_OPTION_CONNECT_TIMEOUT         3
#define WINHTTP_OPTION_CONNECT_RETRIES         4
#define WINHTTP_OPTION_SEND_TIMEOUT            5
#define WINHTTP_OPTION_RECEIVE_TIMEOUT         6
#define WINHTTP_OPTION_RECEIVE_RESPONSE_TIMEOUT 7
#define WINHTTP_OPTION_HANDLE_TYPE             9
#define WINHTTP_OPTION_PARENT_HANDLE           21
#define WINHTTP_OPTION_SECURITY_FLAGS          31
#define WINHTTP_OPTION_URL                     34
#define WINHTTP_OPTION_SECURITY_KEY_BITNESS    36
#define WINHTTP_OPTION_PROXY                   38
#define WINHTTP_OPTION_USER_AGENT              41
#define WINHTTP_OPTION_CONTEXT_VALUE           45
#define WINHTTP_OPTION_DISABLE_FEATURE         63
#define WINHTTP_OPTION_ENABLE_FEATURE          79
#define WINHTTP_OPTION_SECURE_PROTOCOLS        84
#define WINHTTP_OPTION_REDIRECT_POLICY         88
#define WINHTTP_OPTION_MAX_HTTP_AUTOMATIC_REDIRECTS 89
#define WINHTTP_OPTION_DECOMPRESSION           118
#define WINHTTP_OPTION_ENABLE_HTTP_PROTOCOL    133
#define WINHTTP_OPTION_HTTP_PROTOCOL_USED      134

#define WINHTTP_PROTOCOL_FLAG_HTTP2   0x1
#define WINHTTP_PROTOCOL_FLAG_HTTP3   0x2

#define WINHTTP_HANDLE_TYPE_SESSION   1
#define WINHTTP_HANDLE_TYPE_CONNECT   2
#define WINHTTP_HANDLE_TYPE_REQUEST   3

#define WINHTTP_DISABLE_COOKIES       0x00000001
#define WINHTTP_DISABLE_REDIRECTS     0x00000002
#define WINHTTP_DISABLE_AUTHENTICATION 0x00000004
#define WINHTTP_DISABLE_KEEP_ALIVE    0x00000008

#define WINHTTP_OPTION_REDIRECT_POLICY_NEVER                  0
#define WINHTTP_OPTION_REDIRECT_POLICY_DISALLOW_HTTPS_TO_HTTP 1
#define WINHTTP_OPTION_REDIRECT_POLICY_ALWAYS                 2

#define SECURITY_FLAG_SECURE                   0x00000001
#define SECURITY_FLAG_STRENGTH_STRONG          0x20000000
#define SECURITY_FLAG_IGNORE_UNKNOWN_CA        0x00000100
#define SECURITY_FLAG_IGNORE_CERT_WRONG_USAGE  0x00000200
#define SECURITY_FLAG_IGNORE_CERT_CN_INVALID   0x00001000
#define SECURITY_FLAG_IGNORE_CERT_DATE_INVALID 0x00002000

#define WINHTTP_FLAG_SECURE_PROTOCOL_TLS1_2    0x00000800
#define WINHTTP_FLAG_SECURE_PROTOCOL_TLS1_3    0x00002000

/* header queries */
#define WINHTTP_QUERY_CONTENT_TYPE        1
#define WINHTTP_QUERY_CONTENT_LENGTH      5
#define WINHTTP_QUERY_DATE                9
#define WINHTTP_QUERY_LAST_MODIFIED       11
#define WINHTTP_QUERY_VERSION             18
#define WINHTTP_QUERY_STATUS_CODE         19
#define WINHTTP_QUERY_STATUS_TEXT         20
#define WINHTTP_QUERY_RAW_HEADERS         21
#define WINHTTP_QUERY_RAW_HEADERS_CRLF    22
#define WINHTTP_QUERY_CONNECTION          23
#define WINHTTP_QUERY_CONTENT_ENCODING    29
#define WINHTTP_QUERY_LOCATION            33
#define WINHTTP_QUERY_SERVER              37
#define WINHTTP_QUERY_WWW_AUTHENTICATE    40
#define WINHTTP_QUERY_SET_COOKIE          43
#define WINHTTP_QUERY_ETAG                54
#define WINHTTP_QUERY_TRANSFER_ENCODING   63
#define WINHTTP_QUERY_CUSTOM              65535
#define WINHTTP_QUERY_FLAG_REQUEST_HEADERS 0x80000000
#define WINHTTP_QUERY_FLAG_SYSTEMTIME     0x40000000
#define WINHTTP_QUERY_FLAG_NUMBER         0x20000000
#define WINHTTP_QUERY_FLAG_NUMBER64       0x08000000

/* status callbacks */
typedef VOID (CALLBACK *WINHTTP_STATUS_CALLBACK)(HINTERNET, DWORD_PTR, DWORD, LPVOID, DWORD);
#define WINHTTP_INVALID_STATUS_CALLBACK ((WINHTTP_STATUS_CALLBACK)(-1L))
#define WINHTTP_CALLBACK_STATUS_HANDLE_CREATED        0x00000400
#define WINHTTP_CALLBACK_STATUS_HANDLE_CLOSING        0x00000800
#define WINHTTP_CALLBACK_STATUS_REDIRECT              0x00004000
#define WINHTTP_CALLBACK_STATUS_HEADERS_AVAILABLE     0x00020000
#define WINHTTP_CALLBACK_STATUS_DATA_AVAILABLE        0x00040000
#define WINHTTP_CALLBACK_STATUS_READ_COMPLETE         0x00080000
#define WINHTTP_CALLBACK_STATUS_WRITE_COMPLETE        0x00100000
#define WINHTTP_CALLBACK_STATUS_REQUEST_ERROR         0x00200000
#define WINHTTP_CALLBACK_STATUS_SENDREQUEST_COMPLETE  0x00400000
#define WINHTTP_CALLBACK_FLAG_ALL_COMPLETIONS         0x017E0000
#define WINHTTP_CALLBACK_FLAG_ALL_NOTIFICATIONS       0xFFFFFFFF

#define API_RECEIVE_RESPONSE      1
#define API_QUERY_DATA_AVAILABLE  2
#define API_READ_DATA             3
#define API_WRITE_DATA            4
#define API_SEND_REQUEST          5

typedef struct { DWORD_PTR dwResult; DWORD dwError; } WINHTTP_ASYNC_RESULT;

/* errors */
#define WINHTTP_ERROR_BASE                      12000
#define ERROR_WINHTTP_TIMEOUT                   12002
#define ERROR_WINHTTP_INTERNAL_ERROR            12004
#define ERROR_WINHTTP_INVALID_URL               12005
#define ERROR_WINHTTP_UNRECOGNIZED_SCHEME       12006
#define ERROR_WINHTTP_NAME_NOT_RESOLVED         12007
#define ERROR_WINHTTP_INVALID_OPTION            12009
#define ERROR_WINHTTP_OPERATION_CANCELLED       12017
#define ERROR_WINHTTP_INCORRECT_HANDLE_TYPE     12018
#define ERROR_WINHTTP_INCORRECT_HANDLE_STATE    12019
#define ERROR_WINHTTP_CANNOT_CONNECT            12029
#define ERROR_WINHTTP_CONNECTION_ERROR          12030
#define ERROR_WINHTTP_SECURE_CERT_DATE_INVALID  12037
#define ERROR_WINHTTP_SECURE_CERT_CN_INVALID    12038
#define ERROR_WINHTTP_SECURE_INVALID_CA         12045
#define ERROR_WINHTTP_HEADER_NOT_FOUND          12150
#define ERROR_WINHTTP_INVALID_SERVER_RESPONSE   12152
#define ERROR_WINHTTP_REDIRECT_FAILED           12156
#define ERROR_WINHTTP_SECURE_FAILURE            12175
#define ERROR_WINHTTP_AUTODETECTION_FAILED      12180

typedef struct {
    DWORD dwStructSize;
    LPWSTR lpszScheme;    DWORD dwSchemeLength;
    INTERNET_SCHEME nScheme;
    LPWSTR lpszHostName;  DWORD dwHostNameLength;
    INTERNET_PORT nPort;
    LPWSTR lpszUserName;  DWORD dwUserNameLength;
    LPWSTR lpszPassword;  DWORD dwPasswordLength;
    LPWSTR lpszUrlPath;   DWORD dwUrlPathLength;
    LPWSTR lpszExtraInfo; DWORD dwExtraInfoLength;
} URL_COMPONENTS, *LPURL_COMPONENTS, URL_COMPONENTSW;

typedef struct { BOOL fAutoDetect; LPWSTR lpszAutoConfigUrl, lpszProxy, lpszProxyBypass; } WINHTTP_CURRENT_USER_IE_PROXY_CONFIG;
typedef struct { DWORD dwAccessType; LPWSTR lpszProxy, lpszProxyBypass; } WINHTTP_PROXY_INFO, *LPWINHTTP_PROXY_INFO;

#define WINHTTP_AUTH_SCHEME_BASIC       0x00000001
#define WINHTTP_AUTH_TARGET_SERVER      0x00000000
#define WINHTTP_AUTH_TARGET_PROXY       0x00000001

#ifdef __cplusplus
extern "C" {
#endif
WINHTTPAPI HINTERNET WINAPI WinHttpOpen(LPCWSTR agent, DWORD access, LPCWSTR proxy, LPCWSTR bypass, DWORD flags);
WINHTTPAPI HINTERNET WINAPI WinHttpConnect(HINTERNET session, LPCWSTR server, INTERNET_PORT port, DWORD reserved);
WINHTTPAPI HINTERNET WINAPI WinHttpOpenRequest(HINTERNET connect, LPCWSTR verb, LPCWSTR object, LPCWSTR version,
                                               LPCWSTR referrer, LPCWSTR *accept_types, DWORD flags);
WINHTTPAPI BOOL WINAPI WinHttpCloseHandle(HINTERNET h);
WINHTTPAPI BOOL WINAPI WinHttpAddRequestHeaders(HINTERNET request, LPCWSTR headers, DWORD length, DWORD modifiers);
WINHTTPAPI BOOL WINAPI WinHttpSendRequest(HINTERNET request, LPCWSTR headers, DWORD headers_length, LPVOID optional,
                                          DWORD optional_length, DWORD total_length, DWORD_PTR context);
WINHTTPAPI BOOL WINAPI WinHttpWriteData(HINTERNET request, LPCVOID buffer, DWORD length, LPDWORD written);
WINHTTPAPI BOOL WINAPI WinHttpReceiveResponse(HINTERNET request, LPVOID reserved);
WINHTTPAPI BOOL WINAPI WinHttpQueryHeaders(HINTERNET request, DWORD level, LPCWSTR name, LPVOID buffer,
                                           LPDWORD length, LPDWORD index);
WINHTTPAPI BOOL WINAPI WinHttpQueryDataAvailable(HINTERNET request, LPDWORD available);
WINHTTPAPI BOOL WINAPI WinHttpReadData(HINTERNET request, LPVOID buffer, DWORD length, LPDWORD read);
WINHTTPAPI BOOL WINAPI WinHttpSetOption(HINTERNET h, DWORD option, LPVOID buffer, DWORD length);
WINHTTPAPI BOOL WINAPI WinHttpQueryOption(HINTERNET h, DWORD option, LPVOID buffer, LPDWORD length);
WINHTTPAPI BOOL WINAPI WinHttpSetTimeouts(HINTERNET h, int resolve, int connect, int send, int receive);
WINHTTPAPI WINHTTP_STATUS_CALLBACK WINAPI WinHttpSetStatusCallback(HINTERNET h, WINHTTP_STATUS_CALLBACK cb,
                                                                   DWORD flags, DWORD_PTR reserved);
WINHTTPAPI BOOL WINAPI WinHttpSetCredentials(HINTERNET request, DWORD target, DWORD scheme, LPCWSTR user,
                                             LPCWSTR password, LPVOID params);
WINHTTPAPI BOOL WINAPI WinHttpQueryAuthSchemes(HINTERNET request, LPDWORD supported, LPDWORD first, LPDWORD target);
WINHTTPAPI BOOL WINAPI WinHttpCrackUrl(LPCWSTR url, DWORD length, DWORD flags, LPURL_COMPONENTS uc);
WINHTTPAPI BOOL WINAPI WinHttpCreateUrl(LPURL_COMPONENTS uc, DWORD flags, LPWSTR url, LPDWORD length);
WINHTTPAPI BOOL WINAPI WinHttpTimeFromSystemTime(const SYSTEMTIME *st, LPWSTR out);
WINHTTPAPI BOOL WINAPI WinHttpTimeToSystemTime(LPCWSTR time, SYSTEMTIME *st);
WINHTTPAPI BOOL WINAPI WinHttpCheckPlatform(void);
WINHTTPAPI BOOL WINAPI WinHttpGetIEProxyConfigForCurrentUser(WINHTTP_CURRENT_USER_IE_PROXY_CONFIG *config);
WINHTTPAPI BOOL WINAPI WinHttpGetDefaultProxyConfiguration(WINHTTP_PROXY_INFO *info);
WINHTTPAPI BOOL WINAPI WinHttpSetDefaultProxyConfiguration(WINHTTP_PROXY_INFO *info);
WINHTTPAPI BOOL WINAPI WinHttpGetProxyForUrl(HINTERNET session, LPCWSTR url, LPVOID options, WINHTTP_PROXY_INFO *info);
WINHTTPAPI BOOL WINAPI WinHttpDetectAutoProxyConfigUrl(DWORD flags, LPWSTR *url);
#ifdef __cplusplus
}
#endif
