/*** Autogenerated by WIDL 8.5 from ndrbase.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __ndrbase_h__
#define __ndrbase_h__

#ifndef __WIDL_INLINE
#if defined(__cplusplus) || defined(_MSC_VER)
#define __WIDL_INLINE inline
#elif defined(__GNUC__)
#define __WIDL_INLINE __inline__
#endif
#endif

/* Forward declarations */

#ifndef __INdrBase_FWD_DEFINED__
#define __INdrBase_FWD_DEFINED__
typedef interface INdrBase INdrBase;
#ifdef __cplusplus
interface INdrBase;
#endif /* __cplusplus */
#endif

/* Headers for imported files */

#include "ndrunk.h"

#ifdef __cplusplus
extern "C" {
#endif

/*****************************************************************************
 * INdrBase interface
 */
#ifndef __INdrBase_INTERFACE_DEFINED__
#define __INdrBase_INTERFACE_DEFINED__

DEFINE_GUID(IID_INdrBase, 0x6e0f3a10, 0x4d2b, 0x4c55, 0x9a,0x51, 0x7c,0x0d,0xe0,0xa1,0xb0,0x01);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("6e0f3a10-4d2b-4c55-9a51-7c0de0a1b001")
INdrBase : public IUnknown
{
    virtual HRESULT STDMETHODCALLTYPE Add(
        LONG a,
        LONG b,
        LONG *sum) = 0;

    virtual HRESULT STDMETHODCALLTYPE Negate(
        LONG *v) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(INdrBase, 0x6e0f3a10, 0x4d2b, 0x4c55, 0x9a,0x51, 0x7c,0x0d,0xe0,0xa1,0xb0,0x01)
#endif
#else
typedef struct INdrBaseVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        INdrBase *This,
        REFIID riid,
        void **ppv);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        INdrBase *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        INdrBase *This);

    /*** INdrBase methods ***/
    HRESULT (STDMETHODCALLTYPE *Add)(
        INdrBase *This,
        LONG a,
        LONG b,
        LONG *sum);

    HRESULT (STDMETHODCALLTYPE *Negate)(
        INdrBase *This,
        LONG *v);

    END_INTERFACE
} INdrBaseVtbl;

interface INdrBase {
    CONST_VTBL INdrBaseVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define INdrBase_QueryInterface(This,riid,ppv) (This)->lpVtbl->QueryInterface(This,riid,ppv)
#define INdrBase_AddRef(This) (This)->lpVtbl->AddRef(This)
#define INdrBase_Release(This) (This)->lpVtbl->Release(This)
/*** INdrBase methods ***/
#define INdrBase_Add(This,a,b,sum) (This)->lpVtbl->Add(This,a,b,sum)
#define INdrBase_Negate(This,v) (This)->lpVtbl->Negate(This,v)
#else
/*** IUnknown methods ***/
static __WIDL_INLINE HRESULT INdrBase_QueryInterface(INdrBase* This,REFIID riid,void **ppv) {
    return This->lpVtbl->QueryInterface(This,riid,ppv);
}
static __WIDL_INLINE ULONG INdrBase_AddRef(INdrBase* This) {
    return This->lpVtbl->AddRef(This);
}
static __WIDL_INLINE ULONG INdrBase_Release(INdrBase* This) {
    return This->lpVtbl->Release(This);
}
/*** INdrBase methods ***/
static __WIDL_INLINE HRESULT INdrBase_Add(INdrBase* This,LONG a,LONG b,LONG *sum) {
    return This->lpVtbl->Add(This,a,b,sum);
}
static __WIDL_INLINE HRESULT INdrBase_Negate(INdrBase* This,LONG *v) {
    return This->lpVtbl->Negate(This,v);
}
#endif
#endif

#endif


#endif  /* __INdrBase_INTERFACE_DEFINED__ */

/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __ndrbase_h__ */
