/*** Autogenerated by WIDL 8.5 from ndrdual.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __ndrdual_h__
#define __ndrdual_h__

#ifndef __WIDL_INLINE
#if defined(__cplusplus) || defined(_MSC_VER)
#define __WIDL_INLINE inline
#elif defined(__GNUC__)
#define __WIDL_INLINE __inline__
#endif
#endif

/* Forward declarations */

#ifndef __INdrDual_FWD_DEFINED__
#define __INdrDual_FWD_DEFINED__
typedef interface INdrDual INdrDual;
#ifdef __cplusplus
interface INdrDual;
#endif /* __cplusplus */
#endif

/* Headers for imported files */

#include <oleauto.h>             /* (not widl's ndrdisp.h: oleauto.h has the real BSTR, VARIANT and IDispatch) */

#ifdef __cplusplus
extern "C" {
#endif

/*****************************************************************************
 * INdrDual interface
 */
#ifndef __INdrDual_INTERFACE_DEFINED__
#define __INdrDual_INTERFACE_DEFINED__

DEFINE_GUID(IID_INdrDual, 0x6e0f3a10, 0x4d2b, 0x4c55, 0x9a,0x51, 0x7c,0x0d,0xe0,0xa1,0xb0,0x03);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("6e0f3a10-4d2b-4c55-9a51-7c0de0a1b003")
INdrDual : public IDispatch
{
    virtual HRESULT STDMETHODCALLTYPE Concat(
        BSTR a,
        BSTR b,
        BSTR *r) = 0;

    virtual HRESULT STDMETHODCALLTYPE Describe(
        VARIANT v,
        VARIANT *r) = 0;

    virtual HRESULT STDMETHODCALLTYPE Twice(
        VARIANT *v) = 0;

    virtual HRESULT STDMETHODCALLTYPE Pid(
        LONG *pid) = 0;

    virtual HRESULT STDMETHODCALLTYPE Call(
        INdrDual *cb,
        BSTR text,
        BSTR *r) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(INdrDual, 0x6e0f3a10, 0x4d2b, 0x4c55, 0x9a,0x51, 0x7c,0x0d,0xe0,0xa1,0xb0,0x03)
#endif
#else
typedef struct INdrDualVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        INdrDual *This,
        REFIID riid,
        void **ppv);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        INdrDual *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        INdrDual *This);

    /*** IDispatch methods ***/
    HRESULT (STDMETHODCALLTYPE *GetTypeInfoCount)(
        INdrDual *This,
        UINT *n);

    HRESULT (STDMETHODCALLTYPE *GetTypeInfo)(
        INdrDual *This,
        UINT i,
        LCID lcid,
        IUnknown **ti);

    HRESULT (STDMETHODCALLTYPE *GetIDsOfNames)(
        INdrDual *This,
        REFIID riid,
        LPOLESTR *names,
        UINT n,
        LCID lcid,
        DISPID *ids);

    HRESULT (STDMETHODCALLTYPE *Invoke)(
        INdrDual *This,
        DISPID id,
        REFIID riid,
        LCID lcid,
        WORD flags,
        DISPPARAMS *params,
        VARIANT *result,
        EXCEPINFO *excep,
        UINT *argerr);

    /*** INdrDual methods ***/
    HRESULT (STDMETHODCALLTYPE *Concat)(
        INdrDual *This,
        BSTR a,
        BSTR b,
        BSTR *r);

    HRESULT (STDMETHODCALLTYPE *Describe)(
        INdrDual *This,
        VARIANT v,
        VARIANT *r);

    HRESULT (STDMETHODCALLTYPE *Twice)(
        INdrDual *This,
        VARIANT *v);

    HRESULT (STDMETHODCALLTYPE *Pid)(
        INdrDual *This,
        LONG *pid);

    HRESULT (STDMETHODCALLTYPE *Call)(
        INdrDual *This,
        INdrDual *cb,
        BSTR text,
        BSTR *r);

    END_INTERFACE
} INdrDualVtbl;

interface INdrDual {
    CONST_VTBL INdrDualVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define INdrDual_QueryInterface(This,riid,ppv) (This)->lpVtbl->QueryInterface(This,riid,ppv)
#define INdrDual_AddRef(This) (This)->lpVtbl->AddRef(This)
#define INdrDual_Release(This) (This)->lpVtbl->Release(This)
/*** IDispatch methods ***/
#define INdrDual_GetTypeInfoCount(This,n) (This)->lpVtbl->GetTypeInfoCount(This,n)
#define INdrDual_GetTypeInfo(This,i,lcid,ti) (This)->lpVtbl->GetTypeInfo(This,i,lcid,ti)
#define INdrDual_GetIDsOfNames(This,riid,names,n,lcid,ids) (This)->lpVtbl->GetIDsOfNames(This,riid,names,n,lcid,ids)
#define INdrDual_Invoke(This,id,riid,lcid,flags,params,result,excep,argerr) (This)->lpVtbl->Invoke(This,id,riid,lcid,flags,params,result,excep,argerr)
/*** INdrDual methods ***/
#define INdrDual_Concat(This,a,b,r) (This)->lpVtbl->Concat(This,a,b,r)
#define INdrDual_Describe(This,v,r) (This)->lpVtbl->Describe(This,v,r)
#define INdrDual_Twice(This,v) (This)->lpVtbl->Twice(This,v)
#define INdrDual_Pid(This,pid) (This)->lpVtbl->Pid(This,pid)
#define INdrDual_Call(This,cb,text,r) (This)->lpVtbl->Call(This,cb,text,r)
#else
/*** IUnknown methods ***/
static __WIDL_INLINE HRESULT INdrDual_QueryInterface(INdrDual* This,REFIID riid,void **ppv) {
    return This->lpVtbl->QueryInterface(This,riid,ppv);
}
static __WIDL_INLINE ULONG INdrDual_AddRef(INdrDual* This) {
    return This->lpVtbl->AddRef(This);
}
static __WIDL_INLINE ULONG INdrDual_Release(INdrDual* This) {
    return This->lpVtbl->Release(This);
}
/*** IDispatch methods ***/
static __WIDL_INLINE HRESULT INdrDual_GetTypeInfoCount(INdrDual* This,UINT *n) {
    return This->lpVtbl->GetTypeInfoCount(This,n);
}
static __WIDL_INLINE HRESULT INdrDual_GetTypeInfo(INdrDual* This,UINT i,LCID lcid,IUnknown **ti) {
    return This->lpVtbl->GetTypeInfo(This,i,lcid,ti);
}
static __WIDL_INLINE HRESULT INdrDual_GetIDsOfNames(INdrDual* This,REFIID riid,LPOLESTR *names,UINT n,LCID lcid,DISPID *ids) {
    return This->lpVtbl->GetIDsOfNames(This,riid,names,n,lcid,ids);
}
static __WIDL_INLINE HRESULT INdrDual_Invoke(INdrDual* This,DISPID id,REFIID riid,LCID lcid,WORD flags,DISPPARAMS *params,VARIANT *result,EXCEPINFO *excep,UINT *argerr) {
    return This->lpVtbl->Invoke(This,id,riid,lcid,flags,params,result,excep,argerr);
}
/*** INdrDual methods ***/
static __WIDL_INLINE HRESULT INdrDual_Concat(INdrDual* This,BSTR a,BSTR b,BSTR *r) {
    return This->lpVtbl->Concat(This,a,b,r);
}
static __WIDL_INLINE HRESULT INdrDual_Describe(INdrDual* This,VARIANT v,VARIANT *r) {
    return This->lpVtbl->Describe(This,v,r);
}
static __WIDL_INLINE HRESULT INdrDual_Twice(INdrDual* This,VARIANT *v) {
    return This->lpVtbl->Twice(This,v);
}
static __WIDL_INLINE HRESULT INdrDual_Pid(INdrDual* This,LONG *pid) {
    return This->lpVtbl->Pid(This,pid);
}
static __WIDL_INLINE HRESULT INdrDual_Call(INdrDual* This,INdrDual *cb,BSTR text,BSTR *r) {
    return This->lpVtbl->Call(This,cb,text,r);
}
#endif
#endif

#endif


#endif  /* __INdrDual_INTERFACE_DEFINED__ */

/* Begin additional prototypes for all interfaces */

ULONG           __RPC_USER BSTR_UserSize     (ULONG *, ULONG, BSTR *);
unsigned char * __RPC_USER BSTR_UserMarshal  (ULONG *, unsigned char *, BSTR *);
unsigned char * __RPC_USER BSTR_UserUnmarshal(ULONG *, unsigned char *, BSTR *);
void            __RPC_USER BSTR_UserFree     (ULONG *, BSTR *);
ULONG           __RPC_USER VARIANT_UserSize     (ULONG *, ULONG, VARIANT *);
unsigned char * __RPC_USER VARIANT_UserMarshal  (ULONG *, unsigned char *, VARIANT *);
unsigned char * __RPC_USER VARIANT_UserUnmarshal(ULONG *, unsigned char *, VARIANT *);
void            __RPC_USER VARIANT_UserFree     (ULONG *, VARIANT *);

/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __ndrdual_h__ */
