/*** Autogenerated by WIDL 8.5 from ndrtest.idl - Do not edit ***/

#ifdef _WIN32
#ifndef __REQUIRED_RPCNDR_H_VERSION__
#define __REQUIRED_RPCNDR_H_VERSION__ 475
#endif
#include <rpc.h>
#include <rpcndr.h>
#endif

#ifndef COM_NO_WINDOWS_H
#include <windows.h>
#include <ole2.h>
#endif

#ifndef __ndrtest_h__
#define __ndrtest_h__

#ifndef __WIDL_INLINE
#if defined(__cplusplus) || defined(_MSC_VER)
#define __WIDL_INLINE inline
#elif defined(__GNUC__)
#define __WIDL_INLINE __inline__
#endif
#endif

/* Forward declarations */

#ifndef __INdrTest_FWD_DEFINED__
#define __INdrTest_FWD_DEFINED__
typedef interface INdrTest INdrTest;
#ifdef __cplusplus
interface INdrTest;
#endif /* __cplusplus */
#endif

/* Headers for imported files */

#include "ndrbase.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct NdrPoint {
    short x;
    LONG y;
    double z;
} NdrPoint;
typedef struct NdrNamed {
    LONG id;
    WCHAR *name;
} NdrNamed;
typedef struct NdrVec {
    ULONG n;
    LONG items[1];
} NdrVec;
/*****************************************************************************
 * INdrTest interface
 */
#ifndef __INdrTest_INTERFACE_DEFINED__
#define __INdrTest_INTERFACE_DEFINED__

DEFINE_GUID(IID_INdrTest, 0x6e0f3a10, 0x4d2b, 0x4c55, 0x9a,0x51, 0x7c,0x0d,0xe0,0xa1,0xb0,0x02);
#if defined(__cplusplus) && !defined(CINTERFACE)
MIDL_INTERFACE("6e0f3a10-4d2b-4c55-9a51-7c0de0a1b002")
INdrTest : public INdrBase
{
    virtual HRESULT STDMETHODCALLTYPE Echo(
        const WCHAR *in,
        WCHAR **out) = 0;

    virtual HRESULT STDMETHODCALLTYPE Sum(
        ULONG n,
        const LONG *v,
        hyper *total) = 0;

    virtual HRESULT STDMETHODCALLTYPE Fill(
        ULONG n,
        BYTE seed,
        BYTE *buf) = 0;

    virtual HRESULT STDMETHODCALLTYPE Scale(
        double d,
        float f,
        short s,
        BYTE c,
        hyper h,
        double e,
        double *r) = 0;

    virtual HRESULT STDMETHODCALLTYPE Move(
        NdrPoint by,
        NdrPoint *p) = 0;

    virtual HRESULT STDMETHODCALLTYPE Maybe(
        LONG *v,
        LONG *got) = 0;

    virtual HRESULT STDMETHODCALLTYPE List(
        ULONG n,
        ULONG *count,
        LONG **items) = 0;

    virtual HRESULT STDMETHODCALLTYPE Rename(
        NdrNamed *n) = 0;

    virtual HRESULT STDMETHODCALLTYPE Total(
        NdrVec *v,
        LONG *total) = 0;

    virtual HRESULT STDMETHODCALLTYPE Fail(
        HRESULT hr) = 0;

};
#ifdef __CRT_UUID_DECL
__CRT_UUID_DECL(INdrTest, 0x6e0f3a10, 0x4d2b, 0x4c55, 0x9a,0x51, 0x7c,0x0d,0xe0,0xa1,0xb0,0x02)
#endif
#else
typedef struct INdrTestVtbl {
    BEGIN_INTERFACE

    /*** IUnknown methods ***/
    HRESULT (STDMETHODCALLTYPE *QueryInterface)(
        INdrTest *This,
        REFIID riid,
        void **ppv);

    ULONG (STDMETHODCALLTYPE *AddRef)(
        INdrTest *This);

    ULONG (STDMETHODCALLTYPE *Release)(
        INdrTest *This);

    /*** INdrBase methods ***/
    HRESULT (STDMETHODCALLTYPE *Add)(
        INdrTest *This,
        LONG a,
        LONG b,
        LONG *sum);

    HRESULT (STDMETHODCALLTYPE *Negate)(
        INdrTest *This,
        LONG *v);

    /*** INdrTest methods ***/
    HRESULT (STDMETHODCALLTYPE *Echo)(
        INdrTest *This,
        const WCHAR *in,
        WCHAR **out);

    HRESULT (STDMETHODCALLTYPE *Sum)(
        INdrTest *This,
        ULONG n,
        const LONG *v,
        hyper *total);

    HRESULT (STDMETHODCALLTYPE *Fill)(
        INdrTest *This,
        ULONG n,
        BYTE seed,
        BYTE *buf);

    HRESULT (STDMETHODCALLTYPE *Scale)(
        INdrTest *This,
        double d,
        float f,
        short s,
        BYTE c,
        hyper h,
        double e,
        double *r);

    HRESULT (STDMETHODCALLTYPE *Move)(
        INdrTest *This,
        NdrPoint by,
        NdrPoint *p);

    HRESULT (STDMETHODCALLTYPE *Maybe)(
        INdrTest *This,
        LONG *v,
        LONG *got);

    HRESULT (STDMETHODCALLTYPE *List)(
        INdrTest *This,
        ULONG n,
        ULONG *count,
        LONG **items);

    HRESULT (STDMETHODCALLTYPE *Rename)(
        INdrTest *This,
        NdrNamed *n);

    HRESULT (STDMETHODCALLTYPE *Total)(
        INdrTest *This,
        NdrVec *v,
        LONG *total);

    HRESULT (STDMETHODCALLTYPE *Fail)(
        INdrTest *This,
        HRESULT hr);

    END_INTERFACE
} INdrTestVtbl;

interface INdrTest {
    CONST_VTBL INdrTestVtbl* lpVtbl;
};

#ifdef COBJMACROS
#ifndef WIDL_C_INLINE_WRAPPERS
/*** IUnknown methods ***/
#define INdrTest_QueryInterface(This,riid,ppv) (This)->lpVtbl->QueryInterface(This,riid,ppv)
#define INdrTest_AddRef(This) (This)->lpVtbl->AddRef(This)
#define INdrTest_Release(This) (This)->lpVtbl->Release(This)
/*** INdrBase methods ***/
#define INdrTest_Add(This,a,b,sum) (This)->lpVtbl->Add(This,a,b,sum)
#define INdrTest_Negate(This,v) (This)->lpVtbl->Negate(This,v)
/*** INdrTest methods ***/
#define INdrTest_Echo(This,in,out) (This)->lpVtbl->Echo(This,in,out)
#define INdrTest_Sum(This,n,v,total) (This)->lpVtbl->Sum(This,n,v,total)
#define INdrTest_Fill(This,n,seed,buf) (This)->lpVtbl->Fill(This,n,seed,buf)
#define INdrTest_Scale(This,d,f,s,c,h,e,r) (This)->lpVtbl->Scale(This,d,f,s,c,h,e,r)
#define INdrTest_Move(This,by,p) (This)->lpVtbl->Move(This,by,p)
#define INdrTest_Maybe(This,v,got) (This)->lpVtbl->Maybe(This,v,got)
#define INdrTest_List(This,n,count,items) (This)->lpVtbl->List(This,n,count,items)
#define INdrTest_Rename(This,n) (This)->lpVtbl->Rename(This,n)
#define INdrTest_Total(This,v,total) (This)->lpVtbl->Total(This,v,total)
#define INdrTest_Fail(This,hr) (This)->lpVtbl->Fail(This,hr)
#else
/*** IUnknown methods ***/
static __WIDL_INLINE HRESULT INdrTest_QueryInterface(INdrTest* This,REFIID riid,void **ppv) {
    return This->lpVtbl->QueryInterface(This,riid,ppv);
}
static __WIDL_INLINE ULONG INdrTest_AddRef(INdrTest* This) {
    return This->lpVtbl->AddRef(This);
}
static __WIDL_INLINE ULONG INdrTest_Release(INdrTest* This) {
    return This->lpVtbl->Release(This);
}
/*** INdrBase methods ***/
static __WIDL_INLINE HRESULT INdrTest_Add(INdrTest* This,LONG a,LONG b,LONG *sum) {
    return This->lpVtbl->Add(This,a,b,sum);
}
static __WIDL_INLINE HRESULT INdrTest_Negate(INdrTest* This,LONG *v) {
    return This->lpVtbl->Negate(This,v);
}
/*** INdrTest methods ***/
static __WIDL_INLINE HRESULT INdrTest_Echo(INdrTest* This,const WCHAR *in,WCHAR **out) {
    return This->lpVtbl->Echo(This,in,out);
}
static __WIDL_INLINE HRESULT INdrTest_Sum(INdrTest* This,ULONG n,const LONG *v,hyper *total) {
    return This->lpVtbl->Sum(This,n,v,total);
}
static __WIDL_INLINE HRESULT INdrTest_Fill(INdrTest* This,ULONG n,BYTE seed,BYTE *buf) {
    return This->lpVtbl->Fill(This,n,seed,buf);
}
static __WIDL_INLINE HRESULT INdrTest_Scale(INdrTest* This,double d,float f,short s,BYTE c,hyper h,double e,double *r) {
    return This->lpVtbl->Scale(This,d,f,s,c,h,e,r);
}
static __WIDL_INLINE HRESULT INdrTest_Move(INdrTest* This,NdrPoint by,NdrPoint *p) {
    return This->lpVtbl->Move(This,by,p);
}
static __WIDL_INLINE HRESULT INdrTest_Maybe(INdrTest* This,LONG *v,LONG *got) {
    return This->lpVtbl->Maybe(This,v,got);
}
static __WIDL_INLINE HRESULT INdrTest_List(INdrTest* This,ULONG n,ULONG *count,LONG **items) {
    return This->lpVtbl->List(This,n,count,items);
}
static __WIDL_INLINE HRESULT INdrTest_Rename(INdrTest* This,NdrNamed *n) {
    return This->lpVtbl->Rename(This,n);
}
static __WIDL_INLINE HRESULT INdrTest_Total(INdrTest* This,NdrVec *v,LONG *total) {
    return This->lpVtbl->Total(This,v,total);
}
static __WIDL_INLINE HRESULT INdrTest_Fail(INdrTest* This,HRESULT hr) {
    return This->lpVtbl->Fail(This,hr);
}
#endif
#endif

#endif


#endif  /* __INdrTest_INTERFACE_DEFINED__ */

/* Begin additional prototypes for all interfaces */


/* End additional prototypes */

#ifdef __cplusplus
}
#endif

#endif /* __ndrtest_h__ */
