#!/usr/bin/env python3
"""Generate kernel32's table of Windows locales (userland/kernel32/locale_data.h).

    tools/gen_locales.py [IcuLocaleData.cs]

The table is .NET's own record of what Windows knows about each locale
(dotnet/runtime, src/libraries/System.Private.CoreLib/src/System/
Globalization/IcuLocaleData.cs, MIT licence): the 864 locale names, their
LCIDs, ANSI/OEM/Mac/EBCDIC code pages, GEOIDs, list separators, specific and
console-fallback locales, and three-letter Windows language names.  .NET
uses it on Linux and macOS to answer what NLS answers on Windows; NovaOS's
kernel32 uses it the same way, with ICU (icu.dll) for the rest.

Without an argument the file is fetched from the v10.0.0 tag.
"""
import os, re, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'userland', 'kernel32', 'locale_data.h')
URL = ('https://raw.githubusercontent.com/dotnet/runtime/v10.0.0/src/libraries/'
       'System.Private.CoreLib/src/System/Globalization/IcuLocaleData.cs')


def block(src, name):
    """the body of the C# property @name"""
    m = re.search(r'\b' + name + r'\s*=>[^\n]*\n(.*?);\s*\n', src, re.S)
    return m.group(1)


def windows_case(name):
    """'de-de' -> 'de-DE', 'zh-hans-cn' -> 'zh-Hans-CN', 'zh-cn_phoneb' stays
    lower after the '_' (the sort name), as LCIDToLocaleName returns them"""
    base, _, sort = name.partition('_')
    parts = base.split('-')
    out = [parts[0]]
    for p in parts[1:]:
        if len(p) == 2 or (len(p) == 3 and (p.isdigit() or p.isalpha())):
            out.append(p.upper())
        elif len(p) == 4 and p.isalpha():
            out.append(p.title())
        else:
            out.append(p)
    return '-'.join(out) + ('_' + sort if sort else '')


def main():
    if len(sys.argv) > 1:
        src = open(sys.argv[1], encoding='utf-8').read()
    else:
        src = subprocess.run(['curl', '-sSLf', URL], capture_output=True, text=True, check=True).stdout

    names_blob = ''.join(re.findall(r'"([^"]*)"u8', block(src, 'CultureNames')))
    idx = [int(x) for x in re.findall(r'\b\d+\b', re.sub(r'//[^\n]*', '', block(src, 'LocalesNamesIndexes')))]
    count = int(re.search(r'CulturesCount = (\d+)', src).group(1))
    assert len(idx) == 2 * count
    names = []
    for i in range(count):
        hi, lo = idx[2 * i], idx[2 * i + 1]
        start, length = (hi << 4) | (lo >> 4), lo & 0xF
        names.append(names_blob[start:start + length])
    assert names == sorted(names), 'names must be sorted for the binary search'

    num = [int(x, 16) for x in re.findall(r'0x([0-9a-f]{2})', re.sub(r'//[^\n]*', '', block(src, 'NameIndexToNumericData')))]
    assert len(num) == 18 * count
    abbrev = re.findall(r'"([A-Z]{3})"u8', block(src, 'ThreeLetterWindowsLanguageName'))
    assert len(abbrev) == count

    rows = []
    for i, n in enumerate(names):
        d = num[18 * i:18 * i + 18]
        lcid = d[2] | d[1] << 8 | d[0] << 16
        ansi = (d[4] & 0xF0) >> 4 | d[3] << 4
        oem = d[5] | (d[4] & 0xF) << 8
        mac = d[7] | d[6] << 8
        ebcdic = d[9] | d[8] << 8
        geo = d[13] | d[12] << 8 | d[11] << 16 | d[10] << 24
        sep = d[14]                       # high nibble: list separator kind, low: digit substitution
        specific = (d[16] & 0xF0) >> 4 | d[15] << 4
        console = d[17] | (d[16] & 0xF) << 8
        specific = -1 if specific == 0xFFF else specific
        console = -1 if console == 0xFFF else console
        rows.append((windows_case(n), lcid, ansi, oem, mac, ebcdic, geo, sep, specific, console, abbrev[i]))

    with open(OUT, 'w') as f:
        f.write('/* Generated by tools/gen_locales.py from .NET\'s IcuLocaleData.cs\n'
                ' * (Copyright (c) .NET Foundation and Contributors, MIT licence):\n'
                ' * the locales Windows knows, sorted by lower-case name.  Do not edit. */\n')
        f.write('#pragma once\n\n')
        f.write('typedef struct {\n'
                '    const char    *name;      /* as Windows spells it: de-DE, zh-Hans, zh-CN_phoneb */\n'
                '    unsigned       lcid;      /* 0x1000 (LOCALE_CUSTOM_UNSPECIFIED): none of its own */\n'
                '    unsigned short ansi, oem, mac, ebcdic;   /* default code pages */\n'
                '    unsigned       geo;       /* GEOID */\n'
                '    unsigned char  sep;       /* list separator kind << 4 | digit substitution */\n'
                '    short          specific;  /* index of the specific locale (for a neutral one) */\n'
                '    short          console;   /* index of the console fallback locale */\n'
                '    char           abbrev[4]; /* LOCALE_SABBREVLANGNAME */\n'
                '} NovaLocale;\n\n')
        f.write(f'#define NOVA_LOCALE_COUNT {count}\n')
        f.write('static const NovaLocale g_locales[NOVA_LOCALE_COUNT] = {\n')
        for r in rows:
            f.write('    {{ "{}", 0x{:x}, {}, {}, {}, {}, {}, 0x{:02x}, {}, {}, "{}" }},\n'.format(*r))
        f.write('};\n')
    print(f'{OUT}: {count} locales')


if __name__ == '__main__':
    main()
