/*
 * mkfont.c — rasterize the GDI font faces into kernel/gdi/font_inter.c
 *
 * Host-side tool; the kernel itself never needs FreeType.  Re-run it only
 * when changing the font, sizes or character range:
 *
 *   cc -O2 $(pkg-config --cflags freetype2) tools/mkfont.c \
 *      $(pkg-config --libs freetype2) -o mkfont
 *   ./mkfont Inter-Regular.ttf Inter-SemiBold.ttf > kernel/gdi/font_inter.c
 *
 * Inter is by Rasmus Andersson, SIL Open Font License 1.1
 * (see third_party/inter/LICENSE.txt).
 *
 * Output: for each style and each integer display scale 1..MAX_SCALE, the
 * printable ASCII glyphs rendered at BASE_PX * scale pixels with light
 * (vertical-only) hinting as 8-bit coverage, plus metrics.  Advances are
 * kept in 26.6 fixed point so text can be laid out with sub-pixel pen
 * positions using integer arithmetic only.
 */

#include <ft2build.h>
#include FT_FREETYPE_H
#include <math.h>
#include <stdio.h>
#include <stdlib.h>

#define BASE_PX    13      /* logical text size (fits the 16px line box) */
#define MAX_SCALE  2
#define FIRST      32
#define LAST       126

/* Mild coverage gamma: linear blending of hinted coverage renders thin
 * strokes a little light; this compensates slightly. */
#define GAMMA      0.85

static FT_Library ft;

static void emit_face(const char *path, const char *name, int scale)
{
    FT_Face face;
    if (FT_New_Face(ft, path, 0, &face)) {
        fprintf(stderr, "mkfont: cannot open %s\n", path);
        exit(1);
    }
    int px = BASE_PX * scale;
    FT_Set_Pixel_Sizes(face, 0, px);

    unsigned char lut[256];
    for (int i = 0; i < 256; i++)
        lut[i] = (unsigned char)lround(255.0 * pow(i / 255.0, GAMMA));

    unsigned char *bits = NULL;
    size_t nbits = 0;
    struct { unsigned off; int w, h, bx, by, adv; } g[LAST - FIRST + 1];

    for (int c = FIRST; c <= LAST; c++) {
        if (FT_Load_Char(face, c, FT_LOAD_RENDER | FT_LOAD_TARGET_LIGHT)) {
            fprintf(stderr, "mkfont: glyph %d failed\n", c);
            exit(1);
        }
        FT_GlyphSlot s = face->glyph;
        FT_Bitmap *b = &s->bitmap;
        int i = c - FIRST;
        g[i].off = (unsigned)nbits;
        g[i].w   = (int)b->width;
        g[i].h   = (int)b->rows;
        g[i].bx  = s->bitmap_left;
        g[i].by  = s->bitmap_top;
        /* linearHoriAdvance is 16.16; convert to 26.6 */
        g[i].adv = (int)((s->linearHoriAdvance + 512) >> 10);
        if (g[i].w > 255 || g[i].h > 255 || g[i].bx < -128 || g[i].bx > 127 ||
            g[i].by < -128 || g[i].by > 127 || g[i].adv > 65535) {
            fprintf(stderr, "mkfont: glyph %d metrics out of range\n", c);
            exit(1);
        }
        bits = realloc(bits, nbits + (size_t)(b->width * b->rows));
        for (unsigned y = 0; y < b->rows; y++)
            for (unsigned x = 0; x < b->width; x++)
                bits[nbits++] = lut[b->buffer[y * b->pitch + x]];
    }

    printf("static const UINT8 %s_%d_bits[%zu] = {\n", name, scale, nbits ? nbits : 1);
    for (size_t i = 0; i < nbits; i++)
        printf("%s0x%02x,%s", (i % 16) ? "" : "  ", bits[i], (i % 16 == 15) ? "\n" : "");
    if (!nbits) printf("  0");
    printf("\n};\n\n");

    printf("static const GdiGlyph %s_%d_glyphs[%d] = {\n", name, scale, LAST - FIRST + 1);
    for (int c = FIRST; c <= LAST; c++) {
        int i = c - FIRST;
        printf("  { %6u, %3d, %3d, %4d, %4d, %5d }, /* '%c' */\n",
               g[i].off, g[i].w, g[i].h, g[i].bx, g[i].by, g[i].adv,
               c == '\\' ? '/' : c);
    }
    printf("};\n\n");

    free(bits);
    FT_Done_Face(face);
}

int main(int argc, char **argv)
{
    if (argc != 3) {
        fprintf(stderr, "usage: %s Regular.ttf Bold.ttf > font_inter.c\n", argv[0]);
        return 1;
    }
    if (FT_Init_FreeType(&ft)) { fprintf(stderr, "mkfont: FreeType init failed\n"); return 1; }

    const char *names[2] = { "inter_regular", "inter_semibold" };

    printf("/*\n * font_inter.c — GENERATED by tools/mkfont.c; do not edit by hand.\n"
           " *\n * Inter 4.1 by Rasmus Andersson, SIL Open Font License 1.1\n"
           " * (third_party/inter/LICENSE.txt).  Regular and SemiBold, ASCII %d-%d,\n"
           " * %dpx per display scale, light hinting, 8-bit coverage.\n */\n\n"
           "#include \"font.h\"\n\n", FIRST, LAST, BASE_PX);

    for (int st = 0; st < 2; st++)
        for (int sc = 1; sc <= MAX_SCALE; sc++)
            emit_face(argv[1 + st], names[st], sc);

    printf("const GdiFace g_gdi_faces[GDI_FONT_STYLES][GDI_MAX_SCALE] = {\n");
    for (int st = 0; st < 2; st++) {
        printf("  {\n");
        for (int sc = 1; sc <= MAX_SCALE; sc++)
            printf("    { %d, %d, %d, %s_%d_glyphs, %s_%d_bits },\n",
                   BASE_PX * sc, FIRST, LAST - FIRST + 1,
                   names[st], sc, names[st], sc);
        printf("  },\n");
    }
    printf("};\n");

    FT_Done_FreeType(ft);
    return 0;
}
