#!/usr/bin/env python3
"""Make the kernel's embedded symbol table (kernel/ke/ksym.c reads it).

    tools/mkksyms.py KERNEL.ELF OUT.S          the table for KERNEL.ELF
    tools/mkksyms.py --check KERNEL.ELF OUT.S  fail unless KERNEL.ELF's
                                               functions are where OUT.S says

The kernel is linked twice: first without the table, then with OUT.S
assembled into the .ksyms section, which linker.ld places after .text, so
no function moves between the links (--check proves it).  Format, in
section .ksyms: count (8 bytes), then count entries of {address (8),
offset of the name in the strings (4), size (4)} sorted by address, then
the NUL-terminated names.
"""
import re, shutil, subprocess, sys


def functions(elf):
    nm = shutil.which('llvm-nm') or shutil.which('nm')
    out = subprocess.run([nm, '--defined-only', '-S', '-n', elf], check=True,
                         capture_output=True, text=True).stdout
    syms = {}
    for line in out.splitlines():
        p = line.split()
        if len(p) == 4 and p[2] in 'tTwW':
            addr, size, name = int(p[0], 16), int(p[1], 16), p[3]
        elif len(p) == 3 and p[1] in 'tT':
            addr, size, name = int(p[0], 16), 0, p[2]
        else:
            continue
        if name.startswith(('.L', '__text_')) or addr in syms:
            continue
        syms[addr] = (name, size)
    return sorted((a, n, s) for a, (n, s) in syms.items())


def write(elf, out):
    fns = functions(elf)
    strs, offs, pos = [], [], 0
    for _, n, _ in fns:
        offs.append(pos)
        strs.append(n)
        pos += len(n) + 1
    with open(out, 'w') as f:
        f.write('/* generated by tools/mkksyms.py: the kernel\'s function names */\n')
        f.write('.section .ksyms,"a"\n.balign 8\n')
        f.write(f'.quad {len(fns)}\n')
        for (a, n, s), o in zip(fns, offs):
            f.write(f'.quad 0x{a:x}\n.long {o}, {s}\n')
        for n in strs:
            f.write(f'.asciz "{n}"\n')


def check(elf, table):
    want = [(int(a, 16)) for a in re.findall(r'^\.quad 0x([0-9a-f]+)$', open(table).read(), re.M)]
    have = [a for a, _, _ in functions(elf)]
    if want != have:
        sys.exit(f'mkksyms: {elf}: functions moved between the two links; the symbol table would be wrong')


if __name__ == '__main__':
    if sys.argv[1] == '--check':
        check(sys.argv[2], sys.argv[3])
    else:
        write(sys.argv[1], sys.argv[2])
